### ISSUE TITLE
Can I customize paths to import?

### ISSUE THREAD

**Issue by mysticatea** [esdoc/esdoc#10]
Hello.

The generated document shows a statement to import.

![import statement](https://cloud.githubusercontent.com/assets/1937871/8019794/9c0e7a24-0c9b-11e5-918d-38dedf9cadf7.png)

This is a good feature.
But I want to customize this path, can I do so?

This example,

1. `import CodeContractError from "code-contracts/src/CodeContractError.js"` is the path to raw source code. I build with Babel, so
2. `import CodeContractError from "code-contracts/lib/CodeContractError"` is correct. And actually, I want to rewrite it to below:
3. `import {CodeContractError} from "code-contracts"`

Thanks.

**Comment by h13i32maru** [comment]
@mysticatea Hello.

[config.importPathPrefix](https://esdoc.org/config.html) enables to customize import path. But the config can not support your case :cry: 

The config supports the following case:
1. ``src/foo.js`` is transpiled to ``out/src/foo.js``
2. ``config.importPathPrefix`` is ``"out"``
3. The generated document shows ``import Foo from 'out/src/foo.js'``

```json
{
  "source": "./src",
  "destination": "./out/doc",
  "importPathPrefix": "out"
}
```

And if ``main`` property in ``package.json`` is ``out/src/foo.js``, the generated document shows ``import Foo from 'your-package-name'``.

If you want to full customize import path, [config.scripts](https://esdoc.org/config.html) is maybe usefull.

**Comment by mysticatea** [comment]
Thank you, `config.scripts` is useful :)

I think very important the import statement showing, because it's the external interface.
If I got an idea for automation, I will make a PR.

**Comment by h13i32maru** [comment]
@mysticatea The idea (tracked by ``main`` in ``package.json``) is nice! But ``main`` property is not always exist.

I have other idea:
```json
{
  "source": "./src",
  "destination": "./out/doc",
  "importPathReplace": {
    "from": "^src/",
    "to":   "lib/"
  }
}
```

``importPathReplace`` is replace original import path with ``from`` and ``to``. 

Internal pseudo code:
```javascript
importPath = importPath.replace(new RegExp(from), to);
```

What do you think?

**Comment by mysticatea** [comment]
@h13i32maru It's nice!

There are packages that has optional sub modules, such as `"react/addon"`.
I think the `"importPathReplace"` option is very useful for that case.

**Comment by h13i32maru** [comment]
@mysticatea OK, I will implement the feature based on the idea.

By the way, could you tell me more about ``optional sub modules``?

**Comment by mysticatea** [comment]
For example, React.js has an optional sub module ["addons"](https://facebook.github.io/react/docs/addons.html).
Users can select whether or not use it.

So we use the package name + sub module name to import public sub modules: `import bar from "foo/bar";`.
It also is the external interface of packages.

**Comment by h13i32maru** [comment]
@mysticatea Thank you for telling me. That means, ``importPathReplace`` must be array.

e.g.

```javascript
importPathReplace: [
  {from: '^src/', to: 'lib/'},
  {from: '^lib/foo/bar.js', to: 'lib/submodule'}
]
```

- case 1:
  - ``src/a.js`` ->   ``lib/a.js`` -> ``lib/a.js``
- case 2:
  - ``src/foo/bar.js`` -> ``lib/foo/bar.js`` -> ``lib/submodule``

<br/>

I will try to implement this function in next version.

**Comment by h13i32maru** [comment]
I consider plugin feature.
https://github.com/h13i32maru/esdoc/issues/27

**Comment by h13i32maru** [comment]
@mysticatea 
I published [ESDoc Import Path Plugin](https://github.com/esdoc/esdoc-importpath-plugin) :rocket:  
You can customize import path to use this plugin with ESDoc@0.2.1
