### ISSUE TITLE
import path includes file extension

### ISSUE THREAD

**Issue by silkentrance** [esdoc/esdoc#100]
I have a code base that is transpiled from babel/es to 'mere' javascript. However, the generated import statements in the documentation include the '.es' extension.

Would it be possible to simply omit the extension, e.g.

```
import {foo} from 'src/source';
```

instead of

```
import {foo} from 'src/source.es';
```

This, of course, should also be supported by the import-path plugin.

Or, even make it configurable in esdoc.json, e.g.

```
{
    "extension": true|false
}
```

TIA! And thank you for your great work!

**Comment by h13i32maru** [comment]
@silkentrance I will try to support it at import path plugin in future. Please wait a moment.

**Comment by silkentrance** [comment]
@h13i32maru thanks, great!

**Comment by silkentrance** [comment]
@h13i32maru I think we can close this.
