### ISSUE TITLE
Does not recognize alternative export format

### ISSUE THREAD

**Issue by letmaik** [esdoc/esdoc#101]
When I directly write `export default class MyClass` everything works. But when I write `class MyClass` and then `export { MyClass as default }` esdoc ignores that, though this is valid syntax.

**Comment by h13i32maru** [comment]
@neothemachine Hi! Thanks for this issue!
I did not know the syntax. I will try to support it in future version. Please wait a moment.
Thanks.

**Comment by yogioba** [comment]
+1.  Looking forward to this fix.

**Comment by sunnylittle** [comment]
Concur, this is causing issues for me as well.

**Comment by h13i32maru** [comment]
I move this problem to [here](https://github.com/esdoc/esdoc/issues/361)
