### ISSUE TITLE
documentation getter/setters

### ISSUE THREAD

**Issue by christophehurpeau** [esdoc/esdoc#108]
getters and setters should be documented like a property

If there is only a getter, a information "readonly" could be displayed

What do you think ?

Here how to document getters/setters in jsdoc: https://github.com/jsdoc3/jsdoc/issues/973

**Comment by h13i32maru** [comment]
ESDoc already supports getter/setter.

```javascript
export default class MyClass {
  /**
   * @type {number}
   */
  get foo(){return 1;}

  /**
   * @type {number}
   */
  get bar(){return 1;}

  /**
   * @type {number}
   */
  set bar(v){}
}
```

<img width="319" alt="2015-10-10 19 30 47" src="https://cloud.githubusercontent.com/assets/985170/10410729/722a2c38-6f85-11e5-879c-797da7a0fde5.png">

**Comment by christophehurpeau** [comment]
My point was getters and setters are separated, in documentation.
The API user should not necessary know that this is a getter/setter instead of a simple property (could be a flag though) and in my opinion they should at least be combined.

**Comment by h13i32maru** [comment]
Properties and getter/setter are different. 
If getter/setter are combined, loses information(``get`` and ``set``) and displays incorrect documentation.
Separated getter/setter are not problem for users.

**Comment by yordis** [comment]
@h13i32maru why we can't just mark it as a property? Getter/Setter just create a property in the end, they are not function calls, instead, they are just properties in a class.

Separated getter/setter are not a problem for users, indeed, but it's not the best solution. They are getter/setter, not function.

:+1:  for this one.

**Comment by christophehurpeau** [comment]
I agree with @yordis 
User should not be aware that this property is a getter/setter

**Comment by h13i32maru** [comment]
```javascript
class Foo {
  constructor() {
    this.foo = 1;
  }
  
  get bar(){
    return 1;
  }
}

let foo = new Foo();
console.log(Object.keys(foo)); // ["foo"]
```

``foo`` and ``get bar()`` are different. Please use Plugin or API of ESDoc.

**Comment by yordis** [comment]
@h13i32maru What do you mean? Yes, they are different from the implementation but from the concept prospective they are the same.

You use both the same way: `foo.foo` and `foo.bar` but You can't do `foo.bar()` this will trigger an error which means that `bar` is actually an property of that class.

**Comment by yordis** [comment]
@h13i32maru can you elaborate why you don't want to fix this? I am still without get it and even more when you try to see this bug from the end result prospective. Take a look to other programming languages like C#, they have getter/setter and see how they do the Doc generation.

**Comment by h13i32maru** [comment]
This is a **not** bug. ESDoc generates directly the documentation from code without strange transform. ``get foo() / set foo()`` and ``.foo`` is different. If you do not like ESDoc, use other documentation generator.

**Comment by timdp** [comment]
@h13i32maru Sorry to unearth this thread, but I think you're misinterpreting the comments here. Yes, from a strictly semantical perspective, `inst.foo` and `inst.bar` are different in your example, but API docs get generated for the person *using* the API, and that person shouldn't be aware of the implementation. If the author of the API decides to change the implementation of `foo` or `bar` to either getter/setter or a regular object property, it won't affect the behavior at all. What matters is that it's a property that one can get and set from outside the class.

I originally came here looking for a way not to write redundant comments such as:

```
class A {
  /**
   * Description of b.
   *
   * @type {string}
   */
  get b () { return this._b }

  /**
   * Description of b.
   *
   * @type {string}
   */
  set b (value) { this._b = value }
}
```

Even if there's a different syntax or option which allows that, just being able to write `@property {string} Description of b.` would make *so* much more sense.

**Comment by hmil** [comment]
@timdp Agreed. That's part of the reason why I propose #256 . You could use `@ignore` to exclude getters and define the member with an `@member` tag.

**Comment by yordis** [comment]
@hmil @timdp still in WontFix label :disappointed: So I don't know how much movement will be here with that label on it

**Comment by tregusti** [comment]
Documentation should not describe the implementation, it should describe the user facing interface.

A user does not, and should not, care about the implementation. That is an implementation detail that has noting to do with the way a module is used.

I fully support at least an option do handle getter/setter pairs as a member. As mentioned in https://github.com/esdoc/esdoc/issues/108#issuecomment-205717296, if an implementer decides to change between a getter/setter pair and a plain member property, it should not in any way affect either the consumer of the API/module or the documentation.

**Comment by yordis** [comment]
@tregusti the actual issue is that `this.foo` is not the same as `this.foo()` and when you define a getter/setter you have to use it as the first one.

So @h13i32maru, yes is an issue because the `documentation` is telling you that you have a `function` when you really have a `property`. No matter what you do inside the `property` implementation or how you do it, you will always use it as a `property` and that's what matter for a documentation, like @tregusti documentation describes the API/Interface, not implementations details.

**Comment by tregusti** [comment]
@yordis Well, no. A getter and a setter is not documented ad a function. Not according to my own project output or the screenshot above.

The discussion is about the fact that internal implementation (`get`/`set`) is leaked to the user. And the issue starter asked for a way to mark a getter only property as readonly instead of as it is marked today, as a getter only.

**Comment by oravecz** [comment]
Is it possible to override this behavior in a plugin?

**Comment by oravecz** [comment]
Why, yes it is possible.
https://www.npmjs.com/package/esdoc-member-plugin

ESDoc is very well architected except for the templating. Appending a "readonly" or "writeonly" tag to the property is incredibly difficult. I don't see any support for extending an existing template, without forking the whole publishing plugin.
