### ISSUE TITLE
Support default value for optional parameters

### ISSUE THREAD

**Issue by christophehurpeau** [esdoc/esdoc#109]
Like jsdoc: http://usejsdoc.org/tags-param.html

```
/**
 * @param {string} [somebody=John Doe] - Somebody's name.
 */
```

Is it possible ?

**Comment by blindman** [comment]
https://esdoc.org/tags.html#optional-and-default

Is this what you're talking about?

**Comment by christophehurpeau** [comment]
Oh sorry.
My problem was space:

`@param {number} [index = -1]`

I think it worked fine with jsdoc, though

**Comment by h13i32maru** [comment]
@blindman Thanks for reply!
