### ISSUE TITLE
{@link} not being processed in method summary

### ISSUE THREAD

**Issue by andy-hanson** [esdoc/esdoc#110]
Run this code in an empty directory:

	echo '{"source": "./src", "destination": "./esdoc"}' > esdoc.json
	mkdir src
	echo -e '/** {@link func} is this. */\nexport function func() {}' > src/index.js
	esdoc -c esdoc.json
	cat esdoc/function/index.html

`{@link func}` will be processed for the detailed description of it but not for the summary.

esdoc/function/index.html line 61:

	<div data-ice="description">{@link func} is this.</div>

esdoc/function/index.html line 92:

	<div data-ice="description"><p><span><a href="function/index.html#static-function-func">func</a></span> is this.</p>

**Comment by h13i32maru** [comment]
@andy-hanson Hi! Thanks for this issue.
I reproduced it. I will fix it to next version. Please wait a little.

**Comment by h13i32maru** [comment]
I published v0.4.1 that fixed this issue.
