### ISSUE TITLE
Documenting Constants or Files (e.g Angular)

### ISSUE THREAD

**Issue by matthiasg** [esdoc/esdoc#111]
There does not seem to be a way to document anything inside a file that doesnt contain a Type:

e.g:

```
/** 
  * @name rsDocumentsService
  * @ngdoc service 
  * 
  * @description 
  */

import Application from '../application';
import Documents from './rs-documents';

Application.Services.factory('rsDocuments', [...Documents.$inject, Documents.factory]);
```

I know that `ngdoc` is not supported but i would like to have some kind of way to document that there is this file and it contains something like a `service` and here is a list of all such `service` things :)

**Comment by matthiasg** [comment]
alternatively `@file` or `@module` might make sense to support documenting at least a little. Goal is to have an entry on the left side navigation

**Comment by h13i32maru** [comment]
@matthiasg Hi! Thanks for this proposal.
But sorry, I do not plan to support this proposal. Because a file that does not contain Type is not need to users. ESDoc is **documentation generator**, but is not **source viewer**.

Sorry.

**Comment by matthiasg** [comment]
Well in our case it contains a Directive declaration (angular) which is internally implemented as a class. The important one for readers of our documentation is the directive. Without any way to document this ( or any other DI types ) we cannot really use esdoc sadly.

**Comment by h13i32maru** [comment]
Oh, sorry I mistake it. But I do not plan to support meta programming way.

Possibly, you can use ``@typedef`` for a Directive.

```javascript
/**
 * this is myDirective
 * @typedef {function(a: string): number} rsDirective
 */
```

**Comment by matthiasg** [comment]
Thanks .. Will try. 

----- Ursprüngliche Nachricht -----
Von: "Ryo Maruyama" <notifications@github.com>
Gesendet: ‎11.‎10.‎2015 02:34
An: "esdoc/esdoc" <esdoc@noreply.github.com>
Cc: "matthiasg" <mgt576@gmail.com>
Betreff: Re: [esdoc] Documenting Constants or Files (e.g Angular) (#111)

Oh, sorry I mistake it. But I do not plan to support meta programming way.
Possibly, you can use @typedef for a Directive.
/**
 * this is myDirective
 * @typedef {function(a: string): number} rsDirective
 */—
