### ISSUE TITLE
It doesn't seem to be possible to document class members.

### ISSUE THREAD

**Issue by mseddon** [esdoc/esdoc#112]
I have a simple class:

```javascript
class Vec2 {
    /**
     * Constructs a new 2-dimensional vector.
     * @param x the x-component of the vector.
     * @param y the y-component of the vector.
     */
    constructor(x, y) {
        /** @type {number} this description is ignored! */
        this.x = x;
        /** @type {number} so is this. */
        this.y = y;
    }
}
```

esdoc is correctly *finding* `x` and `y` as members, but I cannot figure out how to write a description for the `x` or `y` member.  Is this possible to achieve or a current limitation?

**Comment by h13i32maru** [comment]
@mseddon Hi! Thanks for this question.
``@type`` can not have description. Please see [@type](https://esdoc.org/tags.html#-type).

But you can write description as following code:

```javascript
class Foo {
  constructor(x) {
    /**
     * this is x.
     * @type {number}
     */
    this.x = x;
  }
}
```

And for now, I do not plan to support description of ``@type``.

**Comment by mseddon** [comment]
Hi! That did the trick, thanks!

**Comment by h13i32maru** [comment]
:+1:
