### ISSUE TITLE
ESDoc support inside of AMD modules

### ISSUE THREAD

**Issue by d-koppenhagen** [esdoc/esdoc#113]
Hi guys, I am using `gulp-esdoc` to create a documentation for my code. I tried to wrap the code into an AMD module like that:
```javascript
'use strict';
define(function(){
  class Applicant {
     /**
      * @constructor
      */
     constructor() {
       /**
        * @type {String} name
        * @desc Name of the applicant
        */
       this.name = null;
     }
    /**
     * @desc let the applicant say hello
     * @return {String}
     */
     sayHello() {
        var text = 'hello, I am '+this.name+'!';
        return text;
     }
  }
  return new Applicant();
}
```
Unfortunately after wrapping this into the `define(function(){ ... })`, ESDoc will not transform the comments inside the module. Is there any solution to solve this?

**Comment by h13i32maru** [comment]
@d-koppenhagen Hi! Thanks for this question.
Sorry, ESDoc does not support ADM modules. ESDoc supports ES6 modules(``import/export``).
If you use babel, you can use ``import/export`` with ``babel --modules amd``.
