### ISSUE TITLE
Seems to crash on Arrow functions

### ISSUE THREAD

**Issue by soluml** [esdoc/esdoc#114]
Using arrow functions with Babel as my transpiler.  Running esdoc, I'm getting an error using code like this.

`this.getIframe = (what) => {
    ...code here...
};`

Get this error: 

    this.getIframe = (what) => {
                            ^^
    SyntaxError: Unexpected token =>

**Comment by h13i32maru** [comment]
@soluml Hi! Thanks for this issue.
Please tell me repository url or minimum code for reproducing this issue.
