### ISSUE TITLE
Output formater

### ISSUE THREAD

**Issue by zeitiger** [esdoc/esdoc#115]
Hi,
first thanks for this tool that helps me a lot. 

I see your tool make an report about dismatches between doc and code and also about coverage. Is it possible to format this information e.g. in checkstyle or cobertura format to publish data in a jenkins build?

**Comment by raveclassic** [comment]
@zeitiger AFAIK Esdoc [plugin api](https://esdoc.org/api.html) has a method `onHandleHTML` - you could use that to modify output as you need.

**Comment by zeitiger** [comment]
:+1:

**Comment by zeitiger** [comment]
Sadly `onHandleHTML` isn't the right target, I need access the `_results` from /src/Publisher/Builder/LintDocBuilder.js

**Comment by h13i32maru** [comment]
@zeitiger Hi! Thanks for this question.
For now, please customize ``coverage.json`` in destination directory after generating.
I want to customize ``coverage.json`` with plugin in future version.

**Comment by h13i32maru** [comment]
@raveclassic Thanks for reply!

**Comment by zeitiger** [comment]
@h13i32maru 
Okay so coverage.json is the source for coverage information. Great to hear from you want to tackle this with additional plugins. :+1: 
What about lint errors? How I understand the LintDocBuilder it output the information only via stdout. Right :grey_question:

**Comment by h13i32maru** [comment]
@zeitiger For now, Lint result is not output. I will enhance plugin feature in future.
https://github.com/esdoc/esdoc/issues/145
