### ISSUE TITLE
@param with link is documented wrong

### ISSUE THREAD

**Issue by andy-hanson** [esdoc/esdoc#119]
I'm documenting this code:

	/**
	@param {string} x The only parameter of {@link foo}.
	*/
	export function foo(x) {}

It produces this warning:

	warning: signature mismatch: foo src/file.js#1
	0| /**
	1| @param {string} x The only parameter of {@link foo}.
	2| */
	3| export function foo(x) {}

The documentation looks like:

	import {foo} from './src/file.js'
	Params:
	Name	Type	Attribute	Description
	.	string

The name of the parameter has become `.` rather than `x`.

The error is fixed by replacing `{@link foo}` with `foo`.

**Comment by h13i32maru** [comment]
@andy-hanson This is ESDoc bug. I will fix it. Thanks!

**Comment by h13i32maru** [comment]
this is fixed by https://github.com/esdoc/esdoc/pull/105

**Comment by h13i32maru** [comment]
I published v0.4.1 that fixed this issue.

**Comment by andy-hanson** [comment]
The type now shows up correctly, but the link doesn't.
It looks like this:

	Name	Type	Attribute	Description
	x	string		
	The only parameter of <span><a href="function/index.html#static-function-foo">foo</a></span>.
