### ISSUE TITLE
esdocs ignores unnamed exports like `export default `

### ISSUE THREAD

**Issue by kushdilip** [esdoc/esdoc#120]
I am trying use esdocs for Ember apps. Ember doesn't uses class anywhere yet and all the import/exports are basically dealing with objects and when I run esdoc on the project it just ignores everyting. 
e.g below is a helper from project .

`./addon/helpers/format-date-from-now.js `
```
export default Ember.Helper.helper(function (params, hash) {
  let [value] = params;
  let withoutSuffix = hash.withoutSuffix;
  if (value) {
    return moment(value).fromNow(withoutSuffix);    
  }
});
```

`esdocs.json`
```
{
  "source": "./addon",
  "destination": "./out/esdoc"
}
```

**Comment by h13i32maru** [comment]
@kushdilip Hi! Thanks for this question.
ESDoc does not support it. ESDoc supports a simple ``class/function`` in main stream.
In future, I might support it in plugin.

Thanks.

**Comment by kushdilip** [comment]
@h13i32maru can you suggest any workaround for this. I really want to use esdoc for my ember projects right now.

**Comment by silkentrance** [comment]
@kushdilip how about assigning the result from helper() to a const helper and then exporting that, adding required documentation comments to it?

**Comment by kushdilip** [comment]
@silkentrance I have hundreds of helpers & components like this across projects. I don't think it's a good idea to modify all of them.

**Comment by h13i32maru** [comment]
@kushdilip For now, I can not suggest workaround to you. Sorry.

**Comment by gthomas-appfolio** [comment]
+1

**Comment by noahbenham** [comment]
IMO this is a major project flaw that needs to be fixed. I would like to use esdoc but without supporting this, I won't be able to.

**Comment by dougdomeny** [comment]
`esdoc`'s `esdoc-standard-plugin` has an option to document unexported identifiers. You may also with to disable undocumented identifiers.
```
  "plugins": [
    {
      "name": "esdoc-standard-plugin",
      "option": {
        "accessor": {
          "access": [ "public", "protected" ],
          "autoPrivate": true
        },
        "undocumentIdentifier": { "enable": false },
        **"unexportedIdentifier": { "enable": true },**
```
