### ISSUE TITLE
@typedef with function property will generate insufficient documentation

### ISSUE THREAD

**Issue by silkentrance** [esdoc/esdoc#125]
See

http://inxs.es.coldrye.eu/projects/inxs/doc/dev/typedef/index.html#static-typedef-AbstractBroker

for an example.

The source for that being here

https://github.com/coldrye-es/inxs/blob/master/src/inxs.es#L103

**Comment by h13i32maru** [comment]
Your source is invalid. See https://esdoc.org/tags.html#function

```javascript
/**
 * @typedef {Object} AbstractBroker
 * @property {function(iface: InterfaceType): Object} getInstance
 * @property {AbstractLogger} [logger]
 * @property {function(): void} [validateInterfaces]
 */
```

**Comment by silkentrance** [comment]
@h13i32maru thanks for pointing that one out, did not see it.

**Comment by h13i32maru** [comment]
:+1:
