### ISSUE TITLE
Link in param description ends up as literal HTML

### ISSUE THREAD

**Issue by andy-hanson** [esdoc/esdoc#130]
I'm documenting this code:

	/** @param {string} x The only parameter of {@link foo}. */
	export function foo(x) {}

The resulting documentation looks like:

Name | Type | Attribute | Description
--- | --- | --- | ---
x | string | | The only parameter of \<span>\<a href="function/index.html#static-function-foo">foo\</a>\</span>.

**Comment by h13i32maru** [comment]
@andy-hanson This is ESDoc bug. Thanks.

**Comment by h13i32maru** [comment]
I fixed this issue at v0.4.2.
