### ISSUE TITLE
Fails to create type links for union in record

### ISSUE THREAD

**Issue by andy-hanson** [esdoc/esdoc#133]
I'm documenting this code:

```
/** @return {{a: string|number}} */
export function foo() {}
```

The type shows up as `{a: number | string}` as plain text without any links for the types.
It successfully creates type links for `/** @return {number|string} */` and `/** @return {{a: string}} */`.

**Comment by h13i32maru** [comment]
@andy-hanson For now, ESDoc does not support ``record type + union type``. I might support it in future version. 

The workaround for this:
```javascript
/**
 * @return {Object}
 * @property {string|number} a - this is property of result.
 */
export function foo() {}
```

See https://esdoc.org/tags.html#-return

**Comment by h13i32maru** [comment]
Please check the latest ESDoc that supports it.
