### ISSUE TITLE
Not generating any identifier.

### ISSUE THREAD

**Issue by vekexasia** [esdoc/esdoc#134]
Hello there i tried to generate esdoc using thi project but i'm unable to see ANY classes. i've just one in my lib/ folder which contains this code:

```javascript
class TestClass {
  oneMethod(){}
  testMethod(){}
}
```

I can see in ~./jsdoc/ast/source` a file named test.js contaiing all the MethodDefinitions and the ClassDeclaration but `identifiers.html` is basically empty - here is an extract:

```html
</header>

<nav class="navigation" data-ice="nav"><div>
  <ul>
    
  </ul>
</div>
</nav>

<div class="content" data-ice="content"><h1>References</h1>






</div>

<footer class="footer">
```
esdoc version is 4.0.1 and i'm using the following esdoc.json
```json
{
  "source": "./lib",
  "destination": "./jsdoc"
}
```

**Comment by andy-hanson** [comment]
Try using `export class TestClass ...`

**Comment by h13i32maru** [comment]
@vekexasia Normally, ESDoc targets at ``export`` or ``export default`` identifier.

```javascript
export class TestClass {
  oneMethod(){}
  testMethod(){}
}
```

Or, you can use ``config.unexportIdentifier: true``. See https://esdoc.org/config.html#full-config for more information.

**Comment by vekexasia** [comment]
Thanks :)

**Comment by h13i32maru** [comment]
:+1:
