### ISSUE TITLE
No way to end @example or intersperse multiple @example blocks

### ISSUE THREAD

**Issue by typhonrt** [esdoc/esdoc#136]
Presently ESDoc doesn't allow a way to end an @example block. One can create a second or follow up @example block, but no further normal blocks of documentation are possible. This makes long documentation blocks with multiple example blocks problematic. The worst case example I can show is from this private repo where I had to hack things together w/ bad formatting via using `<code>` blocks:
http://js.typhonrt.org/docs/backbone-parse-typhon-es6/class/backbone-parse-typhon-es6/src/BackboneQuery.js~BackboneQuery.html

As you can see one can use @example at the bottom of the block, but it's impossible to use @example multiple times interspersing it with other non-example documentation.  

Suggestion: Provide a way to end an @example block; perhaps with multiple empty lines (2-3) or other directive.

**Comment by h13i32maru** [comment]
@typhonrt I do not understand your comments... Please post your expecting code.

The following code is valid:
```javascript
/**
 * @example
 * const str = 'this is first example';
 */
export class Foo1 {}

/**
 * @example
 * const str = 'this is first example';
 *
 * @example
 * const str = 'this is second example';
 */
export class Foo2 {}
```

And [Manual Feature](https://esdoc.org/feature.html#integration-manual) might help you.

**Comment by typhonrt** [comment]
This suggestion / feature is alleviated now that I know that markdown is supported. 

The above example that you give is basic and works as expected. My comment was on inline `@example` usage when it may be something more like:

```
/**
 * @example
 * const str = 'this is first example';
 */
export class Foo1 {}

/**
 * Some description for class
 *
 * First example about some neat feature.
 * @example
 * const str = 'this is first example';
 *
 * 
 * More text describing other features and the next example
 * @example
 * const str = 'this is second example';
 */
export class Foo2 {}
```

Currently ESDoc groups all examples at the bottom of the generated documentation block and doesn't allow interspersed `@example` blocks. It will include the inline text "More text describing other features and the next example" into the example blocks when it would be great for it to revert back to normal description block. This isn't so much of a problem as there is markdown support, but it would be nice to support inline examples as the syntax is just a bit nicer.

IE with markdown support the example above becomes:
```
/**
 * @example
 * const str = 'this is first example';
 */
export class Foo1 {}

/**
 * Some description for class
 *
 * First example about some neat feature.
 * **Example:**
 * ```
 * const str = 'this is first example';
 * ```
 *
 * More text describing other features and the next example
 * @example
 * const str = 'this is second example';
 */
export class Foo2 {}
```

Supporting inline or interspersed `@example` tags just allows a bit more syntactic sugar over having to use markdown for inline examples.

**Comment by h13i32maru** [comment]
I understood your suggestion. However I do not apply the suggestion. Because ESDoc syntax will be too complex. Please use [caption](https://esdoc.org/tags.html#-example), markdown or [manual integration](https://esdoc.org/tutorial.html#integrate-manual).
