### ISSUE TITLE
Provide more document tags for "onHandleTag" manipulation

### ISSUE THREAD

**Issue by typhonrt** [esdoc/esdoc#137]
Presently working with tags is problematic especially when it comes to names of files and associated file paths. "longname" (and even "name" seemingly) is used to create the file path in various parts of the ESDoc architecture. There should be separate tags for "filepath" and "filename" from "name" and "longname". Perhaps also adding in "shortname" which defaults to "longname" and can be modified as desired where visible / normalized paths / names should be used. 

An example of this is the search_index.js file which generates names of files based on "longname". Since longname also defines the file path it's not possible to change the script/search_index.js generation based on the actual desired normalized name for a file. 

As a solution in my JSPM ESDoc plugin I have to completely rewrite search_index.js in "onComplete" replacing long names with the actual desired normalized name for a file. 
https://github.com/typhonjs/backbone-parse-es6/blob/master/esdoc-jspm-plugin.js#L198

Similar replacement also needs to be done for all generated HTML files. Providing a short or normalized name separate of "name" or "longname" and a potentially new "filepath" "filename" tag should resolve this issue in a much cleaner manner.

**Comment by h13i32maru** [comment]
@typhonrt Thanks for this suggestion. I consider it.
