### ISSUE TITLE
New @decorator tag

### ISSUE THREAD

**Issue by silkentrance** [esdoc/esdoc#138]
Hi there, how about a new @decorator tag?

Here, one must be able to distinguish between property, method and class level decorators.

E.g.

```
/**
 * @decorator {class}
 */
function ...
```

A decorator that can be used with either class, property or method would then be annotated as such

```
/**
 * @decorator {class|method|property}
 */
function ...
```

Additionally, we might require that a decorator can only be used on static properties a/o methods, e.g.

```
/**
 * @decorator {static property}
 */
function ...
```

In the documentation itself, decorators should be marked as such, e.g. 'D' for decorator.

**Comment by h13i32maru** [comment]
@silkentrance Thanks for this suggestion. However I do not support ``@decorator``. Because ES.next might support decorator syntax. So, ``@decorator`` is not needed.

**Comment by h13i32maru** [comment]
Oh, I mistake your ``@decorator``. I will your suggestions to reference. Thanks.
