### ISSUE TITLE
Exit with code != 0 in case of error when using ES7+ features and not using the es7 plugin

### ISSUE THREAD

**Issue by silkentrance** [esdoc/esdoc#140]
You will warn 'error' about issues with the source but will not exit the process so that a build may fail accordingly, e.g.

```
error: could not parse the following code. if you want to use ES7, see esdoc-es7-plugin(https://github.com/esdoc/esdoc-es7-plugin)
...
```

It would be nice for esdoc tol fail the build in case of such an error.

**Comment by h13i32maru** [comment]
@silkentrance Thanks for this suggestion. I do not change exit code. But I change error message to warning message. https://github.com/esdoc/esdoc/issues/146
