### ISSUE TITLE
HTML tags in comments are now escaped (0.4.0 to 0.4.1)

### ISSUE THREAD

**Issue by typhonrt** [esdoc/esdoc#142]
Since I didn't see this in CHANGELOG.md I'm just confirming if HTML tags in comments are now going to be escaped as this has changed between ESDoc 0.4.0 to 0.4.1 Is this a bug or permanent change in ESDoc? I assume the latter, but making a note for others here as well.

It seems to be a good change as formatting in comments is now preserved without the need for `<p> or <br>`. It also will potentially make my suggestion for esdoc-hosting safer though one would still need to search for any added `<script>` tags:
https://github.com/esdoc/esdoc-hosting/issues/7

**Comment by typhonrt** [comment]
After updating my projects docs I'm curious if it's possible to keep `<b>`, `<u>`, `<code>`, and `<pre>` tags as that could be nice for styling; I assume it might be all or nothing though. If there are other directives that ESDoc understands for bold / underline that is certainly fine too.

**Comment by h13i32maru** [comment]
@typhonrt 
> Is this a bug or permanent change in ESDoc?

This is permanent change. ESDoc escapes HTML tags for safety. You can use markdown(github flavored markdown) in comment. See https://esdoc.org/tags.html#-desc

**Comment by typhonrt** [comment]
Thanks for the heads up on markdown styling being available. I missed that in the ESDoc documentation for `@desc`. Perhaps add info about markdown support to the features & tutorial section. Cheers!
