### ISSUE TITLE
ESDoc + JSPM / SystemJS plugin

### ISSUE THREAD

**Issue by typhonrt** [esdoc/esdoc#143]
Greets Ryo et al...

Thanks again for ESDoc. I just published a rather useful plugin for those using [JSPM](http://jspm.io) / [SystemJS](https://github.com/systemjs/systemjs) for package management. It allows a local source root + any number of JSPM managed packages to be linked together to generate end to end documentation across multiple source repos / packages. I've tested it rather thoroughly and will be actively maintaining it. Could you add a link on the ESDoc site perhaps? I also posted this message here so folks can perhaps find info on this plugin when searching issues. You can close this issue when you get to it. 

https://www.npmjs.com/package/esdoc-plugin-jspm

I'd be glad to chat when you get a chance on how the ESDoc hosting service could pickup the output of this plugin... See the issue I opened here for that:
https://github.com/esdoc/esdoc-hosting/issues/7

Cheers...

**Comment by h13i32maru** [comment]
@typhonrt Awesome! Thank you for this plugin!
I will check the plugin in order to add hosting service.
