### ISSUE TITLE
type in @param

### ISSUE THREAD

**Issue by ouhouhsami** [esdoc/esdoc#147]
Hi there, 

(First, thanks for this great piece of software!).

I'm trying to document some method using an audiocontext param (https://developer.mozilla.org/fr/docs/Web/API/AudioContext). I wrote: 
```
@params {AudioContext} audioContext - an AudioContext instance
```
But the parser doesn't recognize the {AudioContext}, as it recognize the {number} ... type definition.

What must I do to have a link to https://developer.mozilla.org/fr/docs/Web/API/AudioContext in the generated documentation for {AudioContext} type?

Best,

**Comment by h13i32maru** [comment]
@ouhouhsami Hi! Thanks for this question.
You can use three ways.

(1) use ``@external``

```javascript
/**
 * @external {AudioContext} https://developer.mozilla.org/fr/docs/Web/API/AudioContext
 */
```

Please see https://esdoc.org/tags.html#-external for more information.

(2) use ``@typedef``
```javascript
/**
 * @typedef {Object} AudioContext
 * @see https://developer.mozilla.org/fr/docs/Web/API/AudioContext
 */
```

Please see https://esdoc.org/tags.html#-typedef for more information.

(3) send PR to ESDoc
Add ``AudioContext`` to ESDoc internal.
Please see https://github.com/esdoc/esdoc/blob/master/src/BuiltinExternal/WebAPIExternal.js

**Comment by ouhouhsami** [comment]
Well, just sent a PR ;) Thanks for your answer.

**Comment by h13i32maru** [comment]
:+1:
