### ISSUE TITLE
@inheritDoc not working?

### ISSUE THREAD

**Issue by vekexasia** [esdoc/esdoc#148]
Hello there,

i've this:

``` js
export class BaseApiError extends Error {
  /**
   * @param message the reason why this error occurred
   */
  constructor(message) {
    super();
    if (Error.hasOwnProperty('captureStackTrace'))
      Error.captureStackTrace(this, this.constructor);
    else
      Object.defineProperty(this, 'stack', {
        value: (new Error()).stack
      });

    Object.defineProperty(this, 'message', {
      value: message
    });
  }

  /**
   * @return {number} HTTP status code to describe the error.
   */
  code(){}
}
```

& 

``` js
/**
 * Error object describing a Bad Request Error.
 * It might occur when the given parameters are not complying the requirements for the API
 */
export class BadRequestError extends BaseApiError {

  constructor(message) {
    super(message);
  }

  /**
   * @inheritDoc
   */
  code() {
    return 400;
  }
}
```

The generated doc for `BadRequestError` does not pass the `BaseApiError.code` documentation. 

Is there a way ?

**Comment by h13i32maru** [comment]
@vekexasia Hi! Thanks for this question.

ESDoc does not support ``@inheritDoc``. ESDoc automatically detect inherited methods. However it does not override documentation by parent.
<img width="256" alt="2015-10-26 22 45 32" src="https://cloud.githubusercontent.com/assets/985170/10730447/5166bef2-7c33-11e5-8057-f8efa2dd7a08.png">

I will consider the following feature:
If a method has no documentation and parent has documentation, ESDoc overrides documentation by parent.

**Comment by vekexasia** [comment]
Yes please also for interfaces. It would be awesome.

**Comment by kylestev** [comment]
:+1: I would love this feature. I agree that the mechanism for inheriting docs should be declaring it in an ancestor and not "overriding" the doc in the child class.

Looks like I'll copy and paste docs between classes until this works :wink:

**Comment by mmoss** [comment]
:+1:

**Comment by vekexasia** [comment]
Hey guys any news on inheriting docs?

**Comment by rapodaca** [comment]
I'd also find it useful for inherited functions to display the parent's JSDoc.

As it stands now, ESDoc loses type information, giving all parameters and return values the type (*), which seems misleading.

One case to consider: interfaces.

ESDoc does appear to support the <code>@interface</code>/<code>@implements</code> tags. So the documentation override feature might need to account for both of these cases:

- an exported class uses the <code>extends</code> keyword
- an exported class uses the <code>@implements</code> tag but no <code>extends</code> keyword

**Comment by aaronmcohen** [comment]
+1

**Comment by jeremymlane** [comment]
+1

**Comment by h13i32maru** [comment]
I supported to automatically take description from super class method. And I will release in next version.

**Comment by engelen** [comment]
Has anything been implemented that solves this issue? I cannot get the documentation of a parent class method to be copied to the child class method.
