### ISSUE TITLE
Some missing tags and a crash

### ISSUE THREAD

**Issue by julianjensen** [esdoc/esdoc#153]
First of all, thanks for a great tool and good looking output. It has restored my faith in JSDoc tags. However, some issues have arisen that has caused some problems.

* No support for synonyms. Since these just duplicate functionality, they should represent any real work to put in. Since my code uses them, it would be nice if they were supported right out of the box. Some common ones that cause me to do global search-and-replace are @prop for @property and @description for @desc. Also, I use WebStrom which automatically adds JSDoc tags and it uses @returns instead of @return so that's an important synonym.
* @extends (synonym @augments) doesn't seem to work for @typedef objects. I have a base object that I have defined via @type (it has a bunch of associated @property (or @prop) tags. Later, I define another object using @typedef that adds additional fields to the original object. This doesn't seem to work. Here a simple contrived example: 
```js
/**
 * @typedef {object} SomeObject
 * @property {string} name  The name of the object
 * @property {number} id     The ID of the object
 */

// ...

/**
 * @typedef {object} ExtendedObject
 * @extends SomeObject
 * @property {number} age   The age of the thing
 */
```
* HTML tags. In some circumstances, I have added HTML comment to make some of the comment read better. Here's an example:
```js
/**
 * @description
 * Handle all things related to text entries. For a description of the raw text
 * input format, see {@link TextEntry}
 *
 * We need to be able to do the following:
 * <ul>
 *     <li>Read an array of {@link TextEntry} objects from input</li>
 *     <li>Read an individual entry at any time</li>
 *     <li>Create a new empty text class</li>
 *     <li>Add a new single entry to class</li>
 *     <li>Create new empty single entry</li>
 *     <li>Delete entry or all entries</li>
 *     <li>Delete entire text class</li>
 * </ul>
 */
```
This fails in a variety of ways:
1. It doesn't understand @description which should be @desc
2. It doesn't seem to understand @link, which is very similar to \@see
3. It doesn't use the HTML, it just shows the HTML raw, i.e. replaces '<' with &lt; or the equivalent.
* Finally, using JSDoc I discovered that ```Array.<string, object>``` could be written as ```Array<string, object>``` which I think looks cleaner and, because I have to cross-compile to C#, makes life a little easier. However, this crashes ESDoc. By re-writing them, it can be made to work. Again, I had to do a global search-and-replace. I originally had ```@typedef {Array} List``` and then ```List<string, object>``` which was very nice, but that was pushing things a bit. :) Anyways, I tracked it down to crashing in _src/Publisher/Builder/DocBuilder.js_ at line 704, I think it was. No 'replace' method on 'undefined'. Could be as simple as adding a ```\.?``` to the RegExp?

So, to wrap up, I love the project but would like to see these issues fixed. At some point, if you're busy and fixing these will take considerable time, I might fork esdoc and make the fixes myself (I would share them back, of course) but I don't see myself having the time for a while (200% allocation in every sprint these days).

Thanks again for all the great work,
Julian

**Comment by blindman** [comment]
I can't address all of these now but I'll hopefully come back to the ones I missed in the not so distant future.

1) I've added alias tags for @desc/@description and @prop/@property.  It seems like the @returns tag [already exists](https://github.com/esdoc/esdoc/blob/master/src/Doc/AbstractDoc.js#L387-L395) as an alias for @return.  The reference in https://esdoc.org should be updated to reflect this fact as well as the new aliases.

3.1) The @description tag will work with the new commits
3.2) I copied and pasted your code verbatim and the @link tag did not break
3.3) I didn't experience an issue where raw HTML was visible in the documentation, could you provide some screenshots or a more in-depth code sample of what you're seeing?

4) The shorthand you mention seems to be [JSDoc's Google Closure Compiler integration](http://usejsdoc.org/tags-type.html) of their [Type Expressions](https://developers.google.com/closure/compiler/docs/js-for-compiler#types) I'm not 100% sure about this but JSDoc doesn't mention the syntax you have written down in its own docs.  I can try to test out your solution at some point for this but you're also welcome to test it out on your own machine with the directions [here](https://github.com/esdoc/esdoc/blob/master/CONTRIBUTING.md#install-from-head).

Here is a screenshot from my esdoc generation with the new @description tag, the pre-existing @returns tag, and a link reference where the url is visible in the bottom left.

![screen shot 2015-10-30 at 6 41 28 am](https://cloud.githubusercontent.com/assets/850522/10843790/72751292-7ed1-11e5-8afe-f0350796885e.png)

**Comment by julianjensen** [comment]
Thank for the reply. I have been able to make some more things work as I've been looking through the esdoc source. It would appear that esdoc is simply stricter (as in, more correct) about what tags can be applied where and how. I might be able to reconstrcut the HTML issue but I would have to go back a few versions. I have since re-written my many of my more involved descriptions using *markdown*. JSDoc automatically converts certain descriptions to *markdown* (supposedly), and I assumed that ESDoc didn't do this. I might for all I know. But I ended up writing a plugin. (Great plugin system, by the way. It took me all of 5 minutes to write a plugin that converts some descriptions to *markdown*).

Here's what my complete and final plugin code looks like:
```js
'use strict';

var marked = require( 'marked' );

marked.setOptions( { sanitize: true } );

/**
 * Handle the tags.
 *
 * @param {object} ev   - The event object from ESDoc
 */
exports.onHandleTag = function( ev ) {
    var tag = ev.data.tag;

    if ( ~[ 'class', 'constructor', 'method' ].indexOf( tag.kind ) && tag.hasOwnProperty( 'description' ) && !!tag.description )
        tag.description = marked( tag.description );
};
```
I suspect that many of the issues I had with the tags were a combination of JSDoc being lenient, my editor (with *jscs*) complaining, and me playing fast and loose with the tags, that caused many of my issues. The crash is still real, though, especially in the light that the comments in the ESDoc source uses the word "hack" on several occasions. :)

By the way, the JSDoc tag list on the their homepage [JSDoc](http://usejsdoc.org/) lists the synonyms in parentheses right next to the main tag.

It's possible that I got some JSDoc information from the Closure compiler docs since I find the JSDoc examples to never quite cover my situations. I can only assume that my code is unusual in some aspects, which is probably true.

As I work with my documentation some more, I will keep an eye out for issues and be sure to do better tests. :)

Finally, a couple of things:

Anything that is defined in the module scope as a var:

```js
var MyModule = require( './some-module' ),
    Other = require( './other-module' );
```

shows up in the documentation, even though I don't export *private* variables. These variables (in CommonJS) are obviously not global or exported. I'm assuming that it's just because ESDoc doesn't speak Node.js. The workaround, for now, is this:

```js
    /** @private */
var MyModule = require( './some-module' ),
    Other = require( './other-module' );
```

which stops them from showing up in the docs.

Also, my company requires me to provide documentation in **Confluence** which I did in the past using _jsdoc-to-markdown_ (we have a Confluence plugin that reads *markdown* [badly]) but that option is no longer working for me due to ES6 usage. Using the plugin system, I could conceivably write one and started to do so but ran into an issue. It can be worked around, of course. I was hoping to convert the HTML to markdown but there is no easy way to know what file goes with what HTML when it gets sent to the handler. Unlike the *tag* handler, the *HTML* handler only gets the HTML and no other info. Eventually, I will probably just generate the *markdown* at the *tag* stage, instead. I was just hoping for an easy answer. :)

Anyway, once again, thank you very much for the project and this response. I'll stay in touch as I find stuff or find that I might be helpful.

Julian

P.S. I didn't read through this again for errors due to it being my birthday and dinner is on the table. I apologize for any errors.

**Comment by blindman** [comment]
Heya @julianjensen, I'm not able to get a full response to you right now but I'll get back to you hopefully Monday but potentially Wednesday the latest.

P.S. This is really creepy but today is my birthday as well and I'm a few deep and heading out to a mischief night party.  Enjoy your birthday dinner, from a fellow pre-Halloween birthday celebrator.

**Comment by h13i32maru** [comment]
@julianjensen Hi! Thanks for this issue.

1) synonyms
I will consider it carefully. Because A lot of tags bring complexity.

2) extend for typedef
I split to a issue https://github.com/esdoc/esdoc/issues/177

3) HTML in description
ESDoc does not support HTML in description. Please use markdown. And ``{@link TextEntry}`` works fine in my environment.

```javascript
/**
 * Handle all things related to text entries. For a description of the raw text
 * input format, see {@link TextEntry}
 *
 * We need to be able to do the following:
 * - Read an array of {@link TextEntry} objects from input
 * - Read an individual entry at any time
 * - Create a new empty text class
 * - Add a new single entry to class
 * - Create new empty single entry
 * - Delete entry or all entries
 * - Delete entire text class
 */
export function foo(){}
```

4) generics
ESDoc supports ``Array<foo, bar>``. Please see https://esdoc.org/tags.html#generics

5) does not show in documentation
You can use ``@ignore`` or ``config.unexportIdentifier``. Please see following link.
- https://esdoc.org/tags.html#-ignore
- https://esdoc.org/config.html

**Comment by h13i32maru** [comment]
@blindman Thanks for response!

**Comment by h13i32maru** [comment]
Please see https://github.com/esdoc/esdoc/pull/156
