### ISSUE TITLE
Documenting multiple functions or methods with the same name.

### ISSUE THREAD

**Issue by virtyaluk** [esdoc/esdoc#154]
Hi there!

I've noticed, that the library does not generate multiple documentation for one method\property\class\whatever.

Here what I mean. I have next code:

```js
/**
 * First description
 * @returns {PaperNavDrawer}
 */
/**
 * Second description
 * @returns {PaperNavDrawer}
 */
hide() {
}
```
And esdoc only generates documentation based on very last doc-comment.

My code has several functions that behave differently depending on given data and I want to describe these differences. How can I do that?

Thanks in advance.

**Comment by blindman** [comment]
As far as I know, ESDoc (and probably JSDoc too) only parse one comment block per function declaration.  I (personally) don't think it would be a smart idea to allow multiple comment blocks for multiple reasons.

As for other possible ways of commenting in this scenario, [@desc](https://esdoc.org/tags.html#-desc) supports markdown so you could write the @desc tag to separate the different behaviors of a single function and use the [union syntax](https://esdoc.org/tags.html#union) in your [@return](https://esdoc.org/tags.html#-return) tag to reflect the different parts of the @desc tag.

**Comment by virtyaluk** [comment]
@blindman [The fact](https://code.google.com/p/jsdoc-toolkit/issues/detail?id=276#c3) is that jsdoc really does support documenting multiple functions with the same name.

**Comment by blindman** [comment]
@virtyaluk Interesting, they're technically not the same name but it achieves what you're looking for.  If you happen to have a JSDoc'd function like that I'd be interested in seeing the doc output that is generated.  He does offer the same markup solution I was talking about but I agree that is a bit bulky.

With that approach, I'll see if I can look into implementing something along those lines this weekend but I can't make any promises (and maybe someone can beat me to it).

**Comment by devongovett** [comment]
It would be useful to be able to document methods that allow different signatures.

```javascript
doSomething(a, b) {
  if (typeof a === 'object) {
    b = a.b;
    a = a.a;
  }

  // do something with a,b
}
```

This example allows passing either two numbers (a, b), or an object with { a, b } properties. There isn't really a good way to document this using esdoc currently. You could mark a as `{number|object}` and b as optional, but it's not very clear to the reader. I'd say it should be possible to make two comment blocks to document the two signatures separately, and have them listed in the output docs separately as well.

**Comment by h13i32maru** [comment]
@virtyaluk Hi! Thanks for this suggestion.
However I does not support multiple comment. Because some reasons.

1. If supports multiple comment, ESDoc internal is too complex.
2.Personally I do not like the multi type arguments and multi behavior function.

Please use markdown in description.
