### ISSUE TITLE
Default value for @typedef properties

### ISSUE THREAD

**Issue by kctang** [esdoc/esdoc#155]
I am trying to define an object with specific properties with default values. I don't think it is possible to specify "12345" as the default value in @property like the example below. A similar pattern seems possible with @param.

    /**
     * @typedef {object} MyObj
     * @property {number} [prop1=12345] Property 1
     */
    /**
     *
     * type {object}
     * @property {MyObj} [prop1] Object to define my properties
     */
    var myObj = {
      prop1: 12345
    };

Can you advise if this should be a feature request, should not be done or is possible in ways I am not aware of?

**Comment by h13i32maru** [comment]
@kctang Hi! Thanks for this question.
Please use ``@property {MyObj} [prop1=12345] ...``, because ``var myObj = {prop1: 12345}`` is not default value syntax. So ``{ }`` does not have the syntax. But ``function foo(p = 12345)`` is default value syntax in ES6.
