### ISSUE TITLE
Questions: Full list of supported block tags and support for events

### ISSUE THREAD

**Issue by daden** [esdoc/esdoc#157]
Is there someplace I could see a list of the block tags that esdoc supports whether in documentation or in code? Looking for a list of which block tags on http://usejsdoc.org/index.html are supported. 

Also, is there support for @event documentation? 

I have a construct like: 

this.on('select', function() ... )

and am not seeing it in the generated documentation.

btw, thank you for esdoc -- it's great!

**Comment by nodaguti** [comment]
Here is a complete list of supported tags: https://esdoc.org/tags.html

It seems that ESDoc doesn't have native support for **@event**, but you can write **@typedef** to explain the content of an event and refer it using `<identifier>` of **@emits** and **@listens** tags.

**Comment by h13i32maru** [comment]
@daden Please see https://esdoc.org/tags.html
``@event`` is not supported in ESDoc.
