### ISSUE TITLE
Does not detect class extend from module without file extension

### ISSUE THREAD

**Issue by devongovett** [esdoc/esdoc#160]
This does not work:

```javascript
import DataSource from './DataSource';

class ArrayDataSource extends DataSource {}
```

It does not detect that `ArrayDataSource` extends from `DataSource`. The documentation lists it as "src/ArrayDataSource.js~DataSource".

If I include the file extension of `DataSource.js` it works.

```javascript
import DataSource from './DataSource.js';

class ArrayDataSource extends DataSource {}
```

I think both imports should work the same way, as they do in Node, Browserify, etc. Perhaps use `require.resolve` internally to resolve the filename of imports?

**Comment by h13i32maru** [comment]
@devongovett Hi! Thanks for this issue.
I will support non-extension file at next version.

**Comment by h13i32maru** [comment]
I support this issue at ESDoc v0.4.4
