### ISSUE TITLE
Feature: Config option to allow all HTML in documentation

### ISSUE THREAD

**Issue by TitusJonas** [esdoc/esdoc#161]
It would be nice, if it was possible to allow more than the default HTML Tags in the Documentation and especially in the readme.md.

**Comment by h13i32maru** [comment]
@TitusJonas I does not support full HTML. Now, limited HTML is supported.
Please see https://github.com/esdoc/esdoc/blob/master/src/Publisher/Builder/util.js#L63

However I recommend using markdown.

**Comment by jjaderberg** [comment]
There is no Markdown syntax for superscript or subscript. Would you consider adding support for the `<sup>` and `<sub>` tags? We have a document where these are now escaped as `&lt;sup&gt;`, etc.
