### ISSUE TITLE
Suggestion: Breaking down this project into some smaller projects

### ISSUE THREAD

**Issue by nodaguti** [esdoc/esdoc#162]
Currently ESDoc has the following three features:

- **Parser**: Parsing the entire source and creating AST including comments.
- **Linter**: Checking each JSDoc-style comments is appropriate.
- **Publisher**: Building the HTML documentation from the created AST.

For each features, except for ECMAScript parser *espree*, this project uses modules developed from scratch. There are, however, an existing JSDoc parser called *[doctrine](https://github.com/eslint/doctrine)*, and an ECMAScript linter called *ESLint*, which has pre-installed rules for JSDoc ("[require-jsdoc](https://github.com/eslint/eslint/blob/master/lib/rules/require-jsdoc.js)" and "[valid-jsdoc](https://github.com/eslint/eslint/blob/master/lib/rules/valid-jsdoc.js)").

My concern is that this situation could lead to problems about

- **Decentral efforts**: Because there are already existing implementations for parser and linter, developing JSDoc parser and linter from scratch is seemed to be a kind of *reinvention of the wheel* for me. Why don't you concentrate efforts and resources on developing unique and novel features?
- **Discouraging tools collaboration**: Providing parser and linter functionalities on more widely-used platforms encourages engineers to create plugins for collaborating with other applications like editors, build runners, IDEs, etc.

So my suggestions are:

- For parser, let's contribute to *doctrine* to better support for ESDoc-specific tags.
- For linter, let's contribute to ESLint (i.e. creating rules for ESDoc).
- ESDoc project should have responsibilities only about:
   - Generating ESDoc comments from plain source codes (semi-)automatically.
   - Generating a HTML documentation from a given AST.

:bow: I only took a grance at ESDoc's source, so I'm sorry if my suggestions are completely besides the point.

**Comment by nodaguti** [comment]
My apologies for the hasty comment.

Some types of linting, such as warning outdated ESDoc comments, are not able to be realized on ESLint due to the tool's limitation (it doesn't provide path information of files and projects), which doesn't exist in ESDoc.

But I still believe it's better to use doctrine instead of your own parser to reduce future implemantation and maintenance costs, and allow three features to be called independently so that external programs can utilize ESDoc more easily.

As for the latter, though in the current implementation these features are separated into each modules, the cli tool has only `generage` method, which execute *all* tasks: parsing, linting and publising.
If each tasks can work solely, ESDoc's usecases would become more wilder.

**Comment by h13i32maru** [comment]
Thanks for suggestion.
