### ISSUE TITLE
ES7 decorator documentation support

### ISSUE THREAD

**Issue by olegomon** [esdoc/esdoc#163]
Would it be possible to add something like "@decorator" tag to indicate that the underlying function is a ES7 decorator?
At the moment the decorators are displayed as "F" functions, which they are of course but they do have different semantics and it would be really nice to separate them inside the generated documentation from the rest of the classes, functions variables etc.

**Comment by h13i32maru** [comment]
@olegomon I will might support ``@decorator`` in future version. However decoration syntax in TC39 proposal is not released. So, for now, I do not support it.
