### ISSUE TITLE
Support @memberof for sidebar navigation structure

### ISSUE THREAD

**Issue by crucialfelix** [esdoc/esdoc#164]
Currently the sidebar navigation structure is always determined by the folder path of the source file.

For functional style projects (many small functions, no classes) this means that all functions in all files in a folder appear in the same grouping in the navigation.  They are sorted alphabetically, but mixed together with all the other functions in any other file in that folder.

To get them grouped by module we would have to move each file into its own folder.

I think this would be a good solution:

http://usejsdoc.org/tags-memberof.html

```js
/** @namespace */
var Tools = {};

/** @memberof Tools */
var hammer = function() {
};

Tools.hammer = hammer;
```

I think we could also use `@module` in place of `@namespace`

For esdoc it would mean that if the function has a `@memberof` tag then put it in that grouping, otherwise group it by the directory as you are currently doing.

related: #106

**Comment by crucialfelix** [comment]
Additionally I think that if a function has a `@memberof` tag then it should be optional to appear in the sidebar. Just link to the module (just like we link to the class, but don't list all the methods and members of it in the sidebar)

![screen shot 2015-11-12 at 09 49 56](https://cloud.githubusercontent.com/assets/218738/11114177/f6e1d690-8922-11e5-96bf-82e7d2184d7f.png)

Great project, thank you very much for developing it !

**Comment by h13i32maru** [comment]
@crucialfelix I do not support ``@memberof``. Because I have the policy that all documentations side bar are same style and same rule.
