### ISSUE TITLE
Support bracket notation

### ISSUE THREAD

**Issue by kai670** [esdoc/esdoc#165]
If I document a private variable using the bracket notation it is not recognized in the generated documentation:

``` javascript
    constructor() {
        /**
         * Keeps the active tool.
         * @private
         * @type {string}
         */
        this['tool'] = '';
    }
```

IMO this should be recognized the same way as it was assigned using the dot notation.

I detected this trying to declare private variables using Symbols:

``` javascript
let tool = Symbol();
class A() {
    constructor() {
        /**
         * Keeps the active tool.
         * @private
         * @type {string}
         */
        this[tool] = '';
    }
}
```

Of course this last piece of code is also ignored by ESDoc. I'm not sure which should be the expected behaviour for this case but it will be really interesting if private variables declared in that way were included in the generated docs.

**Comment by bmeck** [comment]
I would say dynamic examples like the 2nd example should be ignored. Static analysis of what expressions can evaluate to are complex.

**Comment by h13i32maru** [comment]
@kai670 Hi! Thanks for this issue. I will consider first example. However second example can not be supported.

@bmeck Thanks for reply!

**Comment by h13i32maru** [comment]
Please check the latest ESDoc that supports a first example.
