### ISSUE TITLE
Support for @yields for generator functions

### ISSUE THREAD

**Issue by silkentrance** [esdoc/esdoc#167]
Would it be possible to have a @yields in addition to @return(s) for generator functions?

**Comment by h13i32maru** [comment]
@silkentrance ESDoc already supports generator function.

```javascript
/**
 * this is generator function.
 */
export function* foo(){}
```

<img width="218" alt="2015-11-23 16 46 21" src="https://cloud.githubusercontent.com/assets/985170/11331727/c17e9154-9201-11e5-8995-4582cbfd815b.png">

**Comment by silkentrance** [comment]
@h13i32maru yes, it does support but how do I document the value type it yields?

I tried using @type and it does seem to work, but so does @return.

In both cases, the generated documentation will look like this

```
public abstract * tokenize(file: string, lines: Generator | Array<string>): AbstractToken
```

Now, when called, the generator function will of course return a generator prototype, e.g. Generator<string>.

What my original intend was is that the user just documents the type that the generator produces and that esdoc fills in the rest, e.g.

```
/**
 * The generator...
 * @type {string}
 */
function *generator() {}
```

will produce documentation such as

```
public * generator(): Generator<string>
```

**Comment by zxqfox** [comment]
We could think about `@consumes` and `@produces` to describe what generator awaits and what it produces to yields.

As well as for streams.

**Comment by buschtoens** [comment]
Is this still a WontFix?
