### ISSUE TITLE
Support for Node.js style module.exports

### ISSUE THREAD

**Issue by bentruyman** [esdoc/esdoc#168]
As of Node.js 4.2.0 and 5.0.0, much of the desired ES6 functionality many developers have without the need for using tools such as `babel`. However, Node.js does not yet support ES6 module syntax (any may never support it). But we, and I'm sure many others, would love to use `esdoc` with native ES6 on Node 4.2.0/5.0.0.

**Comment by niclashoyer** [comment]
:+1:

**Comment by h13i32maru** [comment]
I do not support ``module.exports``, because ESDoc support ES6. However ESDoc plugin feature might help you. https://esdoc.org/api.html#plugin-feature

**Comment by Orgun109uk** [comment]
To get this working for one of my projects, i have a very quick and dirty plugin which is included in via the plugins config in my esdoc file:

```js
exports.onHandleCode = function (ev) {
  ev.data.code = ev.data.code
    .replace(/module\.exports = /g, 'export default ')
    .replace(/module\.exports\./g, 'export ')
    .replace(/exports = /g, 'export default ')
    .replace(/exports\./g, 'export ');
};
```

**Comment by DannyDelott** [comment]
:+1:

**Comment by thetutlage** [comment]
@Orgun109uk Same does not work with

```
exports = module.exports = {}
```

As it fails even before reaching the `onHandleCode`
