### ISSUE TITLE
Property documentation not showing up

### ISSUE THREAD

**Issue by andy-hanson** [esdoc/esdoc#169]
Here's the code I'm documenting:

	export class Foo {
		constructor(bar) {
			/**
			@type {number}
			Number of bars.
			*/
			this.bar = bar
		}
	}

In the generated documentation, `bar` shows up in the `Public Members` section and is typed as a number.
However, the text documentation ("Number of bars.") doesn't show up anywhere.

**Comment by h13i32maru** [comment]
The document comment is invalid. Correctly here.

```
export class Foo {
  constructor(bar) {
    /**
     * Number of bars.
     * @type {number}
     */
    this.bar = bar
  }
}
```
