### ISSUE TITLE
Not giving param names in `function()` type expressions crashes esdoc

### ISSUE THREAD

**Issue by fixpunkt** [esdoc/esdoc#170]
The following does not seem to be allowed and will result in a crash without a proper error message:

    export default class Observable {
      /**
       * Subscribe to get notified whenever the observable is modified
       * @param {function(Observable)} listener the listener to notify
       */
      addListener(listener) {
      }
    }

If I change the type expression to `{function(target: Observable)}`, everything works fine. There are a number of problems with this behavior:

1. This is somewhat unexpected, since e.g. Google Closure type expressions allow defining anonymous function types without having to specify argument names (cf. https://developers.google.com/closure/compiler/docs/js-for-compiler?hl=en#types).
2. Documenting argument names for a function that the caller passes in does not even make sense.
3. This will crash esdoc without a proper error message being emitted. I had to run esdoc through the debugger to find the cause of the problem.

Cheers,

Jannik

**Comment by h13i32maru** [comment]
@fixpunkt Hi! Thanks for this issue. I will improve error message in future version.
