### ISSUE TITLE
Support for non-standard manual chapters?

### ISSUE THREAD

**Issue by fixpunkt** [esdoc/esdoc#171]
I am using esdoc for an internal application. I want to add special documentation chapters on architecture and other topics that do not fit within the preconfigured manual structure as [outlined in esdoc's manual](https://esdoc.org/feature.html#integration-manual). I'd like to be able to do something like this:

    {
      destination: config.buildDirectory + '/docs',
      manual: {
        "overview": ["./README.md"],
        "architecture": ["./docs/architecture.md"],
        "template-language": ["./docs/template-language.md"],
        "development-tools": ["./docs/development-tools.md"]
      }
    }

Would you consider this feature request for inclusion?

Cheers,

Jannik

**Comment by h13i32maru** [comment]
@fixpunkt Thanks for using manual feature. I have no plan to support user defined chapters. Because I think that strict chapters bring benefit for writer and reader. However I will add some chapters to manual. For now, I consider ``architecture(or design)`` and ``advanced(or detail)``.

Thanks.

**Comment by fixpunkt** [comment]
Nice, that definitively is an improvement.

While I agree that it makes sense to enforce a standard chapter structure for JavaScript libraries, this is less helpful for documenting internal apps where you may want to document the assumptions about the domain. In this case you really need free-form chapters.

 Just my .02 EUR, I'm happy with `architecture` and `advanced` chapters.

**Comment by bmeck** [comment]
I'm using it for a glossary of terms which is outside the norm, but still a very useful chapter: http://bmeck.github.io/snapshot-utils/doc/manual/terms.html . Maybe we could make it throw errors if it encounters chapters that will not be published, as that confused me for a while before I patched esdoc.

**Comment by h13i32maru** [comment]
I will write my opinion of this feature, please wait.

**Comment by bmeck** [comment]
@h13i32maru any news on this?

**Comment by h13i32maru** [comment]
I do not support non-standard manual chapters.

----

I want to make the structure of the manual. This is the same idea as the MVC of the Web server side programming.

I think that the manual should have the following structure.
- Introduction (overview, installation)
- Operation (usage, tutorial, configuration)
- Reference (API reference)
- Case (example)
- History (changelog)

And that each manual is written along the same structure, I believe that the writers and readers have low cost for the manual. Disorder manual is a high cost.

However, you may want to lack only this structure. Therefore I am considering the additional structure. For example, architecture(or design) and advanced(or detail).

**Comment by chrisabrams** [comment]
@h13i32maru would you please consider adding a "contributing" or "developing" section?

**Comment by h13i32maru** [comment]
I improved the manual feature in ESDoc v0.5.0.
It realizes both a strict and a flexible.
Please check an example.
https://doc.esdoc.org/github.com/esdoc/esdoc/manual/index.html

Details:
Labels in manual sidebar are taken from `h1` tag in manual markdown files.
In other words, you can freely write labels of manual.

If you want to write a `Contributing` manual, you can do the below.

`./manual/contributing.md`
```markdown
# Contributing
write something...
```

`esdoc.json`
```json
{
  "source": "./src",
  "destination": "./doc",
  "manual": {
    "faq": ["./manual/contributing.md"]
  }
}
```
<img width="267" alt="2016-12-28 9 32 53" src="https://cloud.githubusercontent.com/assets/985170/21511186/a5506104-cce0-11e6-856a-4e3b792906e3.png">
