### ISSUE TITLE
Way to import type definitions from another path

### ISSUE THREAD

**Issue by vespakoen** [esdoc/esdoc#172]
Hey!

I have a project that is split up in a lot of different packages, I have one "spec" package that contains all kinds of stuff that get's shared among the packages, I have some typedefs in there as well.

Now I would like to include these typedefs in the docs for other packages, but I don't know how to go about it, can you help me with this? (the spec package is present in the node_modules folder of the other packages)

Thanks!

**Comment by h13i32maru** [comment]
@vespakoen Hi! ``@external`` tag might help you. https://esdoc.org/tags.html#-external
