### ISSUE TITLE
Parameter defaults with spaces

### ISSUE THREAD

**Issue by wherget** [esdoc/esdoc#174]
I have a scenario where I create a new instance of an object as a default value, e.g.:

```
@param {SomeObject} [param=new DefaultSomeObject()] - A complex default parameter
```

Right now, this does not parse correctly (it cuts off at the first space, i.e. after the `new`).

**Comment by h13i32maru** [comment]
@l337r007 Hi! Thanks for this issue. I consider it.

**Comment by l337r007** [comment]
@h13i32maru If you want, I can whip up a pull request to implement this. Should just be a minor change of the regular expressions in `ParamParser.js`, right?

**Comment by h13i32maru** [comment]
Thanks!
Now, I have the idea that treat default parameter as javascript expression. However this idea is difficult. So, please wait more time...

**Comment by evolutionxbox** [comment]
One quick fix for this is to use a non breaking space HTML entity.
```
@param {SomeObject} [param=new&nbsp;DefaultSomeObject()] - A complex default parameter
```

This works in ESDoc v0.4.6

**Comment by h13i32maru** [comment]
I fixed this. And I will release in next version. Please check it via [developing version](https://esdoc.org/manual/usage/usage.html#installation).

https://github.com/esdoc/esdoc/commit/728fba3b123b9ee13b473379e32e709ed59dada6
