### ISSUE TITLE
Suggestion: include module filename into namespace in sidebar

### ISSUE THREAD

**Issue by raveclassic** [esdoc/esdoc#180]
Hi!

Currently sidebar in the doc is namespaced basing only on directories. Could it be possible to also use module filename?

Example: I have various modules (files) in `util` directory each exporting some functions - all these function are in the scope of `util` folder - that's very inconvenient...

![image](https://cloud.githubusercontent.com/assets/1743568/11392014/ec54918c-9367-11e5-993e-b2310e23f2c4.png)

Moreover, what if I have functions with the same name but in different files?

TIA

**Comment by JulienBonnin-ABTasty** [comment]
I'm having the exact same issue, for now I use 1 module = 1 folder rule :( Because my JS is compiled using browserify and Babel to have a single file. But I'd like to have on option to build the treeview by files :)

**Comment by chpio** [comment]
:+1:

**Comment by h13i32maru** [comment]
Now, I do not have a plan to support this suggestion. You can develop the [ESDoc Plugin](https://esdoc.org/api.html) for the feature.

**Comment by screendriver** [comment]
> Because 1 file - 1 class style does not require filename

But most times we have `1 file - many functions` and not only classes.

**Comment by h13i32maru** [comment]
> But most times we have 1 file - many functions and not only classes.

So, this is developer's liking. I like ``1 file - 1 class``.

> You can develop the ESDoc Plugin for the feature.

If you like other style, you can write the plugin.

**Comment by chpio** [comment]
> If you like other style, you can write the plugin.
or just switch to documentation.js (they are now supporting babelv6)

**Comment by raveclassic** [comment]
@chpio Thanks for the tip!
