### ISSUE TITLE
Feature: nested packages

### ISSUE THREAD

**Issue by jcalfee** [esdoc/esdoc#182]
It would be really neat if esdoc could support nested rpm packages.  This would allow an entire collection of related libraries and programs to be searchable from the generated docs.  My initial attempt at this was to create the `esdoc.json` in the root with the following config:
```json
{
  "source": ".",
  "includes": ["\\.(js|es6)$"],
  "excludes": ["node_modules"],
  "destination": "./out/esdoc",
  "index": "./README.md",
  "package": "./package.json",
  "title": "Graphene Docs"
}
```
It would be nice if esdoc could accept multiple `package.json` files (an array perhaps) and correct its import statements..

**Comment by silkentrance** [comment]
What about ``@external``? It allows you to reference externally defined entities by specifying an url. For my part this works just fine. And, btw. did you mean npm instead of rpm?

**Comment by h13i32maru** [comment]
I do not have the plan to support the suggestion. Because 1 package has 1 documentation.

**Comment by h13i32maru** [comment]
@silkentrance Thanks reply :smile:
