### ISSUE TITLE
Feature: group function by filename

### ISSUE THREAD

**Issue by jcalfee** [esdoc/esdoc#183]
We use Redux which involves exporting many functions directly from a file.  The functions are not grouped in a class.  This makes the esdoc hard to read, the functions end up all in one list.

I believe a File grouping is a valid concept for your application, this also provides an opportunity to generated more sample imports.

>`file.js`
```js
export function f1() { ... }
export function f2() { ... }
```

**Comment by screendriver** [comment]
+1

Same here: I write a lot of modules that export single functions and not ES2015 classes.

**Comment by chauthai** [comment]
+1

**Comment by DanielSWolf** [comment]
:+1:

**Comment by peterjuras** [comment]
+1

**Comment by chpio** [comment]
yes! please!

**Comment by raveclassic** [comment]
Duplicates #180

**Comment by h13i32maru** [comment]
Please see https://github.com/esdoc/esdoc/issues/180#issuecomment-182727929
