### ISSUE TITLE
Feature request: Support union type with spread operator and generics.

### ISSUE THREAD

**Issue by rhys-vdw** [esdoc/esdoc#184]
``` js
/** @param {...(Foo|Bar)} foosOrBars */
function fn(...foosOrBars) {}

/** @param {Array<Foo|Bar>} fooOrBars */
function fn(fooOrBars) {}
```

**Comment by rhys-vdw** [comment]
These fail with the same error I've reported in #185. I was assuming that this was unsupported - but it seems now that this is a bug.

**Comment by h13i32maru** [comment]
I consider this feature.

**Comment by h13i32maru** [comment]
I fixed both. And I will release in next version. Please check it via [developing version](https://esdoc.org/manual/usage/usage.html#installation).
