### ISSUE TITLE
Please support ClassExpression

### ISSUE THREAD

**Issue by SunboX** [esdoc/esdoc#187]
By now ***esdoc*** only supports the [ECMAScript-6 ***class declaration***](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-class-definitions) syntax.

I you want to add classes to namespaces, *and don't want to use the ES6 module system*, you have to use the ***class expression*** definition instead:

```js
'use strict'

/**
 * @namespace
 */
var ns = {}

/**
 * My sample class.
 * 
 * @class
 * @name MyClass 
 * @memberof ns
 */
ns.MyClass = class {
  constructor() {
    console.log('in constructor')
  }
}

new ns.MyClass()
```

But ***esdoc*** seems to ignore this kind of class definition, so called ***class expression*** and only parses ***class declaration***.

Please also add support for the ***class expression*** definition. :smile:

**Comment by SunboX** [comment]
Btw. ***espree*** seems to support ***class expression***: https://github.com/eslint/espree/blob/master/tests/fixtures/ecma-features/classes/class-expression.result.js

**Comment by silkentrance** [comment]
@SunboX why not just

```
class Foo {}

ns.MyClass = Foo;
```

instead?

**Comment by h13i32maru** [comment]
@SunboX ESDoc already supports ``class expression``.

```javascript
const Foo = class {
  constructor() {}
}
export default Foo;
```

However ESDoc does not support global name space style(aka ES5 style).
```javascript
// this style is not supported.
const ns = {};
ns.Foo = class {
  constructor() {}
}
```

ESDoc only supports ES6 modules style.
