### ISSUE TITLE
ES7 property initializer alternative

### ISSUE THREAD

**Issue by artisologic** [esdoc/esdoc#188]
Hi,

First, thanks so much for this tool. I looked for lots of tools before deciding on using yours as the result looks great and it has so many features built-in.

Now, I know that you don't support ES7 directly, and I am using the esdoc-es7-plugin which I understand just ignores ES7 so that esdoc doesn't fail. So I am aware that ES7 features shouldn't work directly.

However I am after a way to still document members of a class in an alternative way.

Here's a simple use case:

```js
/**
 * A Class to test documentation
 * @class
 */
export default class TestDoc {

	/**
	 * A dummy member
	 * @private
	 * @type {Number}
	 */
	_dummyMember = 3;

	constructor() {}

	/**
	 * Get dummy.
	 * @return {Number} The dummy.
	 */
	getDummy() {
		return this._dummyMember;
	}

}
```

This is ultimately what I'd like to be able to do. Now I understand that this doesn't work and I'd be happy to use a workaround, if only I could find one!

I have tried everything like, adding `@name _dummyMember` or `@name TestDoc#_dummyMember` or even `@member {Number} _dummyMember` but none of them make the property appear in the documentation.

The only way I have found for it to work is to duplicate the member initialisation in the constructor like so but obviously it defeats the purpose of using ES7 property initializer:

```js
/**
 * A Class to test documentation
 * @class
 */
export default class TestDoc {

	_dummyMember = 3;

	constructor() {
		/**
		 * A dummy member
		 * @private
		 * @type {Number}
		 */
		this._dummyMember = 3;
	}

	/**
	 * Get dummy.
	 * @return {Number} The dummy.
	 */
	getDummy() {
		return this._dummyMember;
	}

}
```

Am I missing something? What would be the way to still be able to use ES7 property initializers AND document them at the same time?

Thanks!

**Comment by silkentrance** [comment]
How about

```
class TestDoc
{
    get dummyMember()
    {
         return 3;
    }
}
```

and if you need a setter, just add it.

**Comment by artisologic** [comment]
A getter is not the same as a property though.
In some cases for example, I do document an underlying property as well as a getter/setter for it.

**Comment by iosulfur** [comment]
**I have the same request.**

My latest attempt was to add a `@property` to the class doc comment:

```javascript
/**
 * A Class to test documentation
 * @class
 * @property {string} test1 - Test property 1
 * @property {string} test2 - Test property 2
 */
export default class TestDoc {
  // ...
}
```

But this also does not add a property to the generated documentation.

**JSDoc allows the property tag for classes.**
[JSDoc: `@property`](http://usejsdoc.org/tags-property.html)
> The @property tag is a way to easily document a list of static properties of a class, namespace or other object.

**ESdoc does not seem to expect this.**
[ESDoc: For Class](https://esdoc.org/tags.html#for-class)
> `@extends` [...] `@implements` [...] `@interface` [...]

_I second artisologic's question:_

> What would be the way to still be able to use ES7 property initializers AND document them at the same time? — artisologic

**Comment by h13i32maru** [comment]
This is very unstable workaround with internal tags. This might become unusable and possibly.

```javascript
export default class Foo {
}

/**
 * this is myProp.
 * @_static false
 * @_memberof src/foo.js~Foo
 * @_member {number} myProp
 */
```
