### ISSUE TITLE
Exporting a default function leads zu wrong documentation

### ISSUE THREAD

**Issue by screendriver** [esdoc/esdoc#189]
If you write

```js
export default function foo() {
}
```

then ESDoc produces following documentation

```
import {foo} from 'my-package/index.js'
```

This is wrong because the function `foo` can not be accessed with destruction because it is exported as `default`.

**Comment by h13i32maru** [comment]
@screendriver This issue was not reproduced in my environment.

```javascript
export default function foo() {}
```

<img width="319" alt="2016-02-14 16 40 42" src="https://cloud.githubusercontent.com/assets/985170/13032539/c7c62710-d339-11e5-8d16-5e0a451d71ad.png">

```
$ esdoc -v
0.4.4
```
