### ISSUE TITLE
Option not to sort the methods?

### ISSUE THREAD

**Issue by udp** [esdoc/esdoc#191]
The order of the methods in my class is semantically important, so I'd rather if they weren't sorted A-Z.  Maybe this could be an option.

**Comment by artisologic** [comment]
I thought of this too as I usually put methods in a specific order that makes sense as well.

**Comment by silkentrance** [comment]
Ever considered using https://esdoc.org/tags.html#-see to put those methods into context?

**Comment by h13i32maru** [comment]
I do not have plan to support optionally sorting. If you want to use optionally sorting, please use [plugin or publisher](https://esdoc.org/api.html).

**Comment by vitalets** [comment]
Did anybody solved this issue by some plugin?
