### ISSUE TITLE
Visibility flag in doc comments for generated documentation

### ISSUE THREAD

**Issue by jstejada** [esdoc/esdoc#193]
I would like to indicate what comments to be included in the generated documentation, and which ones not to.

For example, biscotto provides these flags: https://github.com/gjtorikian/biscotto#visibility, which would be really nice to have.

**Comment by silkentrance** [comment]
How about ``@public`` and ``@private`` and configure your esdoc.json so that it will only include either of these two?

**Comment by h13i32maru** [comment]
@jstejada Please use ``@public, @protected, @private`` and ``config.access``.

- https://esdoc.org/tags.html#-access
- https://esdoc.org/config.html
