### ISSUE TITLE
★ To ESDoc Users ★

### ISSUE THREAD

**Issue by h13i32maru** [esdoc/esdoc#194]
I think glad that you report issues. So I want to response the issues. But, now, I am very busy :sweat_drops:   Please wait a little.

Thanks for understanding.

**Comment by bmeck** [comment]
Let me know if there are any tasks that I can look at to help.

**Comment by typhonrt** [comment]
Likewise if I can help with anything let us know. Perhaps mark issues as `contributions welcome`. It seems there is good uptake in general w/ my [esdoc-plugin-jspm]() plugin. There are aspects of ESDoc that I'd like to continue to improve. I can open another issue and might soon. But I'd really like to make the left hand panel of generated docs allow a collapsible / expandable option for JSPM linked modules and expose the source of the "parent" repo at the top. An example of generated docs for a canonical TODOs app is here: 
http://js.demos.typhonrt.org/backbone-parse-es6-todos-improved/docs/ 

It would be great to position all of the "site" entries in the TODOs or any parent repo at the top of the left hand bar and all of the JSPM dependency related docs at the bottom and initially in a "collapsed" state. Here is an example of what I'd like it to look like:
http://i.imgur.com/uNnDx0b.png

I've postponed posting such an "issue" as I know you are busy, but I'd like to add this enhancement if possible given diving deeper into contributing to ESDoc and properly working out any hooks necessary to making this possible.

**Comment by mtscout6** [comment]
You've got this repo setup in a GitHub Organization. Have you considered making a call for additional maintainers so the brunt of this is not all on you?

**Comment by h13i32maru** [comment]
Thanks everyone! I resumed support ESDoc.
