### ISSUE TITLE
Function not as the first argument

### ISSUE THREAD

**Issue by Orgun109uk** [esdoc/esdoc#201]
I am using the *@param* attribute to define callbacks, all works fine in the generated documentation (links to the definition of Error, String, etc) if the callback is the first attribute, however anything other than the first the links are not generated.

*Working example*
@param {function (err: Error, success: boolean)} callback - A description.
@param {string} id - A description.

*Not working example*
@param {string} id - A description.
@param {function (err: Error, success: boolean)} callback - A description.

**Comment by h13i32maru** [comment]
> @param {function (err: Error, success: boolean)} callback - A description.

ESDoc requires non-space between ``function`` and ``(``.

- valid: ``function(foo: string)``
- invalid: ``function (foo: string)``

----
However, this behavior confuse users. I improve it.
