### ISSUE TITLE
esdoc includes return values inferred from the AST in documentation even though the doc comment includes a @return(s) tag

### ISSUE THREAD

**Issue by silkentrance** [esdoc/esdoc#205]
Say, having

```
class foo
{
     /**
      * @returns {boolean} - the bar
      */
     get bar()
     {
          return true;
     }

     /**
      * @returns {Object} - the car
      */
     get car()
     {
         return {};
     }
}
```

will generate documentation that includes the information inferred from the AST, e.g.

```
get bar : boolean : boolean
get car : Object : *
```

Can this be changed so that esdoc will only include the inferred type when no @return(s) tag is present?

For a "live" example, please have a look at 
http://esbases.es.coldrye.eu/projects/esbases/doc/dev/class/src/error.es~EsError.html

here: get cause : Error : *

**Comment by h13i32maru** [comment]
ESDoc requires ``@type`` for ``getter``, not ``@returns``.

```javascript
export default class Foo {
  /**
   * this is foo.
   * @type {boolean}
   */
  get foo(){
    return true;
  }
}
```

https://esdoc.org/tags.html#for-member-and-variable

**Comment by silkentrance** [comment]
@h13i32maru Thanks for the hint. *Sigh* will have to fix a lot of API docs :grinning:
