### ISSUE TITLE
SpreadProperty type has no key

### ISSUE THREAD

**Issue by NullDivision** [esdoc/esdoc#206]
While investigating the cause of `TypeError: Cannot read property 'name' of undefined at Function.guessParams (/home/NullDivision/Projects/MyProject/node_modules/esdoc/out/src/Parser/ParamParser.js:344:54)` i found that when the type is `SpreadProperty` there is no key property.

**Comment by h13i32maru** [comment]
Please post your the soure code that raise the error.
