### ISSUE TITLE
Cannot Suppress Console Output

### ISSUE THREAD

**Issue by steve-gray** [esdoc/esdoc#208]
When running ESDoc inside a gulp workflow on a large project, sometimes we want to suppress the output from ESDoc unless there's been an error. At the moment it *seems* like it's writing out directly to the console.

Is there some way to quiet/silence the console output that I'm missing?

**Comment by h13i32maru** [comment]
I plan to refine console output. Please see https://github.com/esdoc/esdoc/issues/104
