### ISSUE TITLE
src at multiple location

### ISSUE THREAD

**Issue by navinSing** [esdoc/esdoc#210]
hi, can we specify the src to be array at muliple location /

{
src :['./a/src','./b/src'],
dest: './d'
}

**Comment by raveclassic** [comment]
@navinSing This is a duplicate of #72

**Comment by h13i32maru** [comment]
Please see https://github.com/esdoc/esdoc/issues/72

**Comment by typhonrt** [comment]
I have created a comprehensive solution for multiple source path support with backward compatibility and an overview is available in #310.
