### ISSUE TITLE
Question: Is there something similar to eslint plugin? 

### ISSUE THREAD

**Issue by AdrieanKhisbe** [esdoc/esdoc#211]
Thinking about seting up in a set of repository (#microservicesOblige),
was wondering if it was possible to __keep configuration DRY__, 
with a master config that is refered by disciples config in each repo.

Something similar to eslint plugins:
http://eslint.org/docs/developer-guide/working-with-plugins.html

Thanks in advance for the dedicated time to read and answer :smiley:

**Comment by silkentrance** [comment]
@AdrieanKhisbe and what would be the reference to or implication to this project? Please be more specific.

**Comment by h13i32maru** [comment]
@AdrieanKhisbe Hi. I do not have the plan to support the feature of configuration.
