### ISSUE TITLE
question: is there a way to get a view of all documentation in a folder?

### ISSUE THREAD

**Issue by tony-kerz** [esdoc/esdoc#214]
first of all, just stumbled across your project today after having issues with es6/7 in jsdoc,
and i was able to quickly get my es6/7 project documented via esdoc, so nice work!

the nav bar on the left organizes by folder, but when i click into an F/function icon, it shows the item in a view of _all_ functions grouped together alphabetically.

is there any way that i can get a view of all functions in a folder (all functions in a folder are typically logically grouped together so it seems a more understandable experience for the reader).

the folder name in the left nav is currently not clickable, but that could be a good label to make clickable into a folder-centric view...?

regards,
tony.

**Comment by h13i32maru** [comment]
@tony-kerz Thanks for reporting this question. Now, ESDoc does not support a view that shows all functions in a folder. I consider it.

**Comment by h13i32maru** [comment]
I consider this in [here](https://github.com/esdoc/esdoc/issues/370). Please check it
