### ISSUE TITLE
@see {@link http://example.com|An Example} syntax

### ISSUE THREAD

**Issue by rapodaca** [esdoc/esdoc#216]
JSDoc supports user-defined links in the <code>@see</code> tag:

``` javascript
/**
 * @see {@link http://example.com|An Example}
 */
const example = function () {

};
```

http://usejsdoc.org/tags-see.html

This is useful for presenting a human-readable description of the link, rather than a URL.

When I try this syntax, it shows up literally and isn't parsed. Is anchor text currently supported in the <code>@see</code> tag in ESDoc?

**Comment by h13i32maru** [comment]
This issue is a duplicate of https://github.com/esdoc/esdoc/issues/212

**Comment by h13i32maru** [comment]
Please check https://github.com/esdoc/esdoc/issues/367
