### ISSUE TITLE
Cannot link to method starting with dollar sign

### ISSUE THREAD

**Issue by pgom** [esdoc/esdoc#218]
It's not possible to link to a method that starts with a dollar ( $ ) sign like the following example: `{@link ClientProvider#$get}`

Dollar sign methods are commonly used in Angular applications.

**Comment by h13i32maru** [comment]
I fixed this issue at master.

**Comment by h13i32maru** [comment]
I released v0.4.5 that fixed this issue.

**Comment by pgom** [comment]
@h13i32maru great!
