### ISSUE TITLE
Support ReactJS component properties

### ISSUE THREAD

**Issue by mookraiser** [esdoc/esdoc#220]
It would be fantastic to provide documentation for component properties. here an example that declare a property ```onClose``` of type ```function``` with default value ```null```:
```
MyClass.propTypes = {
  onClose: React.PropTypes.func
};
MyClass.defaultProps = {
  onClose: null
};
```

**Comment by h13i32maru** [comment]
I do not have a plan to support React component.

**Comment by mookraiser** [comment]
too bad :-)
May be you could add new tags to define properties. It would be enough. The point is to handle any web component framework, we need component properties. So basically a class could be divided in
- members variables (they are not properties)
- properties
- methods
If parsing a react code is too much, may be offering new tags is enough ?

**Comment by wtx2338** [comment]
Is it possible to create some plugin to support propTypes? And I also want to know how to debug plugin code (with node-inspector for example), because I have no ideal what kind of data is available in the ev.data.

**Comment by pedroteixeira** [comment]
Hello, any one knows if there exists a plugin that could infer esdoc comments from PropTypes?

**Comment by loopmode** [comment]
I don't think anything has happened on that front. However, here's a workaround approach.
You can use `typedef` tags to define the entire propTypes object as a type with properties.

Pros:
- You can document each prop type of your component

Cons:
- The data type is not inferred from the propType, you still have to manually provide it
- The documentation of the individual props is on a separate docs page (not on the same one as the component)

Here is an example:

```javascript
/**
 * The props supported by the `QueryRunner` component
 *
 * @typedef {Object} QueryRunner~propTypes
 * @property {boolean} autorun - Whether to automatically execute the query when the component is mounted
 * @property {string} conceptID - The ID of the concept to which the query belongs
 * @property {string} nodeID - The ID of the graph node to which the query belongs
 * @property {string} queryID - The ID of the query
 * @property {function} render - A function that will be invoked with `{isLoading, results, error, runQuery}` properties
 */

/**
 * Runs an SQL query remotely and provides the results to a `render` function.
 */
export default class QueryRunner extends PureComponent {
    /**
     * @type {QueryRunner~propTypes}
     */
    static propTypes = {
        autorun: PropTypes.bool,
        conceptID: PropTypes.string,
        nodeID: PropTypes.string,
        queryID: PropTypes.string,
        render: PropTypes.func
    };
    ...
```

![image](https://user-images.githubusercontent.com/623225/50421330-43ccca80-083e-11e9-8fc8-50c47777c7c2.png)

![image](https://user-images.githubusercontent.com/623225/50421335-4d563280-083e-11e9-9b77-2f99b558b2d2.png)

So, it's not optimal but it's a way to document component props.
