### ISSUE TITLE
@alias tag?

### ISSUE THREAD

**Issue by hydrabolt** [esdoc/esdoc#221]
Are there any plans to support the @alias tag? I've got a class that has a few aliases for the same function, and I'm not sure there's a clean way to go about it without @alias. Thanks

**Comment by h13i32maru** [comment]
Please post a detail and example code.

**Comment by hydrabolt** [comment]
For example, this is how I would want it to work:
```js
class Client{
    constructor(){

    }

	/**
	 * Does something
	 * @alias bar
	 * @alias second_alias
	 */
    foo(){

    }

    // bar and second_alias should not appear as their own methods in documentation,
    // but rather as an alias of foo
    bar(){ this.foo(); }
    second_alias(){ this.foo(); }
}
```

**Comment by h13i32maru** [comment]
I understood the your request. But I do not have the plan to support it. Because it is the complexity. I want to keep ESDoc simple.

**Comment by pronebird** [comment]
I have better example, i.e:

```js
/**
 * Event type enum
 * @type {enum}
 * @property {string} enumValue1
 * @property {string} enumValue2
 * @property {string} enumValue3
*/
const EventType = MyEnum( ... )

export default class Backend extends EventEmitter {
   /**
    * @alias EventType 
    */
    static EventType = EventType;
}
```

Now I have no idea how to remap EventType there. Generated documentation is missing type info.

`@alias` could perfectly solve that.
