### ISSUE TITLE
Source code highlighted, but Reference is empty

### ISSUE THREAD

**Issue by peter-kehl** [esdoc/esdoc#222]
Hi Ryo,

Thank you for ESDoc. It parses and higlights my source code well. However, it generates an empty Reference. Here's how to reproduce:

sudo npm --global install esdoc
git clone https://github.com/SeLite/SeLite.git
cd SeLite
esdoc.json:
{
  "source": ".",
  "destination": "../selite.esdoc"
}

esdoc -c esdoc.json
...
Coverage: 0% (0/0)

**Comment by h13i32maru** [comment]
@peter-kehl Hi!
ESDoc supports ES6 modules. So the following code style is supported.

```javascript
export default class MyClass {
  constructor() {
  }
  foo(){
  }
}
```

I think the SeLite looks like non ES6 style.

**Comment by peter-kehl** [comment]
My problem's background: I used to use JSDoc, but it's not ES6-compatible. However, ESDoc doesn't generate any documentation for my project, and it doesn't report any error either.

The core of the problem: There is very little documentation on tags in ESDoc. https://github.com/esdoc/esdoc/blob/master/manual/tutorial.md links to 'Tags' (https://github.com/esdoc/esdoc/blob/master/manual/tags.html), which doesn't exist. I see some examples (e.g. https://github.com/esdoc/esdoc/blob/master/doc/tutorial-example/my-project4/src/MyClass.js). However, navigating through files to learn ESDoc is a highly inefficient way of learning. Would you provide a tags reference, please.

Saying that something 'looks non ES6 style' is unproductive. My project works with current Firefox. It mostly uses old Javascript, with a few ES6 features. How are users supposed to know what 'ES6 style' you mean?

Some of my functions - e.g. SeLiteMisc.compareAllFieldsOneWay() in https://github.com/SeLite/SeLite/blob/master/misc/src/chrome/content/SeLiteMisc.js - have tags that seem like ESDoc-compatible:
/** Compare whether all fields from firstContainer exist in secondContainer and are same. Throw an error if not.
 *  See SeLiteMisc.compareAllFields().
 *  @param {(Array|object)} firstContainer
 *  @param {(Array|object)} secondContainer
 *  @param {boolean} [asArray=false]
 *  @param {boolean} [strict=false]
 *  @param {string} [methodName=undefined]
 *  @return void
 *  @throws If the containers are different (see description); otherwise the containers are equal.
 * */
SeLiteMisc.compareAllFieldsOneWay= function compareAllFieldsOneWay( firstContainer, secondContainer, asArray, strict, methodName ) {...};

However, Esdoc prints
Coverage: 0% (0/0)
and it puts no references to ../selite.esdoc/identifiers.html

Would you make ESDoc reports errors/incorrect tag syntax, please.

**Comment by Ltrlg** [comment]
I think https://esdoc.org/tags.html is the reference you want.

**Comment by peter-kehl** [comment]
Thank you for clarification. However, note https://github.com/esdoc/esdoc/blob/master/doc/tutorial-example/my-project4/src/MyClass.js uses `@returns`, yet https://esdoc.org/tags.html defines `@return` instead. Please would you fix one of them.

Some of my documentation seems to conform to ESDoc. However, ESDoc reports Coverage: 0% (0/0). It generates identifiers.html with no references. An example is SeLiteMisc.addStackToMessage() defined at https://github.com/SeLite/SeLite/blob/master/misc/src/chrome/content/SeLiteMisc.js#L66.

Would you make ESDoc report why it doesn't pick up references from such code.

**Comment by h13i32maru** [comment]
> Would you make ESDoc report why it doesn't pick up references from such code.

This is very hard work. I do not support it. Sorry.

**Comment by peter-kehl** [comment]
What did you mean that you don't support? The syntax, or error reporting?

How are users supposed to know what syntax is not supported, if there is no error reporting?

**Comment by ozjd** [comment]
@peter-kehl This is also driving me insane. I think I'll keep looking for about another 10 minutes :(

**Comment by typhonrt** [comment]
Hang in there folks.. The major problem is that @h13i32maru hasn't had time to maintain / improve ESDoc, but also has not accepted outside collaborators who can move ESDoc forward. There are a few devs like myself out there that would like to help / collaborate and improve ESDoc, but Ryo needs to accept forward progress w/ collaborators. I'd like to address this issue. No ETA until Ryo accepts outside collaborators though.

**Comment by peter-kehl** [comment]
Instead, I'm using https://github.com/jsdoc3/jsdoc. Despite its name it handles new ES6 features well.

**Comment by typhonrt** [comment]
@peter-kehl  Yes ESDoc is for ES6 / ES module formatted code [which is not](https://github.com/SeLite/SeLite/blob/master/misc/src/chrome/content/SeLiteMisc.js) what your project is currently. I didn't give a cursory look at the code you posted as I thought the example you posted in an issues above was for an example like the following:

```
export default class Foo
{
}

Foo.bar = (bar) => { this.bar = bar; }
Foo.biz = function(biz) { this.biz = biz; }
```

IE setting additional methods of a _class_ in a given ES module which is currently not supported by ESDoc, but hopefully will be in the future.

**Comment by peter-kehl** [comment]
Michael @typhonrt,

If ESDoc is for ES6 / ES modules only, then it should clearly document it somewhere. Its README.md should make it obvious.

Otherwise people using ES6 features in code other than ES modules will report problems.
