### ISSUE TITLE
Support trailing comma for import syntax in ES6

### ISSUE THREAD

**Issue by jipodine** [esdoc/esdoc#223]
Hi,

The following statements are considered invalid by ESDoc

``` javascript
import { fun1, fun2, } from './lib12';
import { 
    fun3, 
    fun4, 
} from './lib34';
```

> warning: could not parse the following code. if you want to use ES7, see esdoc es7-plugin(https://github.com/esdoc/esdoc-es7-plugin)

While in ES2015 (ES6) trailing commas are valid http://www.ecma-international.org/ecma-262/6.0/#sec-imports

Regards,

Jipodine

**Comment by bmeck** [comment]
This is actually a bug in [espree](https://github.com/eslint/espree)

**Comment by h13i32maru** [comment]
I consider updating espree to v3

**Comment by h13i32maru** [comment]
Please check the latest ESDoc
