### ISSUE TITLE
Turn off warning output

### ISSUE THREAD

**Issue by benderTheCrime** [esdoc/esdoc#229]
Is it possible to pass an option to stop these warnings?

```
warning: signature mismatch
```

**Comment by h13i32maru** [comment]
Please post your codes for reproduce in my env.

**Comment by benderTheCrime** [comment]
@h13i32maru I have no code to post related to this, but I can give you an example:

I have a dependency injector binding function arguments to a function that I do not want to include in the list of passed params in the documentation:

```javascript

let wrappedFn = fn.bind(null, 'foo');

/**
 * An arbitrary function
 * @param {string} bar
 * /
function fn(foo, bar) {
    // Does something
}

```

I never want to report on the bound params and the documentation engine appropriately finds these circumstances and warns me, but does not document them. I believe this is the correct behavior, but I think there should be an option to disable the warnings output to the terminal. What do you think?

**Comment by h13i32maru** [comment]
> an option to disable the warnings output to the terminal.

This is already in [config.lint](https://esdoc.org/config.html)
