### ISSUE TITLE
Custom manual chapters

### ISSUE THREAD

**Issue by cristinecula** [esdoc/esdoc#232]
The integrated manual feature is awesome. Would it be possible to add the ability to define custom "chapters", alongside the available ones? I want to add some information regarding "contributing" to my project.

**Comment by cristinecula** [comment]
I just saw #227, so I'll close this ticket :)

**Comment by h13i32maru** [comment]
I improved a manual feature.
Please check it.
https://github.com/esdoc/esdoc/issues/171#issuecomment-269403218
