### ISSUE TITLE
Remove project root from source list?

### ISSUE THREAD

**Issue by neezer** [esdoc/esdoc#234]
It seems that whatever configuration is set at `"source": "/web/static/js"` is used when creating file references in the generated output:

![sources list](http://zc.d.pr/1cHMq/5kuL0zYt+)

(Note that every file on this page is prefixed with `js`).

Is there anyway to turn this off? 

--

My directory structure is like this:

```
web/static/js
├── esdoc.js
├── app.js
├── doc
│   └── esdoc generated files here
├── lib
│   └── deep nested hierarchy here
├── pages
│   └── deep nested hierarchy here
└── routes.js
```

... and my config looks like this:

```json
{
  "source": "./web/static/js",
  "destination": "./web/static/js/doc",
  "excludes": ["^doc"],
  "index": "./web/static/js/README.md",
  "package": null,
  "plugins": [
    {
      "name": "esdoc-importpath-plugin",
      "option": {
        "replaces": [{ "from": "^mp/js/", "to": "" }]
      }
    },
    { "name": "esdoc-es7-plugin" }
  ]
}
```

**Comment by h13i32maru** [comment]
@neezer Hi! I do not plan to remove root dir path. [ESDoc Plugin API](https://esdoc.org/api.html) may help you.

**Comment by neezer** [comment]
@h13i32maru I couldn't find any way to configure things to turn this off. Also I was just asking if this could be configured as an option. Having the prefix in front of every file in the entire list feels redundant and unnecessary.

Do you have an example of how to use the existing API to accomplish what I'm after?

**Comment by typhonrt** [comment]
@neezer while specific to JSPM path substitution and such check out [esdoc-plugin-jspm](https://www.npmjs.com/package/esdoc-plugin-jspm). Particularly here:
https://github.com/typhonjs-node-esdoc/esdoc-plugin-jspm/blob/master/src/plugin.js#L368-L380
