### ISSUE TITLE
Support for static modules / methods

### ISSUE THREAD

**Issue by Oza94** [esdoc/esdoc#237]
Hello all,

I know this issue is not new and that it has already been stated that there will be [no support for things such as `@module`](https://github.com/esdoc/esdoc/issues/66#issuecomment-139998056). However, I would like to share my use case.

I develop a client / server game where a lot of the backbone is shared through a dedicated module. In this shared module there is a lot of static helpers with convenient methods, the file structure is something like : 

```
src/
-vector2d.js
-random.js
-math2d.js
-color.js
...
-components/
-systems/
```

For the files in sub-folders this is fine : they are grouped by folder name. Howerver for the files at root, I end up having 40+ functions in the global namespace : 

![esdoc screenshot](http://i.imgur.com/cpg0oDi.png)

I workaround I found is to change `src/module.js` to `src/module/index.js` to take advantage of folders grouping but this is not optimal for project structure. Will ESDoc support static modules somehow? In the JavaScript userland I do not really understand why "sticking to classes", JS code can take a lot of forms and documentation tools should support that IMO.

*Note* I really like the tool, awesome job!

**Comment by philipnilsson** [comment]
I'm really liking Esdoc as well, output looks great, works perfectly. 

Unfortunately, this very issue is currently preventing me from using esdoc at work. We have a lot of code in a functional style, and having all functions packed together in a very long list under "Function" is simply not acceptable for us.

I'd like to consider supporting some simple tag, let's call it `@modulename Random`, which will simply result in a new page in the documentation, like the "Function" page we see today, but with only the exports from the current file. I'm willing to look into a PR for this knowing it'd be considered for acceptance.

In my use case this wouldn't affect the sidebar at all.

**Comment by Oza94** [comment]
@philipnilsson look at #186 , we can add support for meta-programming without touching esdoc/esdoc with the plugin system. I also need something very simple to be able to groupe static methods (either by filename or some special label I define through tags).

ESDoc output is very nice, and I like how it deduce a lot of infos from your code so you don't have to type as much doc as other solutions (less noise, easier doc maintenance, ect.).

Unfortunatly I do not have the time to understand the plugin the system and create something usable. I've looked at the existing plugins and the code seems small but understanding the different stages of parsing, ast, doc generation takes time.. However I would be pleased to contribute if someone starts a repo.

**Comment by h13i32maru** [comment]
@Oza94 @philipnilsson I understood your use case. But I like class base than function base. The ideal is that the both style(class base and function base) are satisfied. However I do not have the concrete and simple feature.

Thanks.

**Comment by philipnilsson** [comment]
@h13i32maru Would you accept a PR for something like this?

**Comment by gdad-s-river** [comment]
@h13i32maru would you?
