### ISSUE TITLE
Add support for package.json to store config

### ISSUE THREAD

**Issue by siggysamson** [esdoc/esdoc#238]
Hey,

first, thanks for ESDoc! So far I've used it in 2 projects and it works great. Recently I discovered one thing though that I'd like to see improved:

Right now it's necessary to provide a config file to the esdoc command, see the [README](https://github.com/esdoc/esdoc#usage) and [ESDocCLI.js](https://github.com/esdoc/esdoc/blob/master/src/ESDocCLI.js#L40). In order to have a cleaner setup/repository I'd like to see support for the config being in the package.json - see e.g. [ESLint](http://eslint.org/docs/user-guide/configuring) or [Babel](https://babeljs.io/docs/usage/babelrc/).

I'd suggest to make the _c_ argument optional ([ESDocCLI.js](https://github.com/esdoc/esdoc/blob/master/src/ESDocCLI.js#L42)) and instead add a condition to load the package.json and search for a property, possibly **esdoc** in the provided object. As an example, here is the way ESLint is doing it: [lib/config/config-file.js](https://github.com/eslint/eslint/blob/master/lib/config/config-file.js#L172).

If that's a possible addition to the project I can create a pull request but before doing so I wanted to make sure that this actually makes sense.

Thanks

**Comment by h13i32maru** [comment]
@siggysamson Hi, thanks for this issue. I think the better that the ways to achieve the goal are more less. So I do not support your suggestion. Sorry.
