### ISSUE TITLE
Test cases not being detected without the extension .spec.js

### ISSUE THREAD

**Issue by mike-schultz** [esdoc/esdoc#240]
For some reason my test cases are not being picked up properly by esdoc 
```
my-project/
└── src
    ├── MyClass.js
└── test
    ├── testcases
    ├── more-testcases
    └── testcase-1.js
```

and my esdoc.json
```
{
  "source": "./src",
  "destination": "./docs",
  "test": {
    "type": "mocha",
    "source": "./test"
  }
}
```

The documentation renders out fine, and even adds the **test** link in the header, but it does not render the /test.html file. Interestingly enough, if I use the extension `*.spec.js` instead of `*.js` everything works fine.

**Comment by h13i32maru** [comment]
@mike-schultz Hi. Please see [config.test.incluces](https://esdoc.org/config.html)
