### ISSUE TITLE
Allow Manual pages to be extended

### ISSUE THREAD

**Issue by Chowarmaan** [esdoc/esdoc#241]
I must first start with thanks for a great tool.  It works right away and documents well, much better than JSDoc. In building up our documentation, it would be nice to be able to update the manual sections with other files than you have hard coded.  

Could you extend the pages of the manual section to simply use the keys as the sections, and then the documents.  So instead of:
"manual": {
				"asset": "./manual/asset",
				"overview": ["./manual/overview.md"],
				"installation": ["./manual/installation.md"],
				"usage": ["./manual/usage.md"],
				"tutorial": ["./manual/tutorial.md"],
				"configuration": ["./manual/configuration.md"],
				"example": ["./manual/example.md"],
				"faq": ["./manual/faq.md"],
				"changelog": ["./CHANGELOG.md"]
},
which is hard set, you can use any key to add additional sections in order, and have additional sections/pages without the need for code changes for adding the sections.  If you wanted to add a Data Model section, you could simply add a new section:
"datamodel": ["./manual/DataModel.md"],

**Comment by h13i32maru** [comment]
@Chowarmaan Hi. I do not support to your request. Please read the [issue comment](https://github.com/esdoc/esdoc/issues/171#issuecomment-180680182)

**Comment by h13i32maru** [comment]
I improved a manual feature.
Please check it.
https://github.com/esdoc/esdoc/issues/171#issuecomment-269403218
