### ISSUE TITLE
When defining a type of type function that has arguments esdoc will unexpectedly fail

### ISSUE THREAD

**Issue by silkentrance** [esdoc/esdoc#242]
Documenting a parameter or property or type such as

```
@typedef {function(a, b, c}:*} theType
```

esdoc will fail with

```
TypeError: Cannot read property 'replace' of undefined
    at /usr/lib/node_modules/esdoc/out/src/Publisher/Builder/DocBuilder.js:925:34
    at Array.map (native)
    at IdentifiersDocBuilder._buildTypeDocLinkHTML (/usr/lib/node_modules/esdoc/out/src/Publisher/Builder/DocBuilder.js:920:41)
```

This is due to the fact that the user forgot to put in the type annotations.

Be it as it may, the user will have a hard time figuring out which doc comment is causing that issue.

Perhaps make this more resilient in that esdoc will assume ``*`` as the type hint if none was specified?

**Comment by h13i32maru** [comment]
@silkentrance Hi. Please write a argument type.

```javascript
/**
 * @typedef {function(a: number, b: string, c: boolean[]): *} theType
 */
```

<img width="469" alt="2016-03-19 14 19 50" src="https://cloud.githubusercontent.com/assets/985170/13896810/af67d0e2-eddd-11e5-8c68-db106cf7368a.png">

**Comment by silkentrance** [comment]
@h13i32maru The question is whether this can be considered a short coming of esdoc. I for my part would think that by failing with an unrelated exception is actually a short coming in the error handling of esdoc.

Esdoc should at least warn the user about the issue and that it was unable to parse the doc comment.
