### ISSUE TITLE
Allow function params to have a defined return type

### ISSUE THREAD

**Issue by StephanBijzitter** [esdoc/esdoc#243]
Given the following class:
```es6
import AssertionError from '../error/AssertionError';

/**
 * Provides functions to assert, validate and sanitize data types.
 */
class Sanitation {

    /**
     * Asserts an expression, and throws an error when it does not validate.
     *
     * @param {boolean|function:boolean} expression An expression.
     * @param {string} actual The actual value.
     * @param {string} expected The expected value.
     * @throws {AssertionError} If the expression evaluated to `false`.
     * @see http://wiki.ecmascript.org/doku.php?id=strawman:assert
     */
    static assert(expression, actual, expected) {
        if (expression instanceof Function) {
            expression = expression();
        }

        if (!expression) {
            throw new AssertionError(actual, expected);
        }
    }
}

export default Sanitation;
```

The following is generated by ESDoc:
<img width="1043" alt="screen shot 2016-03-14 at 23 21 31" src="https://cloud.githubusercontent.com/assets/1649903/13761890/967579d6-ea3b-11e5-9e6b-535d10a6f05a.png">

With `function:boolean` I am trying to document _a function that returns a boolean type_. Based on the [tag documentation](https://esdoc.org/tags.html), this is not yet supported.

I don't know how much trouble this would be to add, or whether this `function:type` syntax is even the proper way to declare a param like this at all, but I would really like it if ESDoc could make this render a bit prettier.

Of course I'm open for input, and with a clear solution (instead of a goal that I am proposing), I _may_ be able to write this functionality myself. But I would need input from the community first.

**Comment by h13i32maru** [comment]
@StephanBijzitter Hi! Thanks for this issue.

Please write ``function(): boolean`` instead of ``function: boolean``.

```javascript
/**
 * this is example.
 * @param {boolean|function():boolean} a
 * @param {number} b
 */
export default function foo(a, b){}
```
<img width="465" alt="2016-03-19 14 26 24" src="https://cloud.githubusercontent.com/assets/985170/13896827/976f8a9c-edde-11e5-93b2-506ee7b48de3.png">

**Comment by StephanBijzitter** [comment]
Seems overly verbose to me, but alright.
Thanks!
