### ISSUE TITLE
Not able to create a link to an object typedef property

### ISSUE THREAD

**Issue by smaximov** [esdoc/esdoc#244]
Hello.

Given the following object type definition

``` js
/**
 * Foo typedef description.
 * @typedef {Object} Foo
 * @property {boolean} bar - a description of bar
 */
```

When I try to create a link to the `bar` property using either `{@link Foo.bar}` or `{@link Foo#bar}` identifier syntax, it doesn't render as a link. I expected it to render the link to the property similar to how it renders links to methods and members of classes. Is it intended behavior?

Thanks.

**Comment by h13i32maru** [comment]
@smaximov Hi! Thanks for this issue. I do not create deep link to typedef. Because typedef is temporary way for express of type. Sorry.

But if you can write the following code, can it help you?

```javascript
/**
 * link to {@link Foo | Foo.bar}
 **/
function foo(){}
```

output:
```html
<a href="Foo URL">Foo.bar</a>
```

**Comment by smaximov** [comment]
In my case it won't make much sense, since the link to `Foo.bar` is inside
the very documentation of `Foo`:

``` js
/**
 * Foo typedef description…
 * …@{link Foo.bar }
 * …some more  description of Foo
 * @typedef {Object} Foo
 * @property {boolean} bar - the description of bar
 */
```

BTW, I've never sees the syntax `{@link ITEM | URL }` in the docs.

Anyway, I don't particularly need this feature, I just thought it would be
a nice thing to have.

Thanks for your response. If it's not a bug, I believe the issue can be
closed.

2016-03-19 15:52 GMT+10:00 Ryo Maruyama <notifications@github.com>:

> @smaximov <https://github.com/smaximov> Hi! Thanks for this issue. I do
> not create deep link to typedef. Because typedef is temporary way for
> express of type. Sorry.
>
> But if you can write the following code, can it help you?
>
> /** * link to {@link Foo | Foo.bar} **/function foo(){}
>
> output:
>
> <a href="Foo URL">Foo.bar</a>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/esdoc/esdoc/issues/244#issuecomment-198640724>
>



-- 
Regards,
Sergei Maximov

**Comment by smaximov** [comment]
In my case it won't make much sense, since the link to `Foo.bar` is inside
the very documentation of `Foo`:

``` js
/**
 * Foo typedef description…
 * …@{link Foo.bar }
 * …some more  description of Foo
 * @typedef {Object} Foo
 * @property {boolean} bar - the description of bar
 */
```

BTW, I've never sees the syntax `{@link ITEM | URL }` in the docs.

Anyway, I don't particularly need this feature, I just thought it would be
a nice thing to have.

Thanks for your response. If it's not a bug, I believe the issue can be
closed.
