### ISSUE TITLE
Inherited functions are not shown on the doc

### ISSUE THREAD

**Issue by StephanBijzitter** [esdoc/esdoc#245]
``` es6
class Animal {

    constructor(name) {
        Object.assign(this, {name});
    }

    isDeadYet() {
        return !!this.isDead;
    }

    die() {
        this.isDead = true;
    }
}

export default Animal;
```

``` es6
import Animal from './Animal';

class Cat extends Animal {

    constructor(name) {
        super(...arguments);

        this._lives = 9;
    }

    die() {
        if (this._lives) {
            this._lives--;
        } else {
            super.die();
        }
    }
}

export default Cat;
```

``` json
{
  "source": "./src/js",
  "destination": "./bin/esdoc",
  "includeSource": false,
  "lint": true,
  "plugins": [
    {
      "name": "esdoc-es7-plugin"
    }
  ]
}
```

This does not show the inherited functions for the `Cat`, even though ESDoc advertises it can do this on: https://esdoc.org/feature.html#es6-class

Running ESDoc v0.4.5

**Comment by h13i32maru** [comment]
@StephanBijzitter Hi. I can see inherited functions in my environment. Please check your file/directory structure.

```
$ tree ./
./
├── esdoc.json
└── src
    ├── Animal.js
    └── Cat.js
```

<img width="262" alt="2016-03-19 14 57 26" src="https://cloud.githubusercontent.com/assets/985170/13896940/ebb193ee-ede2-11e5-82dc-9039fa5fc0e6.png">

**Comment by StephanBijzitter** [comment]
@h13i32maru This is all I get:
<img width="1061" alt="screen shot 2016-03-21 at 08 53 17" src="https://cloud.githubusercontent.com/assets/1649903/13912937/6b174b28-ef42-11e5-9d63-81ebd306cfb8.png">

My file tree is the same as yours, except I have one subdirectory inside `src`.

**Comment by h13i32maru** [comment]
If is problem, please write new issue.
