### ISSUE TITLE
import Default from ... breaks internal linking

### ISSUE THREAD

**Issue by Victorystick** [esdoc/esdoc#247]
In the following example, the documentation generated doesn't understand that `Quux` inherits from `Bar`. We should be able to give a default export a locally different name and still have functioning internal linking.

``` js
// Bar.js
export default class Bar {}
```

``` js
// main.js
import Foo from './Bar.js';

export default class Quux extends Foo {}
```

**Comment by h13i32maru** [comment]
@Victorystick Sorry for late reply.

This problem is very hard for ESDoc. 😢 
Please use a `@extends`.

```js
// main.js
import Foo from './Bar.js';

/**
 * @extends {Bar}
 */
export default class Quux extends Foo {}
```

**Comment by Victorystick** [comment]
But where does `Bar` come from in your example? It is never imported. Also, consider a situation like this:
```js
// main.js
import Foo from './Bar.js';
import Bar from './another/Bar.js';

export default class Quux extends Foo {}
```

**Comment by h13i32maru** [comment]
You can use full path using `<filePath>~<identifier>`.

`./src/baz.js`
```js
export default class Baz {}
```

`./src/foo.js`
```js
import Bar from './baz.js'
/**
 * @extends {src/baz.js~Baz}
 */
export default class Foo extends Bar {}
```
