### ISSUE TITLE
Allow source to be linked to Github

### ISSUE THREAD

**Issue by StephanBijzitter** [esdoc/esdoc#248]
Currently I disable `includeSource`, because I don't want the source code visible outside of Github.
It would be awesome to have an option `includeSourceGithub` which would link to a Github URL.

**Comment by andrewreedy** [comment]
:+1:

**Comment by typhonrt** [comment]
Just a FYI. I'm close to finishing a plugin that provides an enhanced left hand navigation view and it will support a context menu to open code on Github when the appropriate repo details are provided in package.json. I'll post an update here when the plugin is available.

**Comment by typhonrt** [comment]
I have published [esdoc-plugin-enhanced-navigation](https://www.npmjs.com/package/esdoc-plugin-enhanced-navigation) which provides a greatly enhanced left-hand navigation grouping by directory / file name / short name / kind and if you use JSPM / SystemJS and [esdoc-plugin-jspm](https://www.npmjs.com/package/esdoc-plugin-jspm) then JSPM packages are sorted separately.

**Comment by h13i32maru** [comment]
I will consider in the below issues.
https://github.com/esdoc/esdoc/issues/344
