### ISSUE TITLE
Allow tests to be parsed, without being run

### ISSUE THREAD

**Issue by StephanBijzitter** [esdoc/esdoc#249]
My tests are written in Jest, which uses Jasmine.

I did document them as follows:

```
    /**
     * @test {NodeFileParser#getDefaultOptions}
     */
```

If my testing framework is not supported, I would wish for ESDoc to only parse the documentation in the test files, without actually running the tests. That way, I can still link my tests to my documentation.

**Comment by h13i32maru** [comment]
I am not using Jest, but I think that Jest is ``describe/it`` style same as Mocha. If this is right, please try ``test: {type: "mocha", source: "your-test-dir"}`` in esdoc.json with Jest test code.

``type: "mocha"`` only suggests ``describe/it`` style test code. So not run test code actually.

Thanks 😄
