### ISSUE TITLE
Don't copy package.json into documentation

### ISSUE THREAD

**Issue by StephanBijzitter** [esdoc/esdoc#250]
It causes confusion and some parsers that scan for package.json files throw errors because there's two files with identical package names.

**Comment by basilfx** [comment]
It was added by commit 9548fbbfdc51a9133db52a94de3c7518cbd2dc44. If I grep through the generated output, there is no reference to the `package.json`, so I don't understand why it is included.

**Comment by h13i32maru** [comment]
``package.json`` is used by https://github.com/esdoc/esdoc-hosting, because ``package.json`` has some meta data(url, repo, version, description and etc).

If you want to remove ``package.json``, please use plugin api.

**Comment by jupl** [comment]
The inclusion of this `package.json` breaks use of `react-native-cli`.

**Comment by h13i32maru** [comment]
Please check this.
https://github.com/esdoc/esdoc/issues/357#issuecomment-269201206
