### ISSUE TITLE
Integrate ESDoc options into package.json

### ISSUE THREAD

**Issue by StephanBijzitter** [esdoc/esdoc#251]
Several tools (such as Babel and Jest) support writing the configuration/options inside the package.json, which keeps the root directory clean of any configuration files. ESDoc should also support this.

**Comment by h13i32maru** [comment]
For now, I do not support to this.

**Comment by h13i32maru** [comment]
Please check latest ESDoc v0.5
https://esdoc.org/manual/usage/usage.html#configuration
