### ISSUE TITLE
Embedded class member specification

### ISSUE THREAD

**Issue by hmil** [esdoc/esdoc#255]
Sometimes, a class creates members in such a way that ESDoc doesn't recognize them.

example:

``` js
class MyClass {

  constructor() {
    this._createAttribute('myAttribute', 2);
  }

  _createAttribute(name, defaultVal) {
    this[name] = defaultVal;
  }
}
```

It would be useful in such cases to be able to document members explicitely like so:

``` js
/**
 * A class with hidden members
 * @member {number} myAttribute An integer attribute
 */
class MyClass {
...
```

**Comment by h13i32maru** [comment]
Please check https://github.com/esdoc/esdoc/issues/305#issuecomment-269851751
