### ISSUE TITLE
Process ES6 as ES7 code

### ISSUE THREAD

**Issue by montogeek** [esdoc/esdoc#257]
Hi!

I want to use ESDoc to write and generate my code documentation, I have found a problem with the following code:
```js
// @flow
import request from './request';
import User from '../models/User';
import { BASE_URL_V2 } from '../config';

const Auth = {
  login: (username: string, password: string): Promise => {

    const options = Object.assign({}, {
      body: new User(username, password)
    });

    return request.post(`${BASE_URL_V2}auth/token/`, options).then(saveToken);
  },
  logout: () => {
    localStorage.removeItem('auth-token');
  },
  isAuthenticated: () => {}
}

/**
 * Saves the auth token to local storage
 * @param  {Object} response: Object        Response
 * @return {Object}           [description] Response
 */
function saveToken(response: Object): Object {
  if(!response || !response.token) {
    return {};
  }

  localStorage.setItem('auth-token', response.token);

  return response;
}

export default Auth;

```

ESDoc is reporting that could not process it since is ES7 code, I have already installed the plugin but the error persists.

My esdoc.json file:
```json
{
  "source": "./src",
  "destination": "./esdoc",
  "plugins": [
    {"name": "esdoc-es7-plugin"}
  ],
  "test": {
    "type": "mocha",
    "source": "./test"
  }
}

```

**Comment by lj222kj** [comment]
Does esdoc-es7-plugin exist within your package.json file as well?

**Comment by montogeek** [comment]
Yes

**Comment by hmil** [comment]
All parsing errors are treated the same. Esdoc tells you that in case you were trying to parse es7 code, you should use the es7 plugin, but in fact it has no clue what kind of code you are parsing.
I would bet that the types in your code are what's causing the problem. Do you know at what stage this feature is ? I believe it is not part of es7...

**Comment by montogeek** [comment]
Hi @hmil those are Flow annotations, as you can see at the top of the file

**Comment by hmil** [comment]
Thanks for the heads up.
That is indeed what's causing the problem. ESDoc uses espree to parse the code but espree [does not support flow annotations](https://github.com/eslint/espree/issues/189).
The only way to get around this is to change the parser with a [plugin](https://esdoc.org/api.html#plugin-feature).

**Comment by montogeek** [comment]
@hmil Thank you :)

**Comment by montogeek** [comment]
@hmil Thank you :)

**Comment by typhonrt** [comment]
Late to the party here.. I have [a fork of ESDoc](https://github.com/typhonjs-node-esdoc/esdoc) that uses [babylon](https://www.npmjs.com/package/babylon) which will parse any ES6/ES7/edge/flow, etc. To be clear though it parses the AST of course, but doesn't include any type info from flow typing into the docs produced.

**Comment by h13i32maru** [comment]
Please check latest ESDoc and [ECMAScript Proposal Features](https://esdoc.org/manual/usage/feature.html#ecmascript-proposal).
