### ISSUE TITLE
How to document a (non getter) static property

### ISSUE THREAD

**Issue by ibc** [esdoc/esdoc#259]
``` js
export default class Test {
  /**
   * Static getter (it calls a function every time it is read).
   */
  static get foo() {
    return 'FOO';
  }
}

/**
 * Static property.
  */
Test.bar = 'BAR';
```

Is there any way for _esdoc_ to document `Test.bar`?

**Comment by andreu86** [comment]
I'm struggling with it too...

**Comment by bman654** [comment]
Have you tried writing it inline as a static property?

```es6
export default class Test {
  /**
   * Static getter (it calls a function every time it is read).
   */
  static get foo() {
    return 'FOO';
  }

  /**
   * Static property
   */
  static bar = 'BAR';
}

```

**Comment by andreu86** [comment]
I tried to write it inline, but it wasn't documented 😞

**Comment by ibc** [comment]
`static bar = 'BAR'` is invalid syntax.

**Comment by h13i32maru** [comment]
ESDoc does not support ``Test.bar = 'BAR'`` style. ESDoc supports the following code.

```javascript
export default class Test {
  static get bar() {
    return this._bar;
  }
  
  static set bar(value) {
    this._bar = value;
  }
}
```

**Comment by ibc** [comment]
That's nice but we cannot refactor our entire Node code and make it less efficient by using setters (functions) rather than simple property assignments.

**Comment by typhonrt** [comment]
@h13i32maru what do you think about supporting assignment operations on classes that occur in the same file that the class is defined. This could be applied to static properties and assignment of additional methods to the class prototype. This should be possible without much change to DocFactory. 

The caveat being that this only applies to additions made in the same file where the class is defined. The AST will expose the assignments. 

As an aside right now assigning a new method to the class prototype such as `MyClass.prototype.newMethod = function() {...}` actually creates an unexported function doc which is incorrect. 

This is a reasonable feature seemingly and the implementation can handle both of these situations I mention above.

**Comment by Robinfr** [comment]
Struggling with the same issue, would like to be able to use the `Test.bar = 'foo'` syntax.

**Comment by h13i32maru** [comment]
https://github.com/esdoc/esdoc/issues/259#issuecomment-233167560
