### ISSUE TITLE
No way to document an exported Object

### ISSUE THREAD

**Issue by ibc** [esdoc/esdoc#260]
If a file exports an object whose keys have documented functions as values, those functions are not documented.

I mean:

``` js
/**
 * UTILS STUFF
 */
const utils = {
    /**
     * UTIL FOO
     */
    UtilFoo: function() {}
};

export { utils };
```

Just `Utils` VARIABLE is documented.

**Comment by lj222kj** [comment]
Have you found a solution for this? Am struggling with the same issue.

**Comment by ibc** [comment]
> Have you found a solution for this?

Obviously not.

**Comment by benderTheCrime** [comment]
any word on this @h13i32maru? At least for me, it's a huge deterrent, I may have to stop using ESDoc as a result.

**Comment by anatoliyarkhipov** [comment]
As a tmp solution you can define `utils` as a class and immediately instantiate it, like this:

```js
/**
 * UTILS STUFF
 */
class Utils {
    /**
     * UTIL FOO
     */
    UtilFoo() {}
}


export const utils = new Utils
```

![esdoc example](https://cloud.githubusercontent.com/assets/1934180/14415581/e2f724a4-ffb1-11e5-9ee1-a37abf82db73.png)

**Comment by ibc** [comment]
By using esdoc, I found myself refactoring my whole code just to make esdoc happy. Not the way to go.

**Comment by benderTheCrime** [comment]
@ibc Not very constructive.

**Comment by benderTheCrime** [comment]
@anatoliyarkhipov Yeah, I had had static classes set up, but they amount to ~1kb extra a piece when webpacked (as a result of `_classCallCheck`ing and `possibleConstructorReturn`, etc, etc) and so I decided that I would rather wait for a permanent solution than add a lot of boilerplate for no reason.

**Comment by ibc** [comment]
Sorry, I just wanted to describe my experience. Esdoc behaves verh nicely, but just if the code follows a very strict coding guideline.

**Comment by andreu86** [comment]
Same problem

**Comment by h13i32maru** [comment]
ESDoc supports codes that are class base OOP. The code is not class base.
However you can write the below code.

```js
/**
 * UTILS STUFF
 * @property {function()} UtilFoo - this is function.
 */
const utils = {
  UtilFoo: function() {}
};

export { utils };
```

**Comment by JulianKingman** [comment]
I'd love to see an option for this.
