### ISSUE TITLE
Better nav sorting

### ISSUE THREAD

**Issue by silkentrance** [esdoc/esdoc#268]
Currently, nav items are sorted by their dirPath/longname and kind. Sorting by longname will cause items to be sorted by their full path instead of alphabetically:

![image](https://cloud.githubusercontent.com/assets/6068824/14588978/70d9592a-04d7-11e6-8f6f-1d93c30cdd61.png)

See the provided PR that sorts items correctly:

![image](https://cloud.githubusercontent.com/assets/6068824/14588973/57a6ccee-04d7-11e6-9084-5e565ca9c01d.png)

**Comment by typhonrt** [comment]
FYI I'm publishing soon a plugin to replace the left hand navigation with a much improved version including a collapsible file tree accordion view. I'll definitely make sure it sorts by filename in a given directory. Some other nice benefits of the plugin is that it provides a context menu to open the source on Github if the package.json contains the appropriate repo details. I also have plugins for JSPM and soon NPM which will group local source and JSPM / NPM managed source in separate sections.

I'll definitely drop a note here when this plugin is ready.

**Comment by jcowgar** [comment]
@typhonrt, any update on that plugin?

**Comment by typhonrt** [comment]
I should have it published today and will post a note when it's live.

**Comment by typhonrt** [comment]
I have published [esdoc-plugin-enhanced-navigation](https://www.npmjs.com/package/esdoc-plugin-enhanced-navigation) which provides a greatly enhanced left-hand navigation grouping by directory / file name / short name / kind and if you use JSPM / SystemJS and [esdoc-plugin-jspm](https://www.npmjs.com/package/esdoc-plugin-jspm) then JSPM packages are sorted separately.

**Comment by silkentrance** [comment]
@h13i32maru any progress on this? while the plugin looks good, I'd rather use vanilla esdoc for now :grinning:

**Comment by typhonrt** [comment]
Just try the plugin.. ;P I just got things somewhat stable and out there including quite deep [JSPM](http://jspm.io/)  / [esdoc-plugin-jspm](https://www.npmjs.com/package/esdoc-plugin-jspm) support. It adds a bit of flare for sure, but is solidly functional especially if you add `repository` fields for Github. IE you can right context click the left-hand nave to jump to the exact line # for the doc / tag at hand. Other SCMs can be supported as requested.

**Comment by silkentrance** [comment]
@typhonrt sure will try it out some time, yet the core needs to be fixed, too.

**Comment by typhonrt** [comment]
Alot of the core can be improved. @h13i32maru  should consider adding collaborators to esdoc.

**Comment by h13i32maru** [comment]
@silkentrance Sorry late reply. Please check the latest ESDoc. If is problem, please comment and then I re-open this.
