### ISSUE TITLE
functions with arrow function body are ignored

### ISSUE THREAD

**Issue by kaiserkoenig** [esdoc/esdoc#271]
Hi,

we 're using ESLint 'arrow-body-style' in our JSX-files an the functions are completely ignored. if i remove the arrow it works nice.... 

`//bad - doe not work in esdoc
foo = () => {
    return 0;
};

//good 
foo () {
    return 0;
};
`

**Comment by kaiserkoenig** [comment]
also static propTypes = {} are ignored

**Comment by mwxmielke** [comment]
+1

**Comment by ohs2033** [comment]
+1

**Comment by typhonrt** [comment]
Yeah... This is a known issue and there are essentially several duplicates. I've left some thoughts in #318 recently.

**Comment by h13i32maru** [comment]
Please check latest ESDoc version.

I re-open this issue if is problem.

**Comment by dontpanic5** [comment]
I'm still getting this issue in 0.5.2.

This code will stop ESDoc from documenting the file:

	export default class Test extends React.Component {

		IBreakIt = () => {
			// broken
		};

		componentDidUpdate() {
			// stuff
		};

		render() {
			return (<div/>);
		};
	}

**Comment by nirajbhutada** [comment]
ESDoc v0.5.0 supports arrow function exporting. Please check it.
