### ISSUE TITLE
Circular `{extends}` causes infinite loop

### ISSUE THREAD

**Issue by benderTheCrime** [esdoc/esdoc#275]
I found this as a byproduct of a mistake in my own code, much to my chagrin:

https://github.com/esdoc/esdoc/blob/master/src/Publisher/Builder/DocResolver.js#L215:

``` javascript
  while (1) {
    if (!doc.extends) break;

    let superClassDoc = this._builder._findByName(doc.extends[0])[0];
    if (superClassDoc) {
      chains.push(superClassDoc.longname);
      doc = superClassDoc;
    } else {
      chains.push(doc.extends[0]);
      break;
    }
  }
```

This one speaks for itself, but basically if I've got an `{extends}` tag that "extends" itself, ESDoc hangs and never passes this while loop.

**Comment by h13i32maru** [comment]
@benderTheCrime Thanks! I fixed it https://github.com/esdoc/esdoc/commit/9081c45e18909b9abca63d36c47f4155fe7709f5
