### ISSUE TITLE
@typedef for function throws

### ISSUE THREAD

**Issue by cchamberlain** [esdoc/esdoc#286]
Perhaps I have the usage off here but when I have this in a file. If the usage is wrong, seems like it still shouldn't throw.

``` js
/**
 * @typedef {function(...args): string} bunyanSerializer
 */
```

![image](https://cloud.githubusercontent.com/assets/424694/15565036/7b08dbf6-22cc-11e6-8b6e-b2671783fe3b.png)

**Comment by typhonrt** [comment]
It's likely `{function(...args): string}` is what is tripping things up. Indeed ESDoc shouldn't crash per se. For instance the following: `@type {Array<{string, string, string}>}` will crash ESDoc last time I checked.

**Comment by h13i32maru** [comment]
Please write type of variables.

```js
/**
 * @typedef {function(...args:number[]): string} bunyanSerializer
 */
```
