### ISSUE TITLE
Hide Externals

### ISSUE THREAD

**Issue by vicsparkz** [esdoc/esdoc#287]
Is there anyway to link to external classes without having them show up in sidebar? 

I'd like them to be treated the same as the built in externals.

Thanks.

**Comment by typhonrt** [comment]
Through plugins this is possible. For instance I have a plugin, [esdoc-plugin-jspm](https://www.npmjs.com/package/esdoc-plugin-jspm), that makes ESDoc aware of external packages managed by JSPM / SystemJS. That way any external package that has a proper esdoc config file is linked including inheritance and everything else you'd expect. I'm working on a plugin for NPM modules soon. As far as grouping things logically in the left hand navigation I created a plugin, [esdoc-plugin-enhanced-navigation](https://www.npmjs.com/package/esdoc-plugin-enhanced-navigation), which provides an enhanced navigation with folding which is aware of data generated from esdoc-plugin-jspm and soon the NPM version so external code is initially hidden. Outside of getting involved in making a plugin yourself or by chance the JSPM / NPM ones I'm working on fit your use case it's not likely arbitrary linking of external code will be added to esdoc anytime soon.

**Comment by h13i32maru** [comment]
I can not understand the situation with this. Please write a new issue with detail.
