### ISSUE TITLE
Constants should be documented

### ISSUE THREAD

**Issue by kdex** [esdoc/esdoc#289]
The documentation should treat `const` variables different from `let` or `var` variables. For documentation purposes, it is useful to know which values are constants and which could change during runtime.

Example:

``` js
    export const TEN = 10; // Is constant during runtime
    export let ten = 10; // Could change during runtime
```

It might be enough to give them another symbol in the menu and change the heading to "Constant" instead of "Variable".

**Comment by typhonrt** [comment]
For now check out if adding `@constant` works.. 
http://usejsdoc.org/tags-constant.html

Eventually adding the AST parsing to automatically assign a tag is possible.

**Comment by h13i32maru** [comment]
I don't have plan to support it. Please use naming rule or description.
