### ISSUE TITLE
Improve type inference

### ISSUE THREAD

**Issue by kdex** [esdoc/esdoc#290]
Currently, ESDoc auto-detects the variable type if the expression is just a literal:

``` js
    export const m = 1; // automatically detected as "number"
```

However, when dealing with compound expressions like:

``` js
     export const km = 1000 * m; // type undetected
```

It would be great if ESDoc could use the information that `m` is of type `number` to figure out that `km` must be a `number`, too.

**Comment by typhonrt** [comment]
Are you adding type documentation? 
https://esdoc.org/tags.html#-type

Autodetection is not going to cover everything and certainly won't be able to determine runtime dynamic assignments.

**Comment by kdex** [comment]
@typhonrt Thanks, but this issue is really about inference, not about annotation. In the above case, `m` is defined as constant, so `1000 * m` wouldn't even possible to yield any other type than `number`, even at runtime considering dynamic typing. 

These cases shouldn't require to be manually annotated; ESDoc already does some basic inference, and it would be enough in every file to use the known type information to infer the type of variables in the same scope.

**Comment by typhonrt** [comment]
As mentioned ESDoc doesn't reconstruct the runtime relationships. By all means provide a PR with a better implementation as you can see things are quite simple at this point:
https://github.com/esdoc/esdoc/blob/master/src/Parser/ParamParser.js#L306-L314

Accurate type inference is well beyond the scope of the 1.0 version of ESDoc, but I'm not the author or control the roadmap.

**Comment by h13i32maru** [comment]
Type interface of expression is very hard. So for now I don't support it.
