### ISSUE TITLE
Major Fork: Streamlined and updated ESDoc version w/ Babylon support

### ISSUE THREAD

**Issue by typhonrt** [esdoc/esdoc#292]
Greets folks,

I spent ~12 hours over the weekend thoroughly updating ESDoc [in a fork](https://github.com/typhonjs-node-esdoc/esdoc) that majorly improves the core functionality. Here are some of the advancements:
- Supports latest Babylon parser w/ all plugins allowing any edge / ES7 code to be parsed.
- Updated all dependencies to the latest and removed unnecessary ones.
- Removed all unnecessary code and dependencies like the esdoc web site that was previously embedded.
- Removed all local scripts in favor of integrating [typhonjs-npm-build-test](https://www.npmjs.com/package/typhonjs-npm-build-test) which provides standarized build / deployment tooling; note for development only Node 5+ is now required taking advantage of flat packages.  
- All tests now produce coverage of the [ES6 codebase directly](https://codecov.io/github/typhonjs-node-esdoc/esdoc).

The biggest advancement of course is the switch to Babylon for parsing. One should now be able to fully parse any ES6+ / edge / ES7 code as all plugins of Babylon are enabled by default. That doesn't mean the edge / ES7 AST is parsed for inclusion of data into documentation generated, but future work can now support for instance flow typing. 

To test out this new effort please include the following in `package.json`:

```
"devDependencies": {
  "esdoc": "git+https://git@github.com/typhonjs-node-esdoc/esdoc.git"
}
```

For the time being to link directly from Github the transpiled `out/src/` code is committed to the repo. If a permanent fork moves forward with a release on NPM then the transpiled code will simply be removed from the repo as it will be generated in the publish / release process.

There is a branch made before the Babylon switch that has the [latest espree version](https://github.com/typhonjs-node-esdoc/esdoc/tree/espree-latest-before-babylon).

@h13i32maru please respond sooner than later and let's get a discussion going on whether I can be added as a collaborator to ESDoc and upstream this effort. The last thing I want to do is split the ESDoc community, but forward progress is important as well since ESDoc has clearly stalled. I know you mentioned you are still passionate about ESDoc, but please once again consider adding outside collaborators who can move it forward in your general absence. 

I certainly want to respect in every way your effort with ESDoc. I've learned so much from your effort from how to publish ES6 NPM modules to the importance of providing a plugin architecture for a successful project! I do want to point out though that a successful open source project often takes a community and that it can be hard for one person to do it all. You were a great `starter` and `architect` of ESDoc, but the effort now needs `debuggers` and `finishers` - here is a [basic blog post discussing this dynamic](http://jacquesmattheij.com/the-starter-the-architect-the-debugger-and-the-finisher).

I know that communication issues due to language concerns will remain a difficulty and thus trusting outside collaborators is challenging.

If it is decided that a fork is more appropriate I will continue to advance my version of ESDoc and eventually it will be non-compatible especially from a plugin perspective which is something I'm really going to pay attention to in trying to work out a compatible solution. It should be noted that all [TyphonJS](https://typhonjs.io/) repos / efforts are licensed under [MPLv2](https://www.mozilla.org/en-US/MPL/2.0/). I'll fully indicate where the fork originated and give all credit that is due. 

If we can find a way to have me involved directly in ESDoc as a collaborator I'd be glad to drop my fork and upstream everything. 

Thanks for your consideration and I look forward to making ESDoc the premiere documentation tool for Javascript.

**Comment by h13i32maru** [comment]
@typhonrt 

Thanks for this comment. I have finished the almost other works and private works. So I will forward ESDoc to v1.0.0.

## Roadmap ESDoc v1.0.0
I have the plan ESDoc v1.0.0 with the following changes.
- update to babel6 
- switch to babylon(or acorn)
- omit Node v4 and v5
- add new sections ``advanded or detail`` and ``architecture or design`` to manual feature (optional considering)
- enhance side menu bar for function basede code (but I have no idea...)

and refactoring test code at future work.

## Collaborator
Thanks for collaborator request. Pull requests and issues are welcome. However, right now I have no plan to adopt collaborators at least up to version 1.0.0. 

I am glad for your cooperation.

Thanks.

**Comment by typhonrt** [comment]
I have already finished this in the fork I've posted:
- update to babel6
- switch to babylon

I highly recommend switching to Babylon. It's slightly tricky due to the AST differences between ESTree and Babylon, but Babylon is a superset. I've already looked at the AST generated for some of the edge / ES7 / flow based code run through Babylon and it's worth switching to it. Basically the pain points in switching over w/ ESDoc codebase regards `ClassMethod` versus `MethodDefinition/FunctionExpression` differences, the specific `StringLiteral/BooleanLiteral/DirectiveLiteral/<etc.>` nodes versus ESTree `Literal` catch all, and the AST generated by Babylon has a top level program node, so the AST looks like ast.program.body instead of ast.body. Also switching to [typhonjs-ast-walker](https://www.npmjs.com/package/typhonjs-ast-walker) from `estraverse` is recommended as estraverse is hard coded for ESTree by default with no support for Babylon or non-standard AST tags like flow typing. `typhonjs-ast-walker` is [super simple](https://github.com/typhonjs-node-ast/typhonjs-ast-walker/blob/master/src/ASTWalker.js) and walks all nodes regardless of types and is a drop in replacement for `estraverse` and works almost immediately in ESDoc (there are two points where `return this.skip()` and `return this.break()` need to be omitted or changed to `return null`. 

The above changes are the toughest aspects of what you mentioned for a potential 1.0, but if you know what to look for in the AST differences it's not so hard. Would you accept a massive PR that updates this functionality across the codebase? Please do review my fork as I'm still willing to upstream if you can just commit to working on ESDoc and getting to your vision of 1.0 sooner than later.

Could you describe what you mean here in more detail?
- omit Node v4 and v5

As far as adding sections to the manual why don't you let users just configure things entirely instead of having predetermined slots?

Regarding the following:
- enhance side menu bar for function basede code (but I have no idea...)

If that involves the left-hand navigation bar please at least try my plugin [esdoc-plugin-enhanced-navigation](https://www.npmjs.com/package/esdoc-plugin-enhanced-navigation). Perhaps you can describe the side bar enhancements more or what you think is necessary.

-------------------

That said I highly encourage you to immediately clear out or accept the PRs in the queue. One of the more frustrating things for me is that I have [one sitting there](https://github.com/esdoc/esdoc/pull/263) for two months which is crucial for finishing several advanced plugins regarding AST processing. It's the main reason I need to fork ESDoc if it doesn't get accepted.

**Comment by eaviles** [comment]
For those looking for Flow support, I've just published a plugin that for now just removes Flow annotations and types. It's available at https://github.com/eaviles/esdoc-flow-plugin

**Comment by msmyers** [comment]
His fork is A+ quality. 

I cannot build my docs with esdoc (numerous null pointer errors to fix in the code). His worked first-try on my relatively large (and syntax homogenous) project.

Quality work.

**Comment by typhonrt** [comment]
@msmyers thanks for the nod. It does look like @h13i32maru is mostly done supporting Babylon with ESDoc, but I haven't tested it myself. You might try and link the master branch of ESDoc via:
`"esdoc": "git+https://git@github.com/esdoc/esdoc.git"`
and see if it can parse your project. Providing a new issue with an error report for any inconsistency between my fork and the master branch of ESDoc will really help in the next official release of ESDoc.
