### ISSUE TITLE
Cannot read property 'indexOf' of undefined when use array destructor in functions arguments

### ISSUE THREAD

**Issue by ipostol** [esdoc/esdoc#295]
Hello. I have some problem with create docs (http://prntscr.com/bdydlu)

When i am use something like this:

``` js
export function update([Error, Events]) { // array destructor
  return {type: UPDATE, payload: Events, error: Error};
}
```

esdocs throw error

when i am not use array destructor in function arguments all be okay.

Thank you for this project. He is awesome 👍

**Comment by ipostol** [comment]
I am found some solution for resolve this problem.

if u will use array function format, like this:
```js
export const update([Error, Events]) =>  ({ // array destructor
  type: UPDATE,
  payload: Events,
  error: Error
});
```
all be okay

**Comment by typhonrt** [comment]
@ipostol Good find. This is a legitimate bug with ESDoc. One solution is that you document this function like so:
```
/**
 * updates something
 *
 * @param {string} Error - some error
 * @param {object} Events - some events
 * @returns {{type: *, payload: *, error: *}}
 */
export function update([Error, Events]) { // array destructor
  return {type: UPDATE, payload: Events, error: Error};
}
```

When undocumented [ParamParser.js->guessParams](https://github.com/esdoc/esdoc/blob/master/src/Parser/ParamParser.js#L166-L256) is invoked and currently it doesn't handle the `ArrayPattern` node independently or as a left hand value of `AssignmentExpression`. 

@h13i32maru Please see this gist that solves the problem: https://gist.github.com/typhonrt/4ebde611d1517b350830b4a33c2b8267

In particular here are the three modification points:
- [AssignmentExpression left hand value](https://gist.github.com/typhonrt/4ebde611d1517b350830b4a33c2b8267#file-paramparser-js-guessparams-L17-L22)
- [Improved right hand value type guessing](https://gist.github.com/typhonrt/4ebde611d1517b350830b4a33c2b8267#file-paramparser-js-guessparams-L36-L44)
- [Handle bare ArrayPattern](https://gist.github.com/typhonrt/4ebde611d1517b350830b4a33c2b8267#file-paramparser-js-guessparams-L85-L92)

**Comment by h13i32maru** [comment]
@ipostol Thanks this bug report. 

@typhonrt Thanks gist code! Could you please send pull-request? Or I take your gist code into ESDoc.

**Comment by ipostol** [comment]
@h13i32maru 
@typhonrt 
Hello, today try use esdoc for new project and have next

http://prntscr.com/c3fa5d

class A {

  method({ value1, ...rest }) {
     console.log(value1, rest);
  }

}
When esdoc try proccess this code, he throw errors. He don`t like spread operator in function arguments.

If we try next code, all be ok. But use arrow functions in class methods not good idea if this don`t need for context, or something else. Or we add docs for this method like a https://github.com/esdoc/esdoc/issues/295#issuecomment-225066291

class A {

  method = ({ value1, ...rest }) => {
     console.log(value1, rest);
  };

}

This is something similar to the last problem, but maybe you do not know about it.

**Comment by typhonrt** [comment]
@ipostol please reopen #312 as this is a new issue though related to the same area of ESDoc as the issue here in #295. This is valid ES7 code. I have a [fork of ESDoc](https://github.com/typhonjs-node-esdoc/esdoc) that uses the Babylon AST parser and it can accept your first example:
```
class A {
  method({ value1, ...rest }) {
     console.log(value1, rest);
  }
}
```
but there needs to be a small mod even in my fork of ESDoc that picks up the RestPattern AST node properly. My fork will fail as well without a small modification. 

Without upgrading to ESDoc to Babylon there is no clear path to fix #312.

**Comment by ipostol** [comment]
@typhonrt Ok, thank for response, i am reopen https://github.com/esdoc/esdoc/issues/312

**Comment by h13i32maru** [comment]
Your codes works fine in my env. Please check latest ESDoc.

I re-open this issue if is problem.
