### ISSUE TITLE
Improved support for class fields and properties

### ISSUE THREAD

**Issue by MiracleBlue** [esdoc/esdoc#298]
Hey there, I've got a class that uses the ES7 Class Fields and Properties proposal (as outlined https://github.com/jeffmo/es-class-fields-and-static-properties)

I've noticed that some of my properties get recognised and added to the documentation, but some do not.  The ones that do get picked up are typically the uninitialised ones or ones with null, and the ones which are ignored are typically the ones with a default value assigned.

Example:

``` javascript
class Tracker {
    allowedLibraries = {
        'GTM': new GtmTracker(),
        'KISS': new KissTracker(),
        'Optimizely': new OptimizelyTracker()
    };

    eventQueueName = 'tracker_stuff';

    eventQueue = null;

    get queueLength() {
        return this.eventQueue.length;
    }
    // ... rest of code
}
```

Only two of these members appear in the docs:

<img width="310" alt="screen shot 2016-06-17 at 1 42 41 pm" src="https://cloud.githubusercontent.com/assets/23368/16140151/8b3778bc-3491-11e6-8e2b-6cac0301f36e.png">

I've got the esdoc-es7-plugin installed and added to my config.  Here are my installed versions:

```
"esdoc": "^0.4.7",
"esdoc-es7-plugin": "0.0.3",
```

**Comment by typhonrt** [comment]
The `esdoc-es7-plugin` just ignores ES7 syntax, but is also out of date, so it doesn't support anything related to ES7 as things go. 

I can't say this will help you, but I have a fork of ESDoc that supports Babylon for parsing with all Babylon plugins enabled by default [here](https://github.com/typhonjs-node-esdoc/esdoc). It's unpublished on NPM so you have to link to the Github repo. It would be interesting to see what the results would be with you example though.

**Comment by MiracleBlue** [comment]
Ah, good to know.  I may give your fork a try and see how it goes, thank you :)

**Comment by typhonrt** [comment]
Good news / bad news... Babylon can parse the code example you gave and here is the AST it generates: https://astexplorer.net/#/rcvKO9Ozbo

Bad news is that ClassProperty nodes which is what results / is new from your code example are not currently supported within ESDoc as that is Babylon AST spec. ESDoc is currently based on ESTree AST. Babylon AST more or less is a superset with additional changes for modern functionality.

ESDoc has been in a holding pattern for ~6 months while the maintainer works on other projects and he hasn't accepted outside collaborators.  I'm hesitant on moving it forward in my fork beyond what is still big merges upstream currently. I really don't want to run a separate maintained fork from ESDoc, but as the days drag on we'll see.

**Comment by MiracleBlue** [comment]
Ah man, that's unfortunate.  I've not yet found any alternatives that are as configurable as ESDoc and also support ES6/7.  I asked for suggestions on reddit but got no responses.  Thanks for your help, I'm sure I'll find some way to get there at some point.

**Comment by typhonrt** [comment]
I too favor the plugin / configuration options w/ ESDoc!

All hope is not lost per se as It should be possible to create an ESDoc plugin which parses the Babylon AST (in `onHandleAST`) and adds additional doc tags for "class properties as variables" (in `onHandleTags`). That is a plugin should be possible to be created before ESDoc officially supports all of Babylon AST internally. IE this would be a plugin for my fork of ESDoc until it upstreamed or the main distro of ESDoc supports Babylon seems to be a goal mentioned in #293 

The biggest slowdown is that the ESDoc maintainer is from Japan / communication challenges, so upstream progress has been very slow.

**Comment by MiracleBlue** [comment]
Yeah, I can imagine.  My japanese isn't all that good unfortunately.  I'll have to see if work will give me the time to work on this problem further.  I think, if we want these automated docs to happen, we might have to just do it.

**Comment by typhonrt** [comment]
Nice.. Yeah.. I've spent far longer (~4+ months) working on documentation efforts than I wanted to (gratis / open source), but the benefits are big when launching new efforts for others to consume ala [TyphonJS](https://typhonjs.io/). 

Speaking of automating I'll be releasing soonish an NPM module to use on CI (Travis) systems that on commit builds the docs and manages pushing the docs to a separate repo for all JS repos enabled by a user / organization on Github. Then a simple `git pull` on a web site updates all docs (this could be automated too!).

**Comment by MiracleBlue** [comment]
Just took a look at the AST output that you linked to, it appears it errors on the class property.  Unexpected token (2:21) :(

I wanna try and make some time to get class properties parsing, either by contributing to your fork or by doing the plugin way as you suggested.  I'll see what I can do.

**Comment by typhonrt** [comment]
Yeah.. That is a Babylon AST node & not ESTree...  Well. It's still possible to use the main ESDoc repo as you could get "sneaky" with a plugin. IE you could add babylon as a dependency for the plugin and in `onHandleCode` you could parse it and save the AST tree to consume and add extra tags during `onHandleTags` adding the ClassProperty node data to the variable / member data of the class. 

In my fork the AST is waiting there to be handled in `onHandleAST`, but the above trick is so close to being the same. I'd really like to upstream the babylon fork I have though. The Babylon AST is essentially a superset more or less of ESTree syntax.

**Comment by h13i32maru** [comment]
@MiracleBlue Latest ESDoc(v0.5) supports `Class Properties`. Please check it.

However, a little bug is exist in it. I fixed it in next version.
https://github.com/esdoc/esdoc/commit/5920c1f91633202ec795f360bb0ac12f68f258f2
