### ISSUE TITLE
Support @category tag

### ISSUE THREAD

**Issue by megawac** [esdoc/esdoc#299]
See https://github.com/ErnstHaagsman/jsdoc-plugins/blob/master/categories.md

**Comment by typhonrt** [comment]
I can't see this happening for ESDoc anytime soon unless you somehow make it happen and provide a PR. ;) You linked to a JSDoc plugin so as far as I'm aware @category is not a standard JSDoc tag. 

As far as the default left-hand navigation is concerned with ESDoc currently it is tied to the file / path structure.

**Comment by h13i32maru** [comment]
I don't have plan to support `@category`. Please categorize using directory name and file name.
