### ISSUE TITLE
Support functions made by factories

### ISSUE THREAD

**Issue by megawac** [esdoc/esdoc#300]
I've been trying to setup esdoc in asyncjs as part of https://github.com/caolan/async/pull/1191 but noticed an issue with documenting functions generated by other functions. [Example file](https://github.com/caolan/async/blob/master/lib/eachOf.js). In this file `doLimit` creates a wrapper function around `eachOfLimit`.
I was expecting adding a `@type Function` would do the trick and put the docs under the corresponding `@name`, however these functions have not been showing up in the generated output

**Comment by typhonrt** [comment]
@type is only picked up when documenting a member of a class as far as I'm aware. 

IE:
```
export default class Foo
{
   constructor()
   {
       /**
        * A crazy bar string...
        * @type {string}
        */
       this.bar = 'value';
   }
}
```

Even adding @returns to your example will not add a function to the docs per se. For the example supplied I suppose @returns may provide a variable entry into the docs?

**Comment by h13i32maru** [comment]
ESDoc does not support it. Because ESDoc generates doc from concrete codes. A Dynamically codes (aka meta programming) is not targeted of ESDoc.
