### ISSUE TITLE
Don't make @desc parse `.` characters

### ISSUE THREAD

**Issue by kdex** [esdoc/esdoc#304]
Periods are an integral part of many languages, and they're certainly not only used to mark the end of a sentence.

Thus, parsing sentences turns out to be non-trivial, as the character `"."` can also be part of abbreviations or even part of organization names or URLs. To solve this, one would usually need heavy Natural Language Processing, which is by far beyond the scope of this project.

[shorten(doc)](https://github.com/esdoc/esdoc/blob/832515ba2d7bf1535087620807a71e50e2a4fa93/src/Publisher/Builder/util.js#L36-L40)'s behavior currently breaks all descriptions that contain abbreviations, certain URLs or in general, periods that don't imply the end of a sentence. For example, consider:

```js
/**
* This class mainly retrieves media elements, e.g. images and videos.
*/
class Retriever {
    // …
}
```

whose description will be:

```js
"This class mainly retrieves media elements, e.g."
```

Note that there are certain kinds of abbreviations that even have a space in between the two parts. One example is `"et al."`, or the German `"z. B."`. There is no good fix for that; you'd have to use dictionaries to support them all.

So, could ESDoc please try to stop "guessing" what's a sentence? I hope you will agree that this problem is too hard to solve in a project that aims for simplicity.

If you want my opinion, the description should be whatever comes before the first `"\n"`; but that's just one alternative; feel free to suggest a better one.

Nevertheless, could we please get support for abbreviations?

**Comment by typhonrt** [comment]
This is kind of a non-issue. 

The only issue per se is adding documentation on the ESDoc web site / tutorials clearly stating that the description is limited by the first period / sentence and points out that the first word boundary ending with a period is parsed as the description.

If the ESDoc user understands this then documentation should be written accordingly.  

This: `This class mainly retrieves media elements, e.g. images and videos.`

becomes:
`This class mainly retrieves media elements, for instance: images and videos.`
or
`This class mainly retrieves media elements, IE images and videos.`

**Comment by kdex** [comment]
@typhonrt Requiring the first period to be a sentence delimiter is unintuitive. Why should such an obvious limitation to be enforced?

While `IE` is neither an abbreviation nor a word, the `for instance:` alternative does not solve the actual problem that `@desc` currently has.

Now that we're still in a position where `@desc`s exact behavior is undocumented, I think that this is a good chance for us to discuss whether or not it should try and guess what's a sentence and what's not.

It might also be a good idea to check how other documentation generators handle this case.

And again, one might argument that `\n` is just as natural for a delimiter and will make `@desc`'s implementation simpler.

**Comment by typhonrt** [comment]
>`Now that we're still in a position where @desc's exact behavior is undocumented`

It's just not documented well / clearly: https://esdoc.org/tags.html#-desc

The point of the auto-parsing is so @desc tag doesn't need to be used everywhere. 

---------

I can see a potential use case if an explicit @desc tag is used then the shortening / auto-parsing is disabled. That could be considered an enhancement and an actionable change.

---------

If this is an itch for you I've heard a PR soothes things.. ;)  While low hanging fruit per se it's way down the list of things TODO. Besides I'm not the maintainer.

**Comment by kdex** [comment]
Just to be on the same page, I wasn't suggesting that auto-parsing should be disabled completely. :smile: My only intention was to make @h13i32maru reconsider the current rules for `@desc`.

I'll try and work on a PR and might re-open this issue then. Thanks for your suggestions! :)
