### ISSUE TITLE
Documenting dynamically attached properties

### ISSUE THREAD

**Issue by damirka** [esdoc/esdoc#305]
Hello, is there a way to document dynamically attached properties of the class? Maybe there's a way with `@typedef` tag or any other?

Here's an example

``` JavaScript
// parent model, somehow takes data from redis hash and assigns
// selected data to current class
class Model {
  get hashName () {
    return null;
  }

  // data - taken from redis storage
  constructor (data) {
    // properties are different for every model 
    Object.assign(this, data);
  }
}

// takes json from cars storage
class Car extends Model {
  get hashName () {
    return 'cars';
  }
}

// ... more classes ...
```

**Comment by typhonrt** [comment]
Something like this could work. 

```
// parent model, somehow takes data from redis hash and assigns
// selected data to current class
class Model {
  /**
   * @returns {object}
   */
  get data() { return this.hashName ? this._data[this.hashName] : this._data; }

  /**
   * @returns {undefined}
   */
  get hashName () {
    return void 0;
  }

  // data - taken from redis storage
  constructor (data) {
    /**
     * properties are different for every model
     * @type {object}
     * @ignore
     */
    this._data = data;
  }
}

// takes json from cars storage
class Car extends Model {
  /**
   * @returns {{numAxles: number, numTires: number}}
   */
  get data() { return this._data[this.hashName]; }

  /**
   * @returns {string}
   */
  get hashName () { return 'car'; }
}

// ... more classes ...
```

**Comment by damirka** [comment]
Nice try @typhonrt

But in my case I need to access all the properties directly from the model instance. Parent constructor actually does something like:
```JavaScript
class SomeModel 
{
  static getById (id) {
     return new this(getDataFromRedis(id));
  }
  constructor (data) {
    for (let i in data) {
      Object.defineProperty(this, i, {
        get: () => { return data[i]; }
      });
    }
  }
}

let model = SomeModel.getById(1);
console.log(model.id, model.name);
```

Even if I mix our solutions I will have to implement `get data() {}` method in each child model. So nope, it's not the way I expect it to be.

What I'd like to see is something like this in class description:
```JavaScript
/**
 * @desc Some class
 * @property {number} SomeClass#id ...
 * @property {number} SomeClass.hashName
 */
```
It is the way it's done in PHPDoc for example.

There's something like this in JSDoc (look for `@member` tag in JSDoc guides). But JSDoc is weird and I prefer ESDoc as it fits my code better.

**Comment by typhonrt** [comment]
@damirka I'm trying to offer options that work now without mods to esdoc.. ;P

There is no way that I know off to otherwise document potential properties. You either need to document a getter `@returns` or a member variable via `@type`. Ideal... No.. works yes... Ugly.. yes..

```
// parent model, somehow takes data from redis hash and assigns
// selected data to current class
class Model {
  /**
   * Defines a generic model.
   * @param {object} data - taken from redis storage
   */
  constructor (data) {
     Object.assign(this, data);
  }
}

// takes json from cars storage
class Car extends Model {
  /**
   * @param {{numTires: number, numAxles: number}} data - from redis
   */
  constructor(data)
  {
     super(data);

     /**
      * @type {number} - number of tires.
      */
     this.numTires = super.numTires;

     /**
      * @type {number} - number of axles.
      */
     this.numAxles = super.numAxles; 
  }
}

// ... more classes ...
```

**Comment by damirka** [comment]
Thanks @typhonrt 
Same for me - no ideas except obvious ones. Actually I thought about making a type via `@typedef` tag with properties. `redisSomeModel` for example and do the double `@extends`. But it didn't seem to work. I'll try again later.

Anyway it's just a feature request. Even in JSDoc I can't do it easily.

**Comment by typhonrt** [comment]
@typedef is nasty IMHO at least how it appears in ESDoc as a duplicated entry in navigation. In the default navigation it'll really be awkward. It looks somewhat better with my enhanced navigation plugin, but still has a class / typedef entry for a particular file, so not ideal. Yep, I tried this too already and settled on the two examples I posted above as best w/ stock esdoc. 

Somewhat unrelated.. I'm getting closer and closer to just forging ahead w/ my esdoc fork which already supports babylon. The next major architectural goal is to replace all hard coded functionality w/ plugins for all core functionality. If a particular tag wasn't supported one could add additional processing via new plugin hooks.

**Comment by h13i32maru** [comment]
ESDoc does not support it. Because ESDoc generates doc from concrete codes. A Dynamically codes (aka meta programming) is not targeted of ESDoc.

However [Plugin API](https://esdoc.org/manual/advanced/api.html#plugin-feature) may help you.

A rough code:
`Foo.js`
```js
/**
 * this is Foo.
 * @dynamic {number} p1 - this is instance member
 */
export default class Foo{}
```

`esdoc.json`
```json
{
  "source": "./src",
  "destination": "./doc",
  "plugins": [
    {"name": "./dynamic-property-plugin.js"}
  ]
}
```

`dynamic-property-plugin.js`
```js
function supportDynamic(tag){
  const results = [];

  for (const item of tag.unknown) {
    if (item.tagName === '@dynamic') {
      const matched = item.tagValue.match(/^\{(.*?)\} ([\w0-9_]+) -?(.*)$/m);
      const type = matched[1];
      const name = matched[2];
      const desc = matched[3].trim();

      results.push({
        kind: 'member',
        name: name,
        memberof: tag.longname,
        static: false,
        longname:`${tag.longname}#${name}`,
        access: 'public',
        description: desc,
        lineNumber: tag.lineNumber,
        type: {types: [type]}
      });
    }
  }

  return results;
}

exports.onHandleTag = function(ev) {
  const tags = ev.data.tag;

  for (const tag of tags) {
    if (tag.kind === 'class') {
      const dynamicTags = supportDynamic(tag);
      ev.data.tag.push(...dynamicTags);
    }
  }
};
```
