### ISSUE TITLE
Support for the other type of comment markers

### ISSUE THREAD

**Issue by pizzafroide** [esdoc/esdoc#306]
It would be great if ESDoc could support `///` markers (and possibly `/*!`, and `//!`).

Also, when trying with the above code, we get an unwanted `<hr/>` tag.

```js
/*****************************************************************
 * But I think that's not as much important as my other request...
 *****************************************************************/
```

**Comment by typhonrt** [comment]
Again welcome, but this is a non-issue. If for whatever reason you feel the need to use alternative comment markers consider making a plugin that utilizes the `onHandleCode` callback which allows modification of source code before parsing / processing in ESDoc. 

Standard comment markers are well supported:
`/* ... */`
`//`

**Comment by pizzafroide** [comment]
OK, then. I'll do that. I think I'll use `onHandleAST` though; it seems easier.
