### ISSUE TITLE
Automatic detection of parameters type and default value

### ISSUE THREAD

**Issue by pizzafroide** [esdoc/esdoc#308]
When a function parameter is not documented, ESDoc automatically detects its type, whether or not it is optional, and its default value (if any). But, when the parameter is documented, ESDoc loses all these pieces of information, which all needs to be explicitly specified again.

For instance:
```js
export function test(param = 4) {}
```
ESDoc detects that:
- `param` is a number.
- `param` is optional.
- `param`'s default value is 4.

Which is just fine. Now, it would be nice if:
- ESDoc would detect the exact same things when using:
  - `@param param - description` or
  - `@param [param] - description` or
  - `@param [param=4] - description` or
  - `@param {number} param - description` or
  - `@param {number} [param] - description` or
  - `@param {number} [param=4] - description`,
- ESDoc would overwrite type or default value if specified, as in:
  - `@param {SomeType} param - description` or
  - `@param [param=SomeOtherDefaultValue] - description` or
  - `@param {SomeType} [param=SomeOtherDefaultValue] - description`.

**Comment by typhonrt** [comment]
@pizzafroide Welcome to the ESDoc community! Your enthusiasm at least has been noted by me, but consider that this is a duplicate / related issue to #305. If a user provides documentation in @param format that is considered as the authoritative source. If you are using a modern IDE and eslint, etc. then the mismatch of provided documentation to source code will trigger an error / warning.

**Comment by pizzafroide** [comment]
Thanks @typhonrt for your warm welcome! 

Actually, I don't see in what way this is related to #305. Maybe I misunderstood something... 

Anyways, I understand that it is a feature rather than a bug. I think that the fact that `@param` prevails on source code implies more efforts in maintaining the documentation because of duplicated information, though. But that's fine: I'll just write a plugin that completes `@param` information according to what is found in the source code.

**Comment by typhonrt** [comment]
Duplicate is a little strong per se, but related enhancement is about right for #305. You are right that a plugin would be the right way to approach automated param matching, but presently that might be a bit difficult to pull off in regard to the way plugin callbacks are structured. I'm not the ESDoc maintainer, so I can't say when / if said functionality will be available, but I'd like to see a large part of the hardcoded core functionality of ESDoc be exposed through additional plugin hooks which would make this kind of effort easier / possible to accomplish. Anything you might be able to pull on in a plugin now though would be instructive in the larger goal of realizing this kind of enhancement though. Good luck!
