### ISSUE TITLE
test.html not being generated

### ISSUE THREAD

**Issue by chrisabrams** [esdoc/esdoc#311]
I added

    "test": {
        "type": "mocha",
        "source": "./test"
     }

to the config file, which is adding "Test" to the navbar, but test.html is not being created.

**Comment by typhonrt** [comment]
It's a little non-obvious, but the default test includes regexp value for `config.test.includes` is `'(spec|Spec|test|Test)\\.(js|es6)$'` and for `config.test.excludes` is `'\\.config\\.(js|es6)$'`.  If you set `config.test.includes` to `'\\.js$'` then likely your tests will be picked up. 

The author of ESDoc takes a prescriptive viewpoint trying to enforce uniformity on codebases which you can see with his opinion of how the manual sections are hardcoded. This is similar with the default test regexp values; IE all tests should in in `Test.js`

Meh I don't exactly agree. The default test regex confused the heck out of me at the beginning too.

**Comment by chrisabrams** [comment]
@typhonrt that worked; thanks!
