### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by ipostol** [esdoc/esdoc#312]
Hello.

http://prntscr.com/c3fa5d

``` js
class A {

  method({ value1, ...rest }) {
     console.log(value1, rest);
  }

}
```

When esdoc try proccess this code, he throw errors. He don`t like spread operator in function arguments.

If we try next code, all be ok. But use arrow func in class methods not good idea if this don`t need for context, or some else.

``` js
class A {

  method = ({ value1, ...rest }) => {
     console.log(value1, rest);
  };

}
```

Thank for response.

**Comment by ipostol** [comment]
Find same problem in prev issue

**Comment by h13i32maru** [comment]
Your codes works fine in my env. Please check latest ESDoc and https://esdoc.org/manual/usage/feature.html#ecmascript-proposal

I re-open this issue if is problem.
