### ISSUE TITLE
document callback parameters?

### ISSUE THREAD

**Issue by clavecoder** [esdoc/esdoc#314]
I haven't seen a way to document callback parameters in esdoc. E.g.:

```javascript
/**
 * @param {function(!param1: number, param2: string): string} callback -
 *        How can I document `param1`, `param2` and callback result?
 */
export function(callback) { /* */ }
```

In object parameters you can document the object properties using dot notation. Is there a way to specify  the callback function parameters?

The only way I saw documented was to use a `@typedef` from #53 & #58. Is there a way to document them directly?

**Comment by typhonrt** [comment]
Welcome! This should answer your question. Check out the rest of the document for other info on how to handle tags for ESDoc. 

https://esdoc.org/tags.html#function

Please close this issue if this answers your question.

**Comment by clavecoder** [comment]
So the answer is no? If  you look at [tags#object] you will see that you can document the properties of an object parameter individually. So that **cannot** be done with the parameters of a callback parameter? See, for example, [Array#find] on MDN:

![image](https://cloud.githubusercontent.com/assets/3524633/17697355/0cc18a5a-637a-11e6-85f3-5b97475fbf27.png)


[tags#object]: https://esdoc.org/tags.html#object
[Array#find]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find

**Comment by clavecoder** [comment]
This is, apparently, how it's done with `jsdoc`:

![image](https://cloud.githubusercontent.com/assets/3524633/17697536/017f2430-637b-11e6-936e-1465b314aba1.png)

**Comment by typhonrt** [comment]
If the typedef approach isn't suitable then you can use markdown. 

```
/**
 * @param {function(element: *, index: number, array: Array<*>): boolean} callback - Function to execute on each value in the array, taking three arguments:
 * ```
 * element - The current element being processed in the array.
 * index - The index of the current element being processed in the array.
 * array - The array find was called upon.
 * ```
 * @param {!Object} thisArg - Optional. Object to use as this when executing callback.
 */
export default function find(callback, thisArg) { /* */ }
```

I use this approach for documenting object hashes with two or more levels deep as well as ESDoc doesn't support:

```
@param object - some hash
@param object.level1.level2 - some nested entry
```

**Comment by clavecoder** [comment]
I'm using the `@typedef` approach, but thanks for the tip. And, thanks for the welcome, too!
