### ISSUE TITLE
Support nested tests

### ISSUE THREAD

**Issue by ra100** [esdoc/esdoc#315]
When I use mocha tests with nested describe blocks like this

``` js
/** @test {myClass} */
describe('test myClass', () => {
  describe('test myClass subgroup', () => {
    /** @test {myClass#myFunction}*/
    it('should test myFunction', () => {
     //
    })
  })
})
```

Esdoc doesn't detect "it" block.

**Comment by Freezystem** [comment]
Actually the `@test` tag should only be used before `describe()` blocks. The parser will then automatically looks for the `it()` blocks within.

**Comment by ra100** [comment]
Ok, but when I tried to remove all comments before `it()` blocks and add comments before all `describe()` blocks, I was still not getting number and list of tests in docs.

**Comment by Freezystem** [comment]
Sounds like an export issue, your config file `esdoc.json` may be the cause. 
First name all your tests like so `<test-name>.specs.js` to allow the parser to find them using a simple regular expression.
Then add this to your esdoc config:
```json
{
  "source": "./app",
  "destination": "./docs",
  "test": {
    "type": "mocha",
    "source": "./test",
    "includes":["\\.specs\\."]
  }
}
```
Be sure all your tests are in the root folder under `/test` directory.
Try and tell me if it solve your problem.

**Comment by ra100** [comment]
Configuration is fine. Esdoc generates `test-file/...html` files. But for simple test it looks fine. Like:
```javascript
/** @test {Search} */
describe('(Route) Search', () => {
  let _route

  beforeEach(() => {
    _route = SearchRoute({})
  })

  it('should return a route configuration object', () => {
    expect(typeof(_route)).to.eql('object')
  })
  it('should containt path `search` in configuration', () => {
    expect(_route.path).to.eql('search')
  })
})
```
It show in list number of tests 2 and everything seems fine.
But, when I have something like this:
```javascript
/** @test {search} */
describe('(Redux) search', () => {
  describe('(Actions)', () => {
    it('should do something', () => {
    },
    it('should do something else', () => {
    }
  })
  describe('Other type of tests', () => {
    it('should do something', () => {
    },
})
```

Then it in the test table (docs/test.html) it show just something like this:

Description | Identifier | Count
------------|----------|-------
(Redux) search | \- 
(Redux) session | session

**Comment by Freezystem** [comment]
Actually you have to comment each `.describe()` function. like:
```js
/** @test {search} */
describe('(Redux) search', () => {
  /** @test {actions} */
  describe('(Actions)', () => {
    it('should do something', () => {
    },
    it('should do something else', () => {
    }
  })
  /** @test something with no ref */
  describe('Other type of tests', () => {
    it('should do something', () => {
    },
})
```

**Comment by ra100** [comment]
doen't seem to work as expected. But thanks for your time.

**Comment by Freezystem** [comment]
Maybe you can look at my code and figure out what doesn't work in your case.
My generated documentation is [here](https://freezystem.github.io/redux-app/test.html) and my test are [here](https://github.com/Freezystem/redux-app/blob/master/test/todos/components.specs.js)

**Comment by h13i32maru** [comment]
Please check latest version. I re-open this issue if is problem.
