### ISSUE TITLE
export default class without link

### ISSUE THREAD

**Issue by ElfenLiedGH** [esdoc/esdoc#321]
file : src/facades/selection

``` JavaScript
/**
 * Базовая выборка, автоматизирует CRUD-операции
 * {@link http://wiki.*****.ru/index.php/Selection_(базовая_выборка)}
 */
export default class Selection {
}
```

``` JavaScript
import Selection from 'src/facades/selection';
import squel from 'libs/squel';

/**
 * Выборка лицевых счетов
 * Лицевые счета +  Карточки регистрации + AddrLs_Table
 */
export default class ЛицевойСчет extends Selection {
   construcotor(){
      super()
   }
}
```

result:
![image](https://cloud.githubusercontent.com/assets/9973357/18002994/dbe33024-6b93-11e6-9a80-0bc21e8dfe0f.png)

![image](https://cloud.githubusercontent.com/assets/9973357/18002968/bac040f8-6b93-11e6-8487-4f91ae9f4cc6.png)

**Comment by typhonrt** [comment]
Use [@see](https://esdoc.org/tags.html#-see) for external links. `@link` is for internal links. Please close this issue if this solves your problem.

**Comment by ElfenLiedGH** [comment]
@typhonrt no, class Selection have not "Direct Subclass: ЛицевойСчет" & ЛицевойСчет have not "Extends: Selection"

**Comment by h13i32maru** [comment]
The your code works fine in my environemnt. Please check latest ESDoc.

I re-open this issue if is problem.
