### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined (DocBuilder.js)

### ISSUE THREAD

**Issue by bspies-work** [esdoc/esdoc#323]
I am unable to run "esdoc -c myconfig.json" on my project due to an error that occurs in DocBuilder (we are using ES 6 & 7 code--with JSX--so I am using the esdoc-es7-plugin, but this issue happens without configuring the plugin). Output is:
```
badge.svg
E:\Source\GIMLI\web\orion\orion-prep\node_modules\esdoc\out\src\Publisher\Builder\DocBuilder.js:483
            throw _iteratorError2;
            ^

TypeError: Cannot read property 'replace' of undefined
    at E:\Source\GIMLI\web\orion\orion-prep\node_modules\esdoc\out\src\Publisher\Builder\DocBuilder.js:955:32
    at Array.map (native)
    at IdentifiersDocBuilder._buildTypeDocLinkHTML (E:\Source\GIMLI\web\orion\orion-prep\node_modules\esdoc\out\src\Publisher\Builder\DocBuilder.js:950:43)
    at IdentifiersDocBuilder._buildSignatureHTML (E:\Source\GIMLI\web\orion\orion-prep\node_modules\esdoc\out\src\Publisher\Builder\DocBuilder.js:1231:38)
    at E:\Source\GIMLI\web\orion\orion-prep\node_modules\esdoc\out\src\Publisher\Builder\DocBuilder.js:512:38
    at IceCap.loop (E:\Source\GIMLI\web\orion\orion-prep\node_modules\ice-cap\out\src\IceCap.js:261:9)
    at IdentifiersDocBuilder._buildSummaryDoc (E:\Source\GIMLI\web\orion\orion-prep\node_modules\esdoc\out\src\Publisher\Builder\DocBuilder.js:509:11)
    at IdentifiersDocBuilder._buildSummaryHTML (E:\Source\GIMLI\web\orion\orion-prep\node_modules\esdoc\out\src\Publisher\Builder\DocBuilder.js:468:29)
    at IdentifiersDocBuilder._buildIdentifierDoc (E:\Source\GIMLI\web\orion\orion-prep\node_modules\esdoc\out\src\Publisher\Builder\IdentifiersDocBuilder.js:78:40)
    at IdentifiersDocBuilder.exec (E:\Source\GIMLI\web\orion\orion-prep\node_modules\esdoc\out\src\Publisher\Builder\IdentifiersDocBuilder.js:52:32)
```

If I insert this code before line 955:
```
if(typeof tmp[1]==="undefined") {
     console.log("tmp[1] is undefined");
} else { console.log(tmp[1]); }
```
I see output like:
```
string
Array
ReduxActionHandler
string
Array
tmp[1] is undefined
```

**Comment by typhonrt** [comment]
`esdoc-es7-plugin` is old and defunct plugin which doesn't support ES6+, but simply tries to avoid / reduce parsing errors.

A future update to ESDoc will support Babylon, but I have a fork of ESDoc now that has full Babylon support with all plugins enabled including JSX. You can read more about it in #292. Give my fork a try and perhaps drop a note in #292 if it works for your project.

**Comment by bspies-work** [comment]
Thanks for the suggestion. I tried your fork, but am still hitting the same issue.

**Comment by bspies-work** [comment]
If I look at the value prior to splitting on the colon (again with println debugging), I see:
```
Value of 'v' prior to split: mutationString: string
Value of 'v' prior to split:  mutationObjects: Array
Value of 'v' prior to split: reduxUpdate: ReduxActionHandler
Value of 'v' prior to split: queryString: string
Value of 'v' prior to split:  queryObjects: Array
Value of 'v' prior to split: *
```
I assume that it is not likely comments like the following:
```
/**
 * Get server path which is dependant on whether or not aliases
 * are specified for the namespace and operation.
 * @param parsedNamespace
 * @param parsedOperation
 * @returns {*}
 * @private
 */
```

**Comment by typhonrt** [comment]
It looks like the `@param` tags are not formatted correctly to include type information. 
https://esdoc.org/tags.html#-param
It should be `@param {object} parsedNamespace - description`. Of course fill in `{object}` with whatever type it should be. If you don't provide the type ESDoc will try and infer it (not as completely as possible).

That is not likely the problem, but worth trying out. In the code that is failing both sections where `tmp[1]` is preceded by the comment: `this is a bad hack`. It looks like you might have an object or function type information in docs incorrectly formatted somewhere.

As things go there are some "spartan" areas of ESDoc which can fail if the input doesn't match the expected formatting. The maintainer hasn't allowed outside collaborators, so movement is slow with ESDoc and it's a bummer more helpful error information isn't generated. 

While my babylon fork indeed works better than the current master ESDoc branch I haven't fixed problem areas that are inherent in ESDoc itself.

**Comment by bspies-work** [comment]
Well the code here is matching expressions like ``{ .* }`` and expects that the ``.*`` here is in the form paramName:type.  If you see the ``typeName`` variable before the split:
```
typeName: {*}
Value of 'v' prior to split: *
```

**Comment by bspies-work** [comment]
OK, got rid of those errors by removing all the ``@returns {*}`` that we had in our code. Would be nice to have a simple regex that validates if a tag is in the right format, though...

**Comment by typhonrt** [comment]
Better error reporting in general when ESDoc fails is pertinent. As things go something like that is a widespread change across the codebase versus a more contained PR and the single maintainer of ESDoc hasn't been too keen on making these kinds of changes. I suppose you can close this issue if you feel your problem has been resolved.
