### ISSUE TITLE
Documentation left menu navigation order

### ISSUE THREAD

**Issue by paulondc** [esdoc/esdoc#327]
Is there a way to control the order from which the documented categories are listed by the left menu ?

**Comment by typhonrt** [comment]
Not exactly. I do have a plugin that provides an enhanced left-hand side navigation solution; [esdoc-plugin-enhanced-navigation](https://www.npmjs.com/package/esdoc-plugin-enhanced-navigation). It essentially solves category issues. Let me know if it helps.

**Comment by paulondc** [comment]
@typhonrt thanks for you reply, I've looked at your suggestion, it does improve the navigation's interface, however I could not find a way to re-organize the categories. Am I missing something out ?

This is really fundamental in my case, since the most important categories are being listed at the bottom.

**Comment by typhonrt** [comment]
Yeah. Reorganizing the categories displayed for class, function, variable per file is not currently supported in the way that I think you are looking for... It's hard to say if this a legitimate feature request though such that if you are depending on many named exports for a given file and are mixing many functions with many variables for instance a potential solution is to split all named functions out to a separate file and all named variables to another. There are other solutions as well insofar as structuring fewer composite exports. 

At least in my coding style I only do one default export per file and the docs generated are really clear. With my plugin 'esdoc-plugin-enhanced-navigation' if all files in a given directory have just a single default export then that directory omits the file in the accordion. 

It is always possible to add ordering of identifier categories, but I assume this will be a very low priority feature enhancement. You might have to create your own plugin before anything official is released.

**Comment by paulondc** [comment]
Thanks for your reply, closing this ticket.
