### ISSUE TITLE
Class variable not getting documented

### ISSUE THREAD

**Issue by paulondc** [esdoc/esdoc#328]
ES6 does not allow class variables to be declared as part of the class declaration (which is odd). However it can be achieved by defining that later as the following example:

```es6
/**
* My Foo Class
*/ 
class Foo {
}

/**
* How to document me ?
*/ 
Foo.something = 10;
```

I wonder if there is a way to document that as part of the class members ?

**Comment by typhonrt** [comment]
This is an open area of discussion and further implementation. There are several other issues that bring up related functionality. #271 #318 relate to arrow functions, but there are other issues that bring up similar constraints. The crux of the matter currently is that ESDoc relies on explicit ES6 / ES module support for documentation generation. Any modification outside of the class definition to a class even in the same module / file is not currently picked up.

**Comment by paulondc** [comment]
Personally I don't like that I would be happy to be able to declare the static variables as part of the class declaration. But, due this limitation is about how javascript works, I think it would be a good a idea to support that special case. Since there is nothing fundamentally wrong with that.

**Comment by typhonrt** [comment]
`>Personally I don't like to be forced to declare the static variables outside of the class declaration I would be happy to be able to do it as part of the class declaration.`

ES7 class properties will be the way forward in that regard.

There are indeed several special cases that would be ideal to support. The main crux of the issue is that ESDoc currently works via explicit analysis of the generated AST versus providing introspection into the runtime execution. 

IE while unlikely to occur what if this happens:
```
/**
* My Foo Class
*/ 
class Foo {
}

/**
* How to document me ?
*/ 
Foo.something = 10; // It's a variable

Foo.something = () => {...};  // Now it's a function
```

**Comment by paulondc** [comment]
sure thing, I did not know that es7 would support that, I can live without support for that for now. Thanks.

**Comment by typhonrt** [comment]
Also looks like the maintainer of ESDoc has support for this in the forthcoming v1.0 version of ESDoc complete already if you look at the [release log](https://github.com/esdoc/esdoc/issues/293). It's in the [experimental section / class properties](http://babeljs.io/docs/plugins/#experimental)

**Comment by paulondc** [comment]
Thanks again @typhonrt. I'm looking forward for that version, do you know when that is gonna be landing ?

**Comment by typhonrt** [comment]
Hard to say, but I'd guess 1-2 months; most of the difficult work seems to be committed to the mainline repo, though non-released on NPM currently. In general communication concerns with the maintainer, @h13i32maru, being from Japan and not being able to regularly engage in contributing status updates in English and whatever external concerns he is dealing with has slightly obscured forward progress... I do hope to be able to be included as a collaborator post `v1.0` such that ESDoc may have firm forward progress into the future. I do try to help answer questions as best as I can as an "informed" external user / observer presently.

**Comment by paulondc** [comment]
Oh I see, thanks again.

**Comment by h13i32maru** [comment]
Please check latest ESDoc (v0.5)
