### ISSUE TITLE
Polymorphism documentation

### ISSUE THREAD

**Issue by paulondc** [esdoc/esdoc#329]
In reimplemented methods if none documentation is assigned to it could the doc for that be based in the parent class one (looking for it recursively)

Another option that would be simpler to implement compared with the suggestion above is to just have a way to tell esdoc where to find the documentation for the method then including that in the  generated documentation (Maybe there is already this feature ?)

Thanks

**Comment by typhonrt** [comment]
There is a section called "Inherited Summary". For an example see this [doc page](https://docs.typhonjs.io/typhonjs-backbone-parse/backbone-parse-es6/class/backbone-parse-es6/src/ParseModel.js~ParseModel.html) and scroll down to "Inherited Summary". 

Also in each overridden method there should be an automatic override link to the parent class. You can see that in the same example above for the [save method](https://docs.typhonjs.io/typhonjs-backbone-parse/backbone-parse-es6/class/backbone-parse-es6/src/ParseModel.js~ParseModel.html#instance-method-save) 

You can also manually use [@link](https://esdoc.org/tags.html#-link). In using the example above from anywhere in docs you could use `{@link Model#save}` to refer to the class & method.

I don't think ESDoc should automatically post the docs of the parent class for overridden methods as a new doc header for the overridden method should provide what is specific for the override then the override section will link to the parent class/method docs. 

If this answers your question please close this issue.

**Comment by paulondc** [comment]
Hi @typhonrt,

In your example about the save method, did you manually have duplicated the documentation across the re-implementation(s) ?

BTW I was aware about the `@link` tag, but that is not what I'm trying to achieve.

**Comment by typhonrt** [comment]
Alas in that case I did manually duplicate the documentation for the `save` method. In a future update of that repo I'll likely update the documentation to reflect the overridden behavior and refer to the parent class docs for examples. 

Since the override doc link is supplied automatically it's hard to say if your original suggestion above `looking for it [docs in parent class] recursively` would be accepted as an enhancement. This is just my opinion though. The ESDoc author may eventually weigh in.

**Comment by h13i32maru** [comment]
I supported to automatically take a description from super class method. And I will release in next version.
