### ISSUE TITLE
Access tag question

### ISSUE THREAD

**Issue by paulondc** [esdoc/esdoc#330]
I've noticed that if the access tag @protected is included at the begin of the documentation's scope, then the description about the method does not get included in the generated doc.

Does not work:

``` es6
class A {

    /**
    * @protected
    * The description about the protected method
    */
    _myProtectedMethod(){
        ...
    }
}
```

Works:

``` es6
class A {

    /**
    * The description about the protected method
    * @protected
    */
    _myProtectedMethod(){
        ...
    }
}
```

Is it supposed to work like that?

**Comment by typhonrt** [comment]
Yes. The first block of text is treated as the docs. Further tags will start different processing for example, heh, `@example` will create a code block. The way things work currently keeps things simpler when parsing documentation. 

If this answers your question please close this issue. Thanks.

**Comment by paulondc** [comment]
Fair enough, could it be at least documented ?

**Comment by h13i32maru** [comment]
Please check https://esdoc.org/manual/usage/tags.html#-desc

**Comment by bengotow** [comment]
(For what it's worth, the docs do not mention that the order is important - just ran into this one myself.)
