### ISSUE TITLE
It doesn't render all the classes

### ISSUE THREAD

**Issue by jkomyno** [esdoc/esdoc#331]
The overall output and the formatting of esdoc is really better than docco/jsdoc in my option, however I'm having issues with some of my react components.
It displays about the half of this components. I don't use ES7 and I don't see errors during the building process. 
Also, the coverage is stuck at 1.33% from yesterday despite the fact that I have added many esdoc-formatted comments.

Here's the log that I get:

> Euclide@0.0.0 esdoc C:\Users\PC\Desktop\User\client
> esdoc -c esdoc.json

badge.svg
identifiers.html
index.html
class/client/components/Console/Console.js~Console.html
class/client/components/Dashboard/Dashboard.js~Dashboard.html
class/client/components/DashboardComponentHeader/DashboardComponentHeader.js~DashboardComponentHeader.html
class/client/components/DashboardComponentWrapper/DashboardComponentWrapper.js~DashboardComponentWrapper.html
class/client/components/Datatable/Datatable.js~Datatable.html
class/client/components/ErrorView/ErrorView.js~ErrorView.html
class/client/components/Footer/Footer.js~Footer.html
class/client/components/FormGroup/FormGroup.js~FormGroup.html
class/client/components/FormHeader/FormHeader.js~FormHeader.html
class/client/components/Home/Home.js~Home.html
class/client/components/Loader/Loader.js~Loader.html
class/client/components/MainBlockSingle/MainBlockSingle.js~MainBlockSingle.html
class/client/components/ModalWrapper/ModalWrapper.js~ModalWrapper.html
class/client/components/NetworkCard/NetworkCard.js~NetworkCard.html
class/client/components/NetworkRow/NetworkRow.js~NetworkRow.html
class/client/components/PieChart/PieChart.js~PieChart.html
class/client/components/PieChartCard/PieChartCard.js~PieChartCard.html
class/client/components/Root/Root.js~Root.html
class/client/components/ShowParametersList/ShowParametersList.js~ShowParametersList.html
class/client/components/SortableDataTable/SortableDataTable.js~SortableDataTable.html
class/client/components/SortableDataTableSmall/SortableDataTableSmall.js~SortableDataTableSmall.html
class/client/components/SuccessMessage/SuccessMessage.js~SuccessMessage.html
function/index.html
variable/index.html
file/client/actions/index.js.html
file/client/actions/types.js.html
file/client/components/App/App.js.html
file/client/components/App/index.js.html
file/client/components/App/metisMinHeight.js.html
file/client/components/ConfigureHostname/ConfigureHostname.js.html
file/client/components/ConfigureHostname/index.js.html
file/client/components/ConfigureNetwork/ConfigureNetwork.js.html
file/client/components/ConfigureNetwork/index.js.html
file/client/components/Console/Console.js.html
file/client/components/Console/index.js.html
file/client/components/Dashboard/Dashboard.js.html
file/client/components/Dashboard/index.js.html
file/client/components/DashboardComponentHeader/DashboardComponentHeader.js.html
file/client/components/DashboardComponentHeader/index.js.html
file/client/components/DashboardComponentWrapper/DashboardComponentWrapper.js.html
file/client/components/DashboardComponentWrapper/index.js.html
file/client/components/Datatable/Datatable.js.html
file/client/components/Datatable/index.js.html
file/client/components/DropCard/DropCard.js.html
file/client/components/DropCard/index.js.html
file/client/components/ErrorView/ErrorView.js.html
file/client/components/ErrorView/index.js.html
file/client/components/Footer/Footer.js.html
file/client/components/Footer/index.js.html
file/client/components/FormGroup/FormGroup.js.html
file/client/components/FormGroup/index.js.html
file/client/components/FormHeader/FormHeader.js.html
file/client/components/FormHeader/index.js.html
file/client/components/Home/Home.js.html
file/client/components/Home/Home.test.js.html
file/client/components/Home/index.js.html
file/client/components/Loader/Loader.js.html
file/client/components/Loader/index.js.html
file/client/components/MainBlockSingle/MainBlockSingle.js.html
file/client/components/MainBlockSingle/index.js.html
file/client/components/MainBlocks/MainBlocks.js.html
file/client/components/MainBlocks/index.js.html
file/client/components/Menu/Menu.js.html
file/client/components/Menu/index.js.html
file/client/components/ModalWrapper/ModalWrapper.js.html
file/client/components/ModalWrapper/index.js.html
file/client/components/NetworkCard/NetworkCard.js.html
file/client/components/NetworkCard/index.js.html
file/client/components/NetworkRow/NetworkRow.js.html
file/client/components/NetworkRow/index.js.html
file/client/components/NotFound/NotFound.js.html
file/client/components/NotFound/NotFound.test.js.html
file/client/components/NotFound/index.js.html
file/client/components/NotificationsPanel/NotificationsPanel.js.html
file/client/components/NotificationsPanel/index.js.html
file/client/components/PieChart/PieChart.js.html
file/client/components/PieChart/index.js.html
file/client/components/PieChartCard/PieChartCard.js.html
file/client/components/PieChartCard/index.js.html
file/client/components/PingCard/PingCard.js.html
file/client/components/PingCard/index.js.html
file/client/components/Root/Root.js.html
file/client/components/Root/Root.test.js.html
file/client/components/Root/index.js.html
file/client/components/SearchBar/SearchBar.js.html
file/client/components/SearchBar/index.js.html
file/client/components/SetLdapParameters/SetLdapParameters.js.html
file/client/components/SetLdapParameters/index.js.html
file/client/components/SetMailParameters/SetMailParameters.js.html
file/client/components/SetMailParameters/index.js.html
file/client/components/SetMainParameters/SetMainParameters.js.html
file/client/components/SetMainParameters/index.js.html
file/client/components/SetNetflowParameters/SetNetflowParameters.js.html
file/client/components/SetNetflowParameters/index.js.html
file/client/components/SetNetworksParameters/SetNetworksParameters-OLD.js.html
file/client/components/SetNetworksParameters/SetNetworksParameters.js.html
file/client/components/SetNetworksParameters/index.js.html
file/client/components/SetSnmpParameters/SetSnmpParameters.js.html
file/client/components/SetSnmpParameters/index.js.html
file/client/components/SetWmiParameters/SetWmiParameters.js.html
file/client/components/SetWmiParameters/index.js.html
file/client/components/ShowInitParametersList/ShowInitParametersList.js.html
file/client/components/ShowInitParametersList/index.js.html
file/client/components/ShowLdapParametersList/ShowLdapParametersList.js.html
file/client/components/ShowLdapParametersList/index.js.html
file/client/components/ShowMailParametersList/ShowMailParametersList.js.html
file/client/components/ShowMailParametersList/index.js.html
file/client/components/ShowNetflowParametersList/ShowNetflowParametersList.js.html
file/client/components/ShowNetflowParametersList/index.js.html
file/client/components/ShowNetworksParametersList/ShowNetworksParametersList.js.html
file/client/components/ShowNetworksParametersList/index.js.html
file/client/components/ShowParameters/ShowParameters.js.html
file/client/components/ShowParameters/index.js.html
file/client/components/ShowParametersList/ShowParametersList.js.html
file/client/components/ShowParametersList/index.js.html
file/client/components/ShowProbeSystemNetworksParametersList/ShowProbeSystemNetworksParametersList.js.html
file/client/components/ShowProbeSystemNetworksParametersList/index.js.html
file/client/components/ShowProbeSystemParameters/ShowProbeSystemParameters.js.html
file/client/components/ShowProbeSystemParameters/index.js.html
file/client/components/ShowSnmpParametersList/ShowSnmpParametersList.js.html
file/client/components/ShowSnmpParametersList/index.js.html
file/client/components/ShowWmiParametersList/ShowWmiParametersList.js.html
file/client/components/ShowWmiParametersList/index.js.html
file/client/components/SortableDataTable/SortableDataTable.js.html
file/client/components/SortableDataTable/index.js.html
file/client/components/SortableDataTableSmall/SortableDataTableSmall.js.html
file/client/components/SortableDataTableSmall/index.js.html
file/client/components/SortableListContainer/SortableListContainer.js.html
file/client/components/SortableListContainer/index.js.html
file/client/components/SuccessMessage/SuccessMessage.js.html
file/client/components/SuccessMessage/index.js.html
file/client/configureStore.js.html
file/client/index.js.html
file/client/reducers/appState.js.html
file/client/reducers/appState.test.js.html
file/client/reducers/checkLdapParametersReducer.js.html
file/client/reducers/checkMailParametersReducer.js.html
file/client/reducers/checkNetworksListParametersReducer.js.html
file/client/reducers/checkPingReachability.js.html
file/client/reducers/errorViewReducer.js.html
file/client/reducers/fetchEuclideApplReducer.js.html
file/client/reducers/fetchLdapBasesReducer.js.html
file/client/reducers/fetchLdapDomainsReducer.js.html
file/client/reducers/fetchLdapNameReducer.js.html
file/client/reducers/fetchLdapPasswordReducer.js.html
file/client/reducers/fetchLdapPortReducer.js.html
file/client/reducers/fetchMailAuthReducer.js.html
file/client/reducers/fetchMailFromReducer.js.html
file/client/reducers/fetchMailNameReducer.js.html
file/client/reducers/fetchMailPasswordReducer.js.html
file/client/reducers/fetchMailTohReducer.js.html
file/client/reducers/fetchMailUsernameReducer.js.html
file/client/reducers/fetchNetflowNameReducer.js.html
file/client/reducers/fetchNetworksRangeReducer.js.html
file/client/reducers/fetchProbeIdReducer.js.html
file/client/reducers/fetchProbeKeyReducer.js.html
file/client/reducers/fetchProbeSystemNetworksParametersReducer.js.html
file/client/reducers/fetchSiteIdReducer.js.html
file/client/reducers/fetchSiteNameReducer.js.html
file/client/reducers/fetchSnmpCommunityReducer.js.html
file/client/reducers/fetchSnmpVersionReducer.js.html
file/client/reducers/fetchSystemHostname.js.html
file/client/reducers/fetchSystemHostnameReducer.js.html
file/client/reducers/fetchWmiPasswordReducer.js.html
file/client/reducers/fetchWmiPortReducer.js.html
file/client/reducers/fetchWmiServerReducer.js.html
file/client/reducers/fetchWmiUsernameReducer.js.html
file/client/reducers/index.js.html
file/client/reducers/index.test.js.html
file/client/reducers/modalReducer.js.html
file/client/reducers/modalSuccessReducer.js.html
file/client/reducers/notificationsReducer.js.html
file/client/reducers/pingComponentReducer.js.html
file/client/reducers/setEuclideApplReducer.js.html
file/client/reducers/setLdapBasesReducer.js.html
file/client/reducers/setLdapDomainsReducer.js.html
file/client/reducers/setLdapNameReducer.js.html
file/client/reducers/setLdapPasswordReducer.js.html
file/client/reducers/setLdapPortReducer.js.html
file/client/reducers/setMailAuthReducer.js.html
file/client/reducers/setMailFromReducer.js.html
file/client/reducers/setMailNameReducer.js.html
file/client/reducers/setMailPasswordReducer.js.html
file/client/reducers/setMailTohReducer.js.html
file/client/reducers/setMailUsernameReducer.js.html
file/client/reducers/setMainParameters.js.html
file/client/reducers/setNetflowNameReducer.js.html
file/client/reducers/setNetworksRangeReducer.js.html
file/client/reducers/setProbeIdReducer.js.html
file/client/reducers/setProbeKeyReducer.js.html
file/client/reducers/setSiteIdReducer.js.html
file/client/reducers/setSiteNameReducer.js.html
file/client/reducers/setSnmpCommunityReducer.js.html
file/client/reducers/setSnmpVersionReducer.js.html
file/client/reducers/setSystemHostnameReducer.js.html
file/client/reducers/setSystemNetworksReducer.js.html
file/client/reducers/setWmiPasswordReducer.js.html
file/client/reducers/setWmiPortReducer.js.html
file/client/reducers/setWmiServerReducer.js.html
file/client/reducers/setWmiUsernameReducer.js.html
file/client/reducers/sortableDataTableReducer.js.html
file/client/routes.js.html
file/client/utils.js.html
./css
./script
./image
script/search_index.js
source.html
==================================
Coverage: 1.33% (7/525)
==================================

And here's my esdoc.json:

{
	"source": "./client",
	"destination": "./esdoc"
}

**Comment by typhonrt** [comment]
Until ESDoc v1.0 is released you can give [my fork a try](https://github.com/esdoc/esdoc/issues/292). My fork uses Babylon as the AST parser (as will the forthcoming official v1.0 release). It is considerably more tolerant for an ES6+ code base. The current released version of ESDoc has outdated dependencies on several fronts. 

If by chance my fork solves your problem then do consider being an early tester of ESDoc v1.0 to make sure it also works. Consider closing this issue if that is the case too!

**Comment by jkomyno** [comment]
Hey man thanks for the fast reply. I'll give it a try in say 8 hours, when I'll get back to work.

**Comment by jkomyno** [comment]
Same issue with your fork @typhonrt, sorry. It doesn't find formatted comments in componets with names like "SetMainParameters", "SetMailParameters", "SetNetworkParameters" etc

**Comment by typhonrt** [comment]
Can you possibly provide a reasonable snippet of code below or a repo to look at?

**Comment by jkomyno** [comment]
Yup. Here's the gist with a couple of components and my esdoc.json:

https://gist.github.com/jkomyno/6af121d4b79dbb984c60c32f98394462

**Comment by typhonrt** [comment]
Offhand without testing anything is it the methods with `@param` which are not showing up? ESDoc as things go has somewhat fragile regex parsing. See the docs for [@param](https://esdoc.org/tags.html#-param). 

Instead of... 
```
/**
   * Binds to this every method of the class
   * @param {Object} [name="props"] - props passed to the component
   */
```

It should be...
```
/**
   * Binds to this every method of the class
   * @param {Object} props - props passed to the component
   */
```

IE remove the brackets and `name=""`.

**Comment by jkomyno** [comment]
Nothing changes. Actually that `[name="props"]` stuff was a misprint of mine, due to the fact that I also tried another js doc generator after esdoc, and I still had a couple of modules with a non-esdoc-formatted syntax. However, after having corrected that, nothing changes. I also tried applying the ES7 plugin (even though I use ES6 ), but with no result.

**Comment by h13i32maru** [comment]
> https://gist.github.com/jkomyno/6af121d4b79dbb984c60c32f98394462

`SetSnmpParameters` is not exported. ESDoc outputs only exported identifiers. If you want to change this behavior, you can use `config. unexportIdentifier = true`. More document is [here](https://esdoc.org/config.html)

```js
// this is not exported.
class SetSnmpParameters extends React.Component { ... }

// this is exported.
export class SetSnmpParameters extends React.Component {...}
```

**Comment by jkomyno** [comment]
Thanks, I'll try tomorrow. I thought the export default at the end of the class was enough

**Comment by jkomyno** [comment]
Yeah it works, thanks a lot!

**Comment by typhonrt** [comment]
Dang I should have seen / asked that re: "unexportIdentifier" in config. @jkomyno please consider closing the issue at this point. Welcome to ESDoc!

**Comment by jkomyno** [comment]
To everyone who may have the same problem using Redux's MapStateToProps or MapActionsToProps with {connect} provided by [react-redux](https://github.com/reactjs/react-redux): if you're going to use ESDoc, you must add the "export" keyword just besides the class declaration. Otherways, with the export default only at the end of the class declaration, ESDoc won't work, because it doesn't recognize the original class.

@h13i32maru, I suppose a small warning regarding this fact may be added to the README.md or to the official docs, do you agree?
