### ISSUE TITLE
The @namespace seems to be ignored

### ISSUE THREAD

**Issue by Karolusrex** [esdoc/esdoc#333]
In order to generate docs for nested objects I do the following, but the nested object is not outputted in the final html:

```javascript
/**
 * An object containing some things
 * @namespace myNamespace
 */
export const object = {

    /**
     * This is ignored by ESdoc
     * @memberof myNamespace
     */
    innerthing: function() {
        console.log("Hello world")
    }

};
```

**Comment by typhonrt** [comment]
Use [@type / @property](https://esdoc.org/tags.html#-type) and the [object type syntax](https://esdoc.org/tags.html#type-syntax).

```
/**
 * An object containing some things
 * @type {Object}
 * @property {function} object.innerthing - An inner thing!
 */
export const object = {
    innerthing: function() {
        console.log("Hello world")
    }
};
```

If this answers your question please close this issue. Thanks!

**Comment by Karolusrex** [comment]
Ah! that is nice, but not exactly what I'm looking for. I would preferably be able to declare parameters of that functions, e.g. (doesn't work)

```javascript
/**
 * An object containing some things
 * @type {Object}
 * @property {function} object.innerthing - An inner thing!
* @param {String} name A string that describes the name
 */
export const object = {
    innerthing: function(name) {
        console.log("Hello " + name)
    }
};

```

**Comment by typhonrt** [comment]
Check out the full [function identifier](https://esdoc.org/tags.html#function).
```
/**
 * An object containing some things
 * @type {Object}
 * @property {function(name: string)} object.innerthing - An inner thing!
 */
export const object = {
    innerthing: function(name) {
        console.log("Hello " + name)
    }
};
```

If that fails what I do in this case is use markdown. 
```
/**
 * An object containing some things
 * @type {Object}
 * @property {function(name: string)} object.innerthing - An inner thing with params:
 * ```
 * {string} name - A string that describes the name.
 * ```
 */
export const object = {
    innerthing: function(name) {
        console.log("Hello " + name)
    }
};
```

I'm giving the example clips above without testing w/ ESDoc, but that should give a few more directions to try.

**Comment by Karolusrex** [comment]
Still not satisfied because it's not consistent with other functions in the docs. I wrote a plugin that creates a function called 'object.innerthing' and puts it in the docs next to the other ones. This solved the problem in a way I wanted it. I can share with others, if interested.

Karl

**Comment by steezeburger** [comment]
I have utility files in a `utils/` directory that have several exported methods each and I'd love to be able to namespace them instead of them all falling under my `utils/` directory. Is this not possible?

**Comment by typhonrt** [comment]
@steezeburger while not the same exact case as described in this issue for your particular use case I do have an ESDoc plugin, [esdoc-plugin-enhanced-navigation](https://www.npmjs.com/package/esdoc-plugin-enhanced-navigation) which provides a significantly enhanced left side navigation. When there are multiple exports from any file in a directory it will group those doc identifiers under the file from where they originate.

**Comment by steezeburger** [comment]
That is _exactly_ what I needed! Thanks!

**Comment by h13i32maru** [comment]
Thanks all.
