### ISSUE TITLE
Way to input a custom text to @link

### ISSUE THREAD

**Issue by paulondc** [esdoc/esdoc#334]
I've been using the `@link` tag all over my documentation, however the most common issue about that tag is when there is a pluralization case in the documentation where currently there is no way to specify a custom text for the link. In order to workaround this limitation it would be nice to have a way to define an optional display text for the link, for instance: `{@link Foo DisplayText}`

**Comment by h13i32maru** [comment]
Thanks for this proposal. I will consider it.

**Comment by h13i32maru** [comment]
I does not support to anchor text for `@link`. However I will support anchor text for `@see` in next version. Please check https://github.com/esdoc/esdoc/issues/367
