### ISSUE TITLE
Report broken links

### ISSUE THREAD

**Issue by paulondc** [esdoc/esdoc#335]
Currently if a link is not found `{@link MyClass.methodRenamed}` while building the docs it's not reporting that as a problem, instead it silently skips the link creation. 

Could it print out an error message for each of the broken links ? (as it does when the function signature is different from the documented one)

**Comment by paulondc** [comment]
The same above for the `@see` tag as well

**Comment by h13i32maru** [comment]
A link to instance method is `{@link MyClass#method}`. `{@link MyClass.method}` is static method format. Please check https://esdoc.org/manual/usage/tags.html#identifier-syntax

I re-open this if is problem.
