### ISSUE TITLE
`@see {@link [link_url] | [link_name]} for [purpose]` JSDoc syntax not support

### ISSUE THREAD

**Issue by Manuel-Manoury** [esdoc/esdoc#337]
Hi !

During my work I found out that the following syntax is not properly rendered by ESDoc:
```
/**
 * @see {@link [link_url]|[link_name]} for [some purpose]
 */
```
is not properly rendered, despite being an "officially supported" JSDoc syntax (see [JSDoc @see](http://usejsdoc.org/tags-see.html) for examples / reference)

**Comment by typhonrt** [comment]
ESDoc doesn't exactly follow JSDoc syntax per se. See the [docs](https://esdoc.org/tags.html#-link) for what `@link` and `@see` does. `@link` is for internal document identifiers and `@see` only takes an URL argument for external linking. See #334 for a request for adding a way to provide a custom name for `@link`.

**Comment by Manuel-Manoury** [comment]
My bad, not yet used to refer to ESDoc documentation instead of the JSDoc one, thanks for your feedback. :)

**Comment by typhonrt** [comment]
Welcome to ESDoc nonetheless! :D

**Comment by Manuel-Manoury** [comment]
Thanks, I already enjoy it, great job ;D

**Comment by h13i32maru** [comment]
see https://github.com/esdoc/esdoc/issues/367
