### ISSUE TITLE
@see tag limited behavior 

### ISSUE THREAD

**Issue by paulondc** [esdoc/esdoc#338]
Since the `@see` tag is about supplying references for the documented scope I would expect that to be able to point to classes and methods that are defined inside of the documentation, currently it only works with external links.

Both `@see` and `@link` tags should support the same features where the difference between them is just about how they get rendered.

Further information:
[see](http://docs.oracle.com/javase/7/docs/technotes/tools/windows/javadoc.html#see)
[link](http://docs.oracle.com/javase/7/docs/technotes/tools/windows/javadoc.html#link)

**Comment by h13i32maru** [comment]
I don't support it. However If you want to use documentation link by `@see`, you can write the url.

```
@see class/MyClass.js~MyClass
```

And check https://github.com/esdoc/esdoc/issues/367
