### ISSUE TITLE
Improve display of .MD files

### ISSUE THREAD

**Issue by paulondc** [esdoc/esdoc#339]
Currently when reading the README.MD that gets included as HOME in the documentation it's not displaying it with a limit for the maximum width as Github and NPM do, instead the contents use the whole available width which makes inconvenient when reading long paragraphs.

BTW most websites do restrict the maximum width these days due high resolutions, could you consider to apply the max width for the entire doc ? (not only when displaying .md's)

Cheers

**Comment by typhonrt** [comment]
Duly noted.. Sounds good to me. I just haven't had time to look at this in particular, but it should be relatively easy to find out which CSS directive needs to be overridden. With a little snooping it should be possible to verify / modify this constraint via the [styles](https://esdoc.org/config.html) config parameter which provides a CSS style override.

**Comment by paulondc** [comment]
Cool, thanks @typhonrt for looking into it

**Comment by h13i32maru** [comment]
@paulondc  Please check [here](https://esdoc.org/manual/advanced/api.html#style-sheets-and-scripts).

I re-open this if is problem.
