### ISSUE TITLE
Is it possible to flag a file so that it is getting ignored?

### ISSUE THREAD

**Issue by maluramichael** [esdoc/esdoc#341]
I want to add a 'flag' at the top of the file so it does not getting processed. My file just import and exports some stuff and do not need to be documented. This is an index.js file in a directory so i just need to do `import {Api} from './core/api';`

```javascript
import Api from './api';
import ApiProvider from './apiProvider';

export {Api, ApiProvider}
```

**Comment by typhonrt** [comment]
You might try the `@ignore` tag...

```
import Api from './api';
import ApiProvider from './apiProvider';

/**
 * @ignore
 */
export {Api, ApiProvider}
```

A more complicated / potentially invasive way is via the `includes / excludes` regex in the [config file](https://esdoc.org/config.html). 

Welcome to ESDoc! If this answers your question then please close this issue.

**Comment by maluramichael** [comment]
@typhonrt thank you
