### ISSUE TITLE
Standardize OR operator

### ISSUE THREAD

**Issue by paulondc** [esdoc/esdoc#343]
Currently there are two ways to represent the same operator that is used to separate the data types. They seem to be used for different cases which creates an unnecessary complication.

The examples bellow were extracted from the online documentation (https://esdoc.org/tags.html):

***Union*** (|)
```es6
/**
 * @param {number|string} param - this is union param.
 */
function myFunc(param){...}
```

***Generics*** (,)

```es6
...

/**
 * @return {Promise<string[], MyError>} this is Promise return value.
 */
function myFunc(){...}
```

Cheers

**Comment by typhonrt** [comment]
They are not the same... Type Union !== Generics / Type Application. There is plenty of references out there from JSDoc which derives this functionality from the closure compiler ([1](https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#type-application) / [2]
(https://github.com/google/closure-compiler/wiki/Generic-Types)) to confirm. 

A type union is equivalent to OR and specifies a single placeholder. Generics is like filling in a template. For instance `Map<string, number>` doesn't mean string or number it means the key is a string and the value is a number. Likewise the the Promise example doesn't mean string[] or MyError that is interchangeable as it means when resolved a string[] is returned and on rejection MyError is returned.

This is a superfluous issue and since the ESDoc maintainer doesn't close issues quickly I recommend that you self-close it once you are convinced.

**Comment by paulondc** [comment]
Hi @typhonrt,

Thanks for clarifying it for me, I'm not familiar with jsdoc/clousure compiler.

For instance, in case the promise returns two different data types, then it would be something along these lines ?: 
```
* @return {Promise<string|null, MyError>} 
```

Cheers

**Comment by typhonrt** [comment]
Well the generics syntax that ESDoc is derived from currently shares the JSDoc / closure compiler spec approach which is a limited form of generics; kind of like Java generics. I suppose an interesting tidbit is that Java doesn't support union types with a caveat that something like themcan be used in try/catch blocks Java 7+. 

There is no hard and fast rule per se as this is all for type inference purposes in documentation generation and of course is useful in IDEs like [WebStorm](https://blog.jetbrains.com/webide/2012/10/validating-javascript-code-with-jsdoc-types-annotations/). 

If you try `@return {Promise<string|null, MyError>}` ESDoc won't parse or match `string|null` to any built in external or defined type. IMHO, as things evolve though especially with IDE support there is no reason to not expand what ESDoc supports as well. 

On the other hand TypeScript expands on what is possible in implementation and likely for documentation purposes, but currently is beyond the scope of ESDoc. It appears type unions w/ generics from the implementation angle was recently added to TypeScript: `https://github.com/Microsoft/TypeScript/issues/2576`

**Comment by paulondc** [comment]
Thanks again for your reply. I did not know about TypeScript, it seems a must have for javascript. Do you have any suggestions about which docgen I should use to work with TS ?

Cheers

**Comment by typhonrt** [comment]
I have no idea which is a good solution, Google is your friend.. Seems like this has a lot of traction: https://www.npmjs.com/package/typedoc

I wouldn't go as far as saying "it's a must". Modern vanilla ES6+ JS is quite powerful and w/ TS an additional layer of complexity in dev tools is added in general.

**Comment by paulondc** [comment]
I just find myself adding asserts all the time to make sure parameters got the right type because I've an issue with dynamic typing, since it's just a layer on the top of javascript rather than being a complete new language I think it's worth to use that.

Thanks for the suggestion about typedoc (I found that project on google as well, I wanted to make sure that one was the recommended one).

**Comment by typhonrt** [comment]
Yeah.. Go for it / TypeScript if you think it will help. I've personally been fine with the type inference of IDEs (WebStorm) via good documentation, and ESLint. I'm just a big fan of vanilla ES6+. From what I'm reading though there aren't great options for TypeScript documentation and there are several serious projects like RxJS which are using ESDoc and dealing with the fact that not everything is being picked up by ESDoc.

**Comment by h13i32maru** [comment]
@typhonrt thanks for reply.

@paulondc If you want to use a union in a generics, you can use `@typedef`.

```js
/**
 * @typedef {string|null} MyType
 */

/**
 * @return {Promise<MyType, MyError>}
 */
function foo(){...}
```
