### ISSUE TITLE
Feature Request: Support multiple versions

### ISSUE THREAD

**Issue by jukkah** [esdoc/esdoc#348]
I can't find any discussion about supporting multiple documentation versions. :confused: It would be great if we are not forced to override documentations of older versions when generating new one.

My proposal:
- Compile documentation in one level deeper in the file system (e.g. `docs/v1.0` instead of `docs`).
- Add a new command line option to specify the directory name (e.g. `esdoc -c esdoc.json -v v1.0`.
- As an alternative: add a new key in `esdoc.json` that tells how to resolve the version read from `package.json` (e.g. `"versions": "major"`). Procedure: ESDoc reads the package version from `package.json` and convert it to major version and generate documentations into `docs/v1`, `docs/v2`, `docs/v3`, ...
- Add somewhere in UI a version chooser that lists all directories in `docs` and make one of them (latest?) the default one. For example, Read the Docs does it like bellow:

![screenshot from 2016-11-02 13 47 51](https://cloud.githubusercontent.com/assets/1504091/19927602/1c068724-a103-11e6-93ab-1a78283e3566.png)

**Comment by typhonrt** [comment]
I'm not the maintainer, but IMHO this is beyond the scope of ESDoc as it should remain a library for documentation generation. 

That doesn't mean an additional tool couldn't be created that could manage versions and the like. It's more or less beyond the scope of the plugin API, but that is fine as you'd create another tool that invokes ESDoc, but separately manages versions and the like. 

For instance I'm planning on building an automation system that will invoke ESDoc during CI (Travis, etc.) when a repo is committed which subsequently makes commits into a separate documentation repo automatically versioning it as well. This will work for a many organization / many-repo arrangement as well. Icing on the cake I plan to create a containerized web app which can be easily deployed that will pull down the docs from Github and host them with a versioned / organized manner and update automatically as more commits are made to the documentation repo.

**Comment by h13i32maru** [comment]
Thanks your request 😄 

I don't support multi versions at ESDoc. However you can use [Plugin API](https://esdoc.org/manual/advanced/api.html#plugin-feature) for your request.

A rough code:
`multi-version-plugin.js`
```js
exports.onHandleConfig = function(ev) {
  const config = ev.data.config;
  const packageJsonPath = config.package || './package.json';
  const version = getVersion(packageJsonPath);
  config.destination = createNewDest(config.destination, version);
};
```

`esdoc.json`
```json
{
  "source": "./src",
  "destination": "./doc",
  "plugins": [
    {"name": "./multi-version-plugin.js"}
  ]
}
```

I re-open this if is problem.
