### ISSUE TITLE
Feature request: Extending a config

### ISSUE THREAD

**Issue by aarongodin** [esdoc/esdoc#349]
In eslint, there is an "extends" config property that allows you to move boilerplate configuration to a separate file that's used across many projects. This is really useful in organizations where the goal is to have everyone using the same eslint rules.

In a similar way, it would be handy for me if I could make all of my projects extend from the same esdoc config.

If there's interest in this feature, I can work on it.

**Comment by aarongodin** [comment]
Some additional details about what the implementation would look like:

Your esdoc config would look like:

```json
{
  "extends": "my-company"
}
```

When processing the config file, if "extends" is present esdoc would first require a node module. The naming specification eslint uses is:

```js
`eslint-config-${extends}`
```

for example, "eslint-config-my-company".

Then, it would be as simple as calling Object.assign to replace properties on the base config with the user's config.

**Comment by h13i32maru** [comment]
You can use a [Plugin API](https://esdoc.org/manual/advanced/api.html#plugin-feature) for the your request.

A rough code:
`my-company-config-plugin.js`
```js
exports.onHandleConfig = function(ev) {
  ev.data.config.title = 'Company Name';
  ev.data.config.lint = true;
  // do something
};

```

`esdoc.json`
```json
{
  "source": "./src",
  "destination": "./doc",
  "plugins": [
    {"name": "./my-company-plugin.js"}
  ]
}
```

I re-open this if is problem.
