### ISSUE TITLE
One class is not showing up in documentation, can I manually add it?

### ISSUE THREAD

**Issue by sammy6464** [esdoc/esdoc#353]
This class won't show up in my documentation, and I'm not quite sure what to do about it. Can I manually add it?

`/* @flow */
import React, { Component } from 'react';
import { connect } from 'react-redux';
import { browserHistory } from 'react-router';

import HeaderPresentation from './headerPresentation';
import { DesktopMenuItems, MobileMenuItems } from './menuConfig';
import { handleNavigate, menuToggle } from '../ducks';
import type { ToggleState, Destination, MenuConfig } from '../ducks';
import type { State } from '../../../store/types';

type PropTypes = {
  containerWidth: number,
  mobileMenuItems: MenuConfig,
  desktopMenuItems: MenuConfig,
  menuOpen: ToggleState,
  routerLocation: Destination,
  scrollLocation: Destination,
  handleNavigate: Function,
  menuToggle: Function
};

 /**
 * let HeaderContainer = new HeaderContainer();
 * @extends {Component}
 */

class HeaderContainer extends Component {
  props: PropTypes;

  constructor(props) {
  super(props);
  this.handleNavigate = this.handleNavigate.bind(this);
  this.toggleMenu = this.toggleMenu.bind(this);
  }

  handleNavigate(route: Destination, scrollTo: Destination) {
    this.props.handleNavigate(route, scrollTo);
  }

  toggleMenu() {
  this.props.menuToggle(!this.props.menuOpen);
  }

  render() {
    return (
      <HeaderPresentation
      containerWidth={this.props.containerWidth}
      desktopMenuItems={this.props.desktopMenuItems}
      mobileMenuItems={this.props.mobileMenuItems}
      onNavigateClick={this.handleNavigate}
      routerLocation={this.props.routerLocation}
      scrollLocation={this.props.scrollLocation}
      toggleMenu={this.toggleMenu}
      menuOpen={this.props.menuOpen}
      />
    );
  }
}

function mapStateToProps(state: State) {
  const menuOpen: ToggleState = state.navigation.menuOpen;
  const scrollLocation: Destination = state.navigation.scrollLocation;
  const mobileMenuItems: MenuConfig = MobileMenuItems;
  const desktopMenuItems: MenuConfig = DesktopMenuItems;
  const routerLocation: Destination = browserHistory.getCurrentLocation().pathname;
  return {
    scrollLocation,
    menuOpen,
    routerLocation,
    mobileMenuItems,
    desktopMenuItems };
}

export default connect(mapStateToProps, { handleNavigate, menuToggle })(HeaderContainer);` 

My esdoc.json file looks like this:
`{
  "source": "./src/",
  "destination": "./documentation/esdoc",
  "plugins": [
    {"name": "esdoc-es7-plugin"},
    {"name": "esdoc-flow-plugin"}
  ]
}
` Is this a big or something wrong at my end? Thanks

**Comment by typhonrt** [comment]
You need to add `"unexportIdentifier": true` to the config file for unexported classes and such to show up in the docs generated. So change your config to:
```
{ "source": "./src/", "destination": "./documentation/esdoc", "unexportIdentifier": true, "plugins": [ {"name": "esdoc-es7-plugin"}, {"name": "esdoc-flow-plugin"} ] }
```

Also `esdoc-es7-plugin` is old / defunct and can be ignored.

**Comment by sammy6464** [comment]
Aah I see that worked great thanks a lot!

**Comment by h13i32maru** [comment]
@typhonrt thanks for reply
