### ISSUE TITLE
function parameters with Array containg multiple types throws

### ISSUE THREAD

**Issue by cnlpete** [esdoc/esdoc#356]
```js
/**
 * @property {function(values: Array<object|string>)} [onValueChange] The on value change handler
 */
x = {
  onValueChange: function(values) { ... }
}
```

The error message is:
> Fatal error: Invalid regular expression: /[~]function(values: Array<object$/: Unterminated group

The current workaround is to have the object|strign in a typedef. Which kinda works, but does not produce the same, simple result.

**Comment by h13i32maru** [comment]
Thanks for this issue.

I don't have plan to support it. Please use `@typedef` for `object|string`.

```js
/**
 *
 * @param {Array<MyType>} a
 */
export default function foo(a){}

/**
 * @typedef {string|object} MyType
 */

```

**Comment by h13i32maru** [comment]
I supported this feature in next version.
https://github.com/esdoc/esdoc/commit/eb051e729b83bca552a3d4b43351dc1272ee4154
