### ISSUE TITLE
Copy package.json to esdoc output breaks the application

### ISSUE THREAD

**Issue by markusguenther** [esdoc/esdoc#357]
Hi,

I relly like the esdoc project and I am happy that i found this project.
But while using it in my react native application the compile process always copies the whole package.json.

So my package.json is in the root and in the subfolder out/esdoc. When i now use yarn start this breaks because yarn finds multiple definitions.

My current esdoc config is:
```
{
  "source": "./app",
  "destination": "./out/esdoc",
  "package": "./package.json",
  "includes": ["\\.(js|jsx|es6)$"],
  "excludes": ["(node_modules|bower_components|./package.json)"],
  "includeSource": false,
  "lint": false
}
```

Thanks, maybe it is my fault.

**Comment by vovkasm** [comment]
I have similar problems with ReactNative projects.
This workaround works for me (my documentation generated in `./doc` folder):
rn-cli.config.js
```
'use strict'

const blacklist = require('react-native/packager/blacklist')

const config = {
  getBlacklistRE() {
    return blacklist([
      /doc\/.*/
    ])
  }
}

module.exports = config
```
Plus `.eslintignore` for eslint, because `*.js` files also copied. Probably better way to deal with this is renaming copied files in generated documentation folder. For ex. `package.json` can be `package.json.source`, `index.js` -> `index.js.source` etc...

**Comment by markusguenther** [comment]
Hmm it does not work for me. Is a registration of th ern-cli.config.js file required? Sorry never used this configuration to blacklist something.

But thanks for the hint :)

**Comment by vovkasm** [comment]
Format of `rn-cli.config.js` depends on version of react-native, you can see default config (`node_modules/react-native/local-cli/default.config.js` for react-native 0.39.2) and track required parameters format from here. Teretically react-native should automatically find this file in project root.

**Comment by h13i32maru** [comment]
You can use a plugin to remove the `package.json`.

The plugin rough code.

`remove-package-json-plugin.js`
```js
exports.onComplete = function(ev) {
  fs.unlinkSync(yourPackageJSONPath);
};
```

`esdoc.json`
```json
{
  "source": "./src",
  "destination": "./doc",
  "plugins": [
    {"name": "./remove-package-json-plugin.js"}
  ]
}
```

Please see [here](https://esdoc.org/manual/advanced/api.html#plugin-feature) for more info.

**Comment by h13i32maru** [comment]
reopen if is problem.
