### ISSUE TITLE
[Question] What does the input variation in tags object ?

### ISSUE THREAD

**Issue by gregaou** [esdoc/esdoc#358]
I think all is in the title ? Just to be more specific i'm talking about tag i get in OnHandleTag function.

Thank for your answers

**Comment by typhonrt** [comment]
It's not exactly clear what you are asking other than perhaps where is the documentation for what to do in `onHandleTags`? There really isn't any per se. 

It's a callback which allows one to modify and even synthesize and inject internal ESDoc doc tags. It's also useful for a few other things and I'll point to some examples from plugins I've made. 

First is addition of new data to tags and also normalizing paths and linking JSPM managed source code to it's actual path. Check out [esdoc-plugin-jspm / onHandleTag](https://github.com/typhonjs-node-esdoc/esdoc-plugin-jspm/blob/master/src/plugin.js#L361-L398). There is a whole lot of data gathering happening before that. First to each tag a relative path is added. If it starts with `jspm_packages` then the JSPM package data is attached to the tag. There is a bunch more going on too including adding copious data about the JSPM config to a global variable including doing a full graph analysis of all package dependencies. 

Where is that info used? Well [esdoc-plugin-enhanced-navigation](https://github.com/typhonjs-node-esdoc/esdoc-plugin-enhanced-navigation/blob/master/src/plugin.js#L142-L146) processes the tags to build an enhanced left-hand side navigation replacement which is far superior to stock ESDoc. ESDoc infrastructure such as [DocBuilder.js](https://github.com/esdoc/esdoc/blob/master/src/Publisher/Builder/DocBuilder.js) can be used to create whole new sections that process the tag data. In this case [EnhancedNavDocBuilder.js](https://github.com/typhonjs-node-esdoc/esdoc-plugin-enhanced-navigation/blob/master/src/EnhancedNavDocBuilder.js) does the heavy lifting and it parses the extra data added from esdoc-plugin-jspm for the relevant doc tags. 

Soon I'll have an NPM version similar to what esdoc-plugin-jspm accomplishes.

And yes there is no documentation for how ESDoc internally works, so I learned all of the above by trial and error via reading the source code. You can do some nifty things though and this is why I'm gung ho more or less about ESDoc.

**Comment by gregaou** [comment]
Hi and thank for your answer @typhonrt, i think i wasn't clear =)

I was asking for the entry "variation" inside a tag object 
```
 {
    "__docId__": 7,
    "kind": "method",
    "static": true,
    "variation": null,
    "name": "defineAttributes",
    "memberof": "services/Model.js~Model",
    "longname": "services/Model.js~Model.defineAttributes",
    "access": null,
    "description": null,
    "lineNumber": 35,
    "undocument": true,
    ...
}
```

I made a search but i think i was blind or tired cause today i easily found my answer (https://github.com/esdoc/esdoc/blob/c9419512b7dda5e8f0b906945fb2a91f0b4621b3/src/Doc/AbstractDoc.js#L93)

Thank for your time,
gregaou

**Comment by typhonrt** [comment]
Ah yes.. It's a good question now that I understand what you are asking and this is a new tag field for me too. This is a new currently undocumented annotation for `v1.0`. From reading the code it looks like it functions similar to [JSDoc @variation](http://usejsdoc.org/tags-variation.html) for linking docs with the same name. It looks like one would add `@variation <number>` similar to what is described in the linked JSDoc annotation. Hard to tell if it's completely implemented / finished feature. I've been waiting for the maintainer to push out `v1.0` / next version before digging into any changes added or doing any testing.  With any luck a description will be added to ESDoc [tags section of the documentation](https://esdoc.org/tags.html) sometime soon.

So far it only looks like it is used in [ClassDocBuilder.js](https://github.com/esdoc/esdoc/blob/master/src/Publisher/Builder/ClassDocBuilder.js#L126-L136).

**Comment by h13i32maru** [comment]
The code was written at early ESDoc. However, now I don't have plan to support `@variation`.
