### ISSUE TITLE
v1.0 release progress

### ISSUE THREAD

**Issue by typhonrt** [esdoc/esdoc#360]
@h13i32maru thanks for putting in some time over past months and recently with today's v0.5 / v0.5.1 releases.

I'd like to invite you to comment on this issue regarding the progress to v1.0 as you keep editing your [old post](https://github.com/esdoc/esdoc/issues/293) which is not transparent to the larger community interested in the progress of ESDoc. It would be very handy if you can post discrete updates to this issue so that we can all follow along with your progress. I have been aware of your tendency to edit the old post mentioned, but that likely is not the case for the larger community. Editing an old post does not show up as a progress notification to anyone watching this repo. 

I'll take some time over the coming days to verify that my ESDoc plugins work with `v0.5.1`. Do you expect anymore v0.5.x releases before publishing v1.0? 

Thanks for your efforts and I'm glad things are progressing to a v1.0 release. Happy holidays!

**Comment by h13i32maru** [comment]
@typhonrt Thanks for your concern.

I posted a comments. Please check it.
https://github.com/esdoc/esdoc/issues/293#issuecomment-269179926
