### ISSUE TITLE
ES7 objectRestSpread bug

### ISSUE THREAD

**Issue by ratson** [esdoc/esdoc#365]
- [x] check the documentation of ESDoc
  - https://esdoc.org/manual/configuration/config.html
  - https://esdoc.org/manual/usage/tags.html
  - https://esdoc.org/manual/faq/faq.html
- [x] your input data (codes, config and more)
https://github.com/ratson/bug-esdoc
```js
class Bug {
  constructor() {
    const o = {}
    this.a = {
      ...o,
    }
  }
}
```
- [x] write output that you obtained (log or screenshot)
`TypeError: Cannot read property 'name' of undefined`
- [x] if possible, write your expectation for the input
Should generate docs without error
- [x] your environment
  - OS type and version
macOS 10.10
  - Node.js version
v7.3.0
  - ESDoc version
v0.5.1

**Comment by h13i32maru** [comment]
@ratson Sorry for late reply 🙇 
I merged and improved to guess type.

https://github.com/esdoc/esdoc/pull/364
https://github.com/esdoc/esdoc/commit/b613502c8eaa010979f3344012a2543801c18d38

And I will release it in next version
