### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by taoxiang1995** [esdoc/esdoc#369]
Make sure these boxes are checked before submitting your issue - thank you!
(If your issue is neither a both bug nor a request, please write in a free style)

- [ 1] check the documentation of ESDoc
  - https://esdoc.org/manual/configuration/config.html
  - https://esdoc.org/manual/usage/tags.html
  - https://esdoc.org/manual/faq/faq.html

- [ ] your input data (codes, config and more)
{"source": "./src", "destination": "./doc"}

- [ ] write output that you obtained (log or screenshot)
/usr/local/lib/node_modules/esdoc/out/src/ESDoc.js:121
      results.push(...temp.results);
                   ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/esdoc/out/src/ESDocCLI.js:20:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

- [ ] if possible, write your expectation for the input
- [ ] your environment
  - OS type and version macOS Yosemite 10.10.5
  - Node.js version: v4.3.1
  - ESDoc version: 0.5.1

**Comment by h13i32maru** [comment]
> your input data (codes, config and more)

Please write JavaScript source code. Otherwise I can not inspect this.

**Comment by aristov** [comment]
https://travis-ci.org/aristov/htmlmodule/builds/190010618

**Comment by skurger** [comment]
I stopped getting this error when I upgraded to the Node v6.9.4 (the current LTS) FYI.  This was added to the esdoc.org documentation site but I'm not sure when: "ESDoc supports Node.js(v6 or later)"

https://esdoc.org/manual/faq/faq.html

Check the "Supported Environment" section.

**Comment by CoenWarmer** [comment]
Thanks for this answer. I was on Node v4.2.1 and had the same error. 

It would be very nice if ESDoc could support lower versions of Node (4 mainly) as it is used in many production environments where it isn't as easy as upgrading to the latest and greatest version of Node.

**Comment by dafit1991** [comment]
I have similar issue. I have node 5.3, and unfortunately cannot upgrade it in production. 

It seems to be caused by es6 code in esdoc. 

Perhaps changing babel configuration would solve this? 
Example in esdoc code [Default parameters](https://github.com/esdoc/esdoc/blob/master/src/Plugin/Plugin.js#L18)

**Comment by dafit1991** [comment]
It is possible to run esdoc on node 5.3.0 using babel-node. Example in script below.

const path = require('path');
const childProcess = require('child_process');

function exec(cmd) {
  cmd = cmd.replace(/\//g, path.sep);
  childProcess.execSync(cmd, {stdio: 'inherit'});
}

exec('./node_modules/.bin/babel-node ./node_modules/esdoc/out/src/ESDocCLI.js');

I've also experimented with build process of esdoc (babel config). ES6 issues are gone when setting preset to env but Reflect.defineProperty() is missing. Perhaps using some kind of polyfill would solve it?

**Comment by taoxiang1995** [comment]
Thanks guys. I solved this issue by upgrading my node to v6.9.4.
I will close the issue for now.
