### ISSUE TITLE
Manual index not generating correctly. Right click disabled on manual screen.

### ISSUE THREAD

**Issue by mdashx** [esdoc/esdoc#375]
# Short summary of your issue
The manual navigation only shows "Reference". The divs for the TOC items are generated, but not the list/anchor elements. The cards for elements besides "Reference" do not show up in the body. Right click is not working on the manual screens. There are not errors or other messages in the browser console. Building the documentation runs fine with no error output. 

# Input data for reproducing
#### Configuration
```json
"manual": {
  "overview": ["./manual/overview.md"]
}
```

# Output data
#### Log
```
output: manual/index.html
output: manual/overview/overview.html
output: manual-badge.svg
```

### HTML
```html
<div class="manual-toc-root">
  
<div data-ice="manual" data-toc-name="overview">
    <ul class="manual-toc">
      
    </ul>
  </div>
<div data-ice="manual" data-toc-name="reference">
    <ul class="manual-toc">
      
    <li data-ice="manualNav" class="indent-h1 manual-color manual-color-reference" data-section-count="■■■" data-link="identifiers.html"><a href="identifiers.html" data-ice="link">Reference</a></li>
<li data-ice="manualNav" class="indent-h2" data-link="identifiers.html"><a href="identifiers.html#class" data-ice="link">Class</a></li>
<li data-ice="manualNav" class="indent-h2" data-link="identifiers.html"><a href="identifiers.html#function" data-ice="link">Function</a></li>
<li data-ice="manualNav" class="indent-h2" data-link="identifiers.html"><a href="identifiers.html#variable" data-ice="link">Variable</a></li>
</ul>
  </div>
</div>
```

# Your environment
- OS type and version: Ubuntu 16.04.1 LTS 
- Node.js version: v7.2.1
- ESDoc version: 0.5.2

**Comment by mdashx** [comment]
Everything related to the manual index works fine when I use version 0.4.8

**Comment by h13i32maru** [comment]
A manual TOC title is generated by `# Title`. Do you write `# Title` in your markdown file? If you does not write it, please write it.

FYI: You can check it via [try.esdoc.org](https://goo.gl/z3fsK7)

**Comment by mdashx** [comment]
@h13i32maru thank you much, it works great now. I thought the title was generated automatically based on the the "manual" section of the config file. I actually did have a heading tag, but it was `## Title`. Changing to a top-level heading fixed it. Thanks!
