### ISSUE TITLE
Test feature doesnt work when folder structure is same

### ISSUE THREAD

**Issue by gyandeeps** [esdoc/esdoc#376]
Make sure these boxes are checked before submitting your issue - thank you!
(If your issue is neither a both bug nor a request, please write in a free style)
- [ ] https://esdoc.org/manual/usage/feature.html
- [ ] https://esdoc.org/manual/configuration/config.html
- [ ] https://esdoc.org/manual/usage/tags.html
- [ ] https://esdoc.org/manual/advanced/api.html
- [ ] https://esdoc.org/manual/faq/faq.html

# Short summary of your issue
Test feature doesnt work if the folder structure inside `src` and `test` folder is identical. My guess is that it overwrites each other while docs are generated.

# Input data for reproducing
#### Configuration
```json
{
    "title": "test",
    "source": "./src/main",
    "destination": "./pages/doc",
    "test": {
        "type": "mocha",
        "source": "./src/__tests__"
    },
    "coverage": true,
    "lint": false
}
```

#### Codes
create your folder structure this way

```
--base
       --> src
            --> fol1
                --> subfol1
                    --> src1.js
                    --> src2.js
       --> test
            --> fol1
                --> subfol1
                    --> src1.js
                    --> src2.js
                    
```

Note: `src` and `test` folder structure and names are identical.

# Output data
#### Log

build output is success

When I launch the page and hit the test tab then its a 404

# Your environment
- OS type and version: Windows 7
- Node.js version: 7.4
- ESDoc version: 0.5.2

**Comment by petrbroz** [comment]
I see the same problem even when the folder structure under `src/` and `test/` is different, and the filenames are different, too.

**Comment by sebastianwessel** [comment]
...same on me

`lib/` and `test/` with folders inside each directory containing files Class.js and ClassTests.js

macOS Sierra 10.12.4
Node.js version 7.7.3
ESDoc version 0.5.2
