### ISSUE TITLE
No documentation is generated

### ISSUE THREAD

**Issue by ripter** [esdoc/esdoc#383]
Make sure these boxes are checked before submitting your issue - thank you!
(If your issue is neither a both bug nor a request, please write in a free style)
- [x] https://esdoc.org/manual/usage/feature.html
- [x] https://esdoc.org/manual/configuration/config.html
- [x] https://esdoc.org/manual/usage/tags.html
- [x] https://esdoc.org/manual/advanced/api.html
- [x] https://esdoc.org/manual/faq/faq.html

# Short summary of your issue
It looks like it works, I see each source file listed in the `parse` and `output` in the log. I can see the source of each file. But the refrence page is blank, and it says `Coverage: 0% (0/0)`. This same code generates properly when using JSDoc3

# Input data for reproducing
#### Configuration
```json
{
  "source": "./src",
  "destination": "./doc"
}
```

#### Codes
```js
/**
 * Returns a valid index for the array
 * @param {Array} array - array to use when calculating wrapping.
 * @param {Number} index - starting index to use.
 * @param {Number} delta - positive or negative number to adjust the index.
 * @return {Number} - A valid index for the array.
 */
module.exports = function wrapIndex(array, index = 0, delta = 0) {
  // delta allows us to advance the index in either direction.
  // mod the sum by length to wrap-around when the end is reached.
  index = (index + delta) % array.length;

  // if the new index value is negative, make it positive
  if (index < 0) {
    index += array.length;
  }

  return index;
};

```

# Output data
#### Log
```
parse: /Users/chris/dev/tesla/js/src/utils/wrapIndex.js
resolve: extends chain
resolve: necessary
resolve: access
resolve: unexported identifier
resolve: undocument identifier
resolve: duplication
resolve: ignore
resolve: link
resolve: markdown in description
resolve: test relation
output: badge.svg
output: identifiers.html
output: index.html
output: file/src/utils/wrapIndex.js.html
```

#### Screen shot of documentation
![Screen shot](http://i.imgur.com/Imk1ehq.png)

# Your environment
- OS type and version: macOS 10.12.2 (16C67)
- Node.js version: v6.9.1
- ESDoc version: 0.5.2

**Comment by guiguan** [comment]
It looks like you hv to use es6's export:

```
/**
 * Returns a valid index for the array
 * @param {Array} array - array to use when calculating wrapping.
 * @param {Number} index - starting index to use.
 * @param {Number} delta - positive or negative number to adjust the index.
 * @return {Number} - A valid index for the array.
 */
export default function wrapIndex(array, index = 0, delta = 0) {
  // delta allows us to advance the index in either direction.
  // mod the sum by length to wrap-around when the end is reached.
  index = (index + delta) % array.length;

  // if the new index value is negative, make it positive
  if (index < 0) {
    index += array.length;
  }

  return index;
};
```

**Comment by guiguan** [comment]
You can use this plugin: https://www.npmjs.com/package/esdoc-node

**Comment by h13i32maru** [comment]
@ripter ESDoc does not support `module.exports`.

https://esdoc.org/manual/usage/feature.html#es2015-module
> Note: ESDoc doesn't support module/require of Node.js.

You can use  https://www.npmjs.com/package/esdoc-node that is un-official plugin.

**Comment by h13i32maru** [comment]
@guiguan Thanks!

**Comment by nayeembadhusha** [comment]
@guiguan why do we need export keyword...why does ESDoc doesn't produce any document for this code?...But generates doc when used with export keyword?
`/**
 * @param {Number} a - Integer value
 * @param {Number} b - Integer Value
 * @returns {Number} diff - Integer Value
 */

function add (a, b){
        var sum;
        sum = b-a;
        return sum

    }`
