### ISSUE TITLE
AST Docs line preventing completion

### ISSUE THREAD

**Issue by flodonsky** [esdoc/esdoc#406]
Make sure these boxes are checked before submitting your issue - thank you!
(If your issue is neither a both bug nor a request, please write in a free style)
- [x] https://esdoc.org/manual/usage/feature.html
- [x] https://esdoc.org/manual/configuration/config.html
- [x] https://esdoc.org/manual/usage/tags.html
- [x] https://esdoc.org/manual/advanced/api.html
- [x] https://esdoc.org/manual/faq/faq.html

# Short summary of your issue

When I run a build, I end up with the following error. However if I comment out line `publish.js:152`
Everything works as expected. I don't need AST Docs, just HTML. But this is throwing an error keeping me from completion.

ERROR LOG BELOW

# Input data for reproducing
#### Configuration
```json
{
  title: "My Title",
  coverage: true,
  includeSource: true,
  builtinExternal: true,
  autoPrivate: true,
  unexportIdentifier: false,
  undocumentIdentifier: true,
  source: null,
  destination: "./src/build/docs",
  lint: true,
  experimentalProposal: {
    classProperties: true,
    objectRestSpread: true,
    decorators: true,
    doExpressions: true,
    functionBind: true,
    asyncGenerators: true,
    exportExtensions: true,
    dynamicImport: true
  }
}
```

#### Codes
```js
// write into here
```

# Output data
#### Log
```bash
RangeError: Invalid string length
    at join (native)
    at Object.stringify (native)
    at ASTDocBuilder.exec (/usr/src/app/node_modules/esdoc/out/src/Publisher/Builder/ASTDocBuilder.js:34:25)
    at publish (/usr/src/app/node_modules/esdoc/out/src/Publisher/publish.js:152:51)
    at Function.generate (/usr/src/app/node_modules/esdoc/out/src/ESDoc.js:137:7)
    at DestroyableTransform.flush [as _flush] (/usr/src/app/node_modules/gulp-esdoc/index.js:42:11)
    at DestroyableTransform.<anonymous> (/usr/src/app/node_modules/readable-stream/lib/_stream_transform.js:115:49)
    at DestroyableTransform.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at DestroyableTransform.emit (events.js:185:7)
```

#### Screen shot of documentation
// attach a image into here

# Exception output (if possible)
#### Log
```
// write into here
```

#### Screen shot of documentation
// attach a image into here

# Your environment
- OS type and version: DOCKER->Node->6.10.0
- Node.js version: 6.10.0
- ESDoc version: `latest:0.5.2`

**Comment by MattMcFarland** [comment]
I am experiencing the same problem using node 8.

**Comment by MattMcFarland** [comment]
@h13i32maru can I get word from you that this project is still maintained?  The issues and PR are piling up.  I can work on fixing this issue if you are still interested in working on this project. I'd be happy to help you out as well.

**Comment by MattMcFarland** [comment]
@h13i32maru can I get word from you that this project is still maintained?  The issues and PR are piling up.  I can work on fixing this issue if you are still interested in working on this project. I'd be happy to help you out as well.

**Comment by relicmelex** [comment]
@MattMcFarland I found out the problem is how JS handles strings... you docker container just doesn't have enough resources as what you're asking it to do is a fairly heavy task. The addition of using streams is I think the correct solution, but you may have to fork and start being the maintainer... I'd follow up. Cheers.

**Comment by MattMcFarland** [comment]
Been playing around with this, and inspecting memory usage!

When using the original method usage is this:
```
rss 86.72 MB
heapTotal 57.85 MB
heapUsed 29.37 MB
external 1.71 MB
```

When using stream API the memory usage is this:
```
rss 84.04 MB
heapTotal 54.85 MB
heapUsed 35.01 MB
external 0.35 MB
```

The differences aren't much, and I haven't tested this in our gitlab runner yet.  Even with streams, calling JSON.stringify is heavy.  I am thinking we might have to break the objects up a little bit to prevent a huge push to JSON stringify.

**Comment by MattMcFarland** [comment]
Ok, I just found an awesome library: [big-json](https://github.com/DonutEspresso/big-json), and verified that it breaks the json up so stringify never hits its limit. I've implimented it, tested it with a huge file, and pushed up the changes.  I am going to send a PR!

**Comment by flodonsky** [comment]
Ohhh, very nice...!

**Comment by MattMcFarland** [comment]
We have a working solution, but I want to make sure we cover our bases before sending the PR.  Sorry for the early request!  Will have one ready soon

**Comment by MattMcFarland** [comment]
Ok, we finally have finished this up.  This was a pretty big effort between @workjalexanderfox and I, including code reviews, testing, iteration, cleanup, etc.  Hope this helps the community and we look forward to contributing more to esdoc in the future.

**Comment by MattMcFarland** [comment]
@flodonsky can you pull down my forked version and try it out?  you could probably just change your package.json / esdoc version tag to `MattMcFarland/esdoc#216ed7f` as[ npm supports github](https://docs.npmjs.com/files/package.json#github-urls) for version tags.

Also are there any other maintainers other than @h13i32maru  ?  He is very active on twitter but seems to be MIA here.

**Comment by relicmelex** [comment]
@MattMcFarland looking now
