### ISSUE TITLE
Marking function as class?

### ISSUE THREAD

**Issue by JerryFox1** [esdoc/esdoc#41]
Is there a way to force an export function to be treated as a class?
Example:
export function AudioExt(session){
vs.
export class Pluggy {

Classes have their own section while the functions are all grouped together.
Is it possible to change this?

**Comment by h13i32maru** [comment]
@JerryFox1 Hi! Thanks for this issue!
Sorry, ESDoc does not support it :pensive:
And, for now, I do not plan to support it.
