### ISSUE TITLE
not all es6 features turned on for espree

### ISSUE THREAD

**Issue by nickolaylavrinenko** [esdoc/esdoc#42]
Hi guys!
I've noticed that some of features have been missed in "ecmaFeatures" list in parser. I think whole React.js community will be grateful if you turn on "experimentalObjectRestSpread" feature.
Thank you!

**Comment by melbourne2991** [comment]
+1

**Comment by h13i32maru** [comment]
@nickolaylavrinenko @melbourne2991 Hi! Thanks for this issue!

I think that ``ObjectRestSpread`` is [ES7 syntax](https://github.com/sebmarkbage/ecmascript-rest-spread)
And, For now, I don't plan to support ES7 in ESDoc main stream.

But, I published [ESDoc ES7 Plugin](https://github.com/esdoc/esdoc-es7-plugin) :smile:
This plugin enables to generate documentation from source code including ES7.
You can use this plugin with ESDoc@0.2.1
