### ISSUE TITLE
Added tilde in filename causes issues when hosted from Apache Tomcat

### ISSUE THREAD

**Issue by geertendoornenbal** [esdoc/esdoc#423]
I'm using ESDoc in Hudson, where I use the HTML publish plugin to publish the results.

This works fine, until I click one of my classes, and get a 404 from Tomcat. This is caused by the added tilde/~ in the filename. 
This is done at the following location:
https://github.com/esdoc/esdoc/blob/master/src/Doc/ClassDoc.js#L89

Apache Tomcat filters these out (makes sense, considering tilde being the home directory on Linux), and I have broken documentation.

Can you replace this tilde with something else?

**Comment by geertendoornenbal** [comment]
Close, I jumped to conclusions too soon. No issue here.

**Comment by eemeli** [comment]
@geertendoornenbal I think I'm experiencing the same or a similar issue as this, with ESDoc output being hosted as "Javadoc" in Jenkins: paths that include `~` result in `404 Not Found` errors. How did you resolve this issue?
