### ISSUE TITLE
Documentation for destructuring arguments.

### ISSUE THREAD

**Issue by koba04** [esdoc/esdoc#43]
```js
export function test({foo, bar}) {
}
```

In this code, ESDoc generates a documentation as below.

![image](https://cloud.githubusercontent.com/assets/250407/9105133/b6066dfe-3c4f-11e5-8efa-c1859373d825.png)

Does ESDoc have the way to write a documentation for destructuring arguments?

like this:

```
/**
 * test1
 * @param {object} args
 * @property {string} foo
 * @property {string} bar
 */
export function test1({foo, bar}) {
}
```

Thanks.

**Comment by h13i32maru** [comment]
Would this code help for you?

```javascript
/**
 * test1
 * @param {object} args - this is args.
 * @param {string} args.foo - this is foo of args.
 * @param {string} args.bar - this is bar of args.
 */
export function test1({foo, bar}) {
}
```

<img width="506" alt="2015-08-07 13 26 02" src="https://cloud.githubusercontent.com/assets/985170/9128698/f4f46bde-3d07-11e5-8c07-2f79d968fd3b.png">

FYI: https://esdoc.org/tags.html#object

**Comment by koba04** [comment]
I was missing the document... :persevere:
Thanks!!

**Comment by h13i32maru** [comment]
:+1:
