### ISSUE TITLE
TypeScript throwing errors for lines that don't exist

### ISSUE THREAD

**Issue by wbhob** [esdoc/esdoc#447]
Make sure these boxes are checked before submitting your issue - thank you!
(If your issue is neither a both bug nor a request, please write in a free style)
- [x] https://esdoc.org/manual/usage/feature.html
- [x] https://esdoc.org/manual/configuration/config.html
- [x] https://esdoc.org/manual/usage/tags.html
- [x] https://esdoc.org/manual/advanced/api.html
- [x] https://esdoc.org/manual/faq/faq.html

# Short summary of your issue
TypeScript support is a little weak from my understanding... I am unable to find where this error is located. This error should not be happening, since all the code is valid.

# Input data for reproducing
#### Configuration
```json
{
  "source": "./packages",
  "destination": "./docs",
  "excludes": [
    ".*(node_modules).*"
  ],
  "plugins": [
    {
      "name": "esdoc-typescript-plugin"
    }
  ]
}
```

#### Codes
```js
// middleware.ts
import { makeDecorator, TypeDecorator } from './util';

// export interface Middleware { }

export interface MiddlewareDecorator {
    (): TypeDecorator;

    new(): any;
}


export const Middleware: MiddlewareDecorator =
    <MiddlewareDecorator>makeDecorator('Middleware');
```

# Output data
#### Log
```
// write into here
```

#### Screen shot of documentation
// attach a image into here

# Exception output (if possible)
#### Log
```
parse: /Users/wilsonhobbs/orbital/framework/packages/core/src/decorators/middleware.ts
{ SyntaxError: Unexpected token (1:26)
    at Parser.pp$5.raise (/usr/local/lib/node_modules/esdoc/node_modules/babylon/lib/index.js:4246:13)
```

#### Screen shot of documentation
// attach a image into here
![screen shot 2017-08-01 at 11 33 26 pm](https://user-images.githubusercontent.com/4442130/28856559-dd3a91c6-7711-11e7-9e65-286b266377a1.png)

# Your environment
- OS type and version: macOS 10.12
- Node.js version: 8.2.1
- ESDoc version: 1.0.1

**Comment by wbhob** [comment]
Hello? Is anyone there?

**Comment by nicolo-ribaudo** [comment]
ESDoc doesn't support TypeScript because it uses Babylon 6 to parse the input code. You may use the [esdoc-typescript-plugin](https://github.com/esdoc/esdoc-plugins/tree/master/esdoc-typescript-plugin)

**Comment by wbhob** [comment]
That is what I am using
