### ISSUE TITLE
Not sure what guidelines are for coverage

### ISSUE THREAD

**Issue by aphelionz** [esdoc/esdoc#45]
Hi, please see my coverage stats here: http://luna-aphelionz.c9.io/waterhero/client/doc/source.html

As I work through my docs and tests I can't seem to get 100% coverage on any particular file. I was hoping something obvious would occur to me, but it hasn't happened yet.

What else is esdoc expecting for 100% coverage?

**Comment by h13i32maru** [comment]
@aphelionz Hi! Thanks this issue :smile: 

In order to be 100% coverage, you must write documentation to all identifiers.

The following code is not 100% coverage.

```javascript
/**
 * one
 */
class Foo {}

export default new Foo();
```

To be 100% coverage:

```javascript
/**
 * one
 */
class Foo {}

/**
 * two
 */
export default new Foo();
```

Is this helpful to you?

**Comment by aphelionz** [comment]
Yes, thank you! Will the comments above an export statement be reflected in
the docs anywhere?

**Comment by h13i32maru** [comment]
The comments is reflected in ``variable`` page.
- http://luna-aphelionz.c9.io/waterhero/client/doc/variable/
- http://luna-aphelionz.c9.io/waterhero/client/doc/variable/index.html#static-variable-application

**Comment by aphelionz** [comment]
Thank you! I am satisfied :)

**Comment by h13i32maru** [comment]
:+1:
