### ISSUE TITLE
Don't parse es-function-bind

### ISSUE THREAD

**Issue by i-have-no-name** [esdoc/esdoc#49]
Don't parse es-function-bind ::

**Comment by h13i32maru** [comment]
@i-have-no-name Hi! Thanks this issue :smile: 
``function bind ::`` is ES7, and Now, doest not support ES7 in ESDoc main stream.
However experimentally support with [ESDoc ES7 Plugin](https://github.com/esdoc/esdoc-es7-plugin).
Please use it.

**Comment by i-have-no-name** [comment]
Thansk!)
