### ISSUE TITLE
Update "marked" dependency due to security vulnerability

### ISSUE THREAD

**Issue by amirmohsen** [esdoc/esdoc#492]
I am using ESDoc to generate documentation for my library. Github has given me an alert about a security issue with one of my dependencies, [marked](https://github.com/chjj/marked/issues/863) which is in fact a dependency of esdoc. Here's the result of running `npm ls marked` on my library:

```
+-- esdoc@1.0.4
| `-- marked@0.3.6
`-- esdoc-standard-plugin@1.0.0
  `-- esdoc-publish-html-plugin@1.1.0
    `-- marked@0.3.6  deduped
```

As you can see, both core and at least one of the plugins depend on it. Could you please upgrade marked to its latest version to address this security issue?

**Comment by teppeis** [comment]
Why are all dependencies locked? https://github.com/esdoc/esdoc/commit/86cf2206f7b53b599091573f888b8403635d96ca

**Comment by amirmohsen** [comment]
That's a good point. If your dependencies follow semver, you shouldn't have to lock them like that.

**Comment by pixelass** [comment]
reported here too: 
https://github.com/esdoc/esdoc-plugins/issues/50
