### ISSUE TITLE
Is there way to disable source of code? 

### ISSUE THREAD

**Issue by shenghu** [esdoc/esdoc#493]
I'm using it to document our utilitis, which is good. In the generated document, there is link `source` which allows user to jump to source code. However, I want to disable this feature. Is there configuration to disable it?

**Comment by ericblade** [comment]
I suspect turning off the "coverage" option might do that:

https://esdoc.org/manual/config.html#full-config

**Comment by shenghu** [comment]
@ericblade unfortunately, turning off 'coverage' doesn't disable reference to source code.

**Comment by TriMoon** [comment]
See: https://github.com/esdoc/esdoc-plugins/tree/master/esdoc-exclude-source-plugin
:wink:

**Comment by shenghu** [comment]
@TriMoon thanks. This works.

**Comment by MG55** [comment]
What if I want to completely hide the "source" page? I don't only want to hide source code, but also hide the link to the file list and the list itself. Using esdoc-exclude-source-plugin, the code is unreachable but the file list is visible.
