### ISSUE TITLE
Multiple source directories

### ISSUE THREAD

**Issue by tobscure** [esdoc/esdoc#52]
I am building two ES6 module-based JavaScript applications which both build on top of a common library of modules:

```
app1/
  src/
    foo1.js
    bar1.js
app2/
  src/
    foo2.js
    bar2.js
lib/
  common.js
  another.js
```

So after compilation, app1 ends up with the modules app1/common, app1/another, app1/foo1, and app1/bar1.
Likewise, app2 ends up with the modules app2/common, app2/another, app2/foo2, and app2/bar2.

What is the best approach to generate docs in this scenario?

If I just generate docs individually for app1 and app2, then the docs don't contain proper references to the classes in lib.

I was thinking it might help if I could specify multiple source directories in esdoc config. So I could generate docs for app1+lib, and then app2+lib.

What do you think?

**Comment by h13i32maru** [comment]
@tobscure Hi! Thanks this issue!
Does the following code helpful for you?

- esdoc1.json
```javascript
{
  "source": "./",
  "destination": "./doc1",
  "excludes": ["app2"]
}
```

- esdoc2.json
```javascript
{
  "source": "./",
  "destination": "./doc2",
  "excludes": ["app1"]
}
```

But, unfortunately, this case has a bug...
Please wait a little for I fix this bug.

**Comment by h13i32maru** [comment]
@tobscure I released ESDoc v0.2.3. This ESDoc fixed the bug.
Please try to it.

**Comment by tobscure** [comment]
Thanks!

**Comment by c-emil** [comment]
@h13i32maru Wouldn't it be better to provide an array of sources? If I have 15 directories to exclude but 2 to include, I think it would be nice to have such option.
