### ISSUE TITLE
Inline docblocks

### ISSUE THREAD

**Issue by cristinecula** [esdoc/esdoc#54]
Hello. First of all I want to thank you for this awesome software! It's really useful and easy to use.

Do you think it's possible to support inline docblocks?
```
    /** @type {Number} the progress in percentages */
    this.progress = 0
```

**Comment by h13i32maru** [comment]
@cristinecula Hi! Thanks this question!
Now, ESDoc supports inline docblocks.
But, ``@type`` can not have description text.
Because [JSDoc original syntax](http://usejsdoc.org/tags-type.html) does not have description text.
Sorry :sweat:

**Comment by mysticatea** [comment]
So this works:

```js
/** the progress in percentages. @type {Number} */
this.progress = 0
```

Hmm, ugly a bit :)

**Comment by h13i32maru** [comment]
@mysticatea Thanks!
But documentation of the code is invalid... ESDoc does not support the style.
![2015-08-28 22 13 10](https://cloud.githubusercontent.com/assets/985170/9546997/0804284c-4dd2-11e5-88d6-20e079160ace.png)

**Comment by cristinecula** [comment]
Thank you for the answer :)

This notation is pretty standard across other documentation tools, but I understand if you want compatibility with JSDoc. 

Keep up the good work :+1:

**Comment by h13i32maru** [comment]
Thanks for your understanding.
