### ISSUE TITLE
Flow type support

### ISSUE THREAD

**Issue by Chrisui** [esdoc/esdoc#55]
Is it currently possible to extract types from [typescript](http://www.typescriptlang.org/) (specifically using [flow types](http://flowtype.org/)) style [annotations](http://www.typescriptlang.org/Handbook#basic-types) when building documentation rather than enforcing extra docblocks? Perhaps there is some plugin support?

If not currently is there any plan to build this support in?

**Comment by h13i32maru** [comment]
@Chrisui Hi! Thanks this question!
Sorry, ESDoc does not support typescript and flow types. And I have no plan to it.

But, ESDoc has plugin system. The plugin can replace JavaScript parser to any parser.
I use the plugin system to support ES7
- https://github.com/esdoc/esdoc-es7-plugin
- https://esdoc.org/api.html#plugin-feature

I do not know detailed about typescript, you might be able to support typescript with using the plugin system.

**Comment by eaviles** [comment]
I've just published a plugin that will strip Flow annotations and types. It's an initial effort towards integrating Flow into ESDoc data.

https://github.com/eaviles/esdoc-flow-plugin

**Comment by ksmolyanin** [comment]
Actually the first idea when you start using both ESDoc and Flow Type in one project is "how to eliminate that redundancy when you need to describe types differently for both tools". It would be really nice to have some plugin that can generate jsdocs from the flow syntax.

**Comment by thurt** [comment]
@ksmolyanin 

great point! honestly, i'm thinking if you adopt flow, then flow types should be used as a replacement for ESDoc & jsDoc tags. As a developer, I have never used the external documentation generated by ESDoc for my day-to-day work. I want to remain inside the code and not have to be switching contexts. flow brings that forward with much better integration into my ide and becomes part of my continuous integration checks and my type annotations never become outdated.

**Comment by rutsoluo** [comment]
@eaviles Thanks for the great job, it would be wonderful if it could generate documentation from the Flow declaration.
