### ISSUE TITLE
Outdated website / docs

### ISSUE THREAD

**Issue by DanielRuf** [esdoc/esdoc#555]
It seems the website / docs of esdoc is not the latest - `--save-dev` is missing there.

**Comment by cjancsar** [comment]
That is because -> https://github.com/esdoc/esdoc/issues/556

**Comment by DanielRuf** [comment]
We use typedoc now. It's still actively maintained.

**Comment by cjancsar** [comment]
@DanielRuf does TypeDoc support plain JS projects though?

**Comment by cjancsar** [comment]
Looks like it might: https://github.com/TypeStrong/typedoc/issues/643
