### ISSUE TITLE
Improve Coverage Report by displaying what is not documented

### ISSUE THREAD

**Issue by Rukenshia** [esdoc/esdoc#61]
I am currently documenting a lot of code. Currently, my work flow is like "do what you see is missing in your files and then run esdoc to see how much is covered". esdoc always provides me a neat percentage for each file, but maybe this could be taken even further to display what is *not* covered yet. Im currently stuck in a few files with like 70/71 and whatever and it is pretty hard to find what's missing right now. 
Maybe it is possible to mark the lines in the source page for each file of esdoc? I would pretty much love that. If you can already measure how much is covered, I guess it should be possible to check what is not covered.

**Comment by h13i32maru** [comment]
I understood your request. And I think that it is pretty good!
I consider UI of coverage detail. Please wait a some time because the UI is difficult.
Thanks.

**Comment by h13i32maru** [comment]
Now, I published ESDoc v0.2.5.
With this version, you can see undocumentation lines.
1. click ``Source`` in header
2. click ``your not 100% coverage file link``

<img width="558" alt="2015-09-06 19 14 31" src="https://cloud.githubusercontent.com/assets/985170/9703880/8e468b84-54cb-11e5-9f19-1f5372918566.png">

**Comment by Rukenshia** [comment]
Awesome, thank you!
