### ISSUE TITLE
setter documentated with return type *

### ISSUE THREAD

**Issue by Rukenshia** [esdoc/esdoc#62]
When generating a documentation of a class with getters and setters, the setter will be documented/parsed as
```javascript
public set name(variableName: type): *
```

Looking at the [ECMAScript Specification, 11.13.1](http://www.ecma-international.org/ecma-262/5.1/#sec-11.13.1), a setter always returns the value:

```javascript
public set name(variableName: type): type
```

would be therefor correct if I am not mistaken. Maybe it should just be left out for cosmetic purposes.

Code to reproduce said behavior:
```javascript
export class Foo {
  /**
   * New Foo
   */
  constructor() {
    /** @type {string} */
    this._bar = '';
  }

  /**
   * @type {string}
   */
  get bar() {
    return this._bar;
  }

  /**
   * Sets bar to the given string
   *
   * @param {string} v - the new value of bar
   */
  set bar(v) {
    this._bar = v;
  }
}
```

**Comment by h13i32maru** [comment]
Setter must be following doc comment. Use ``@type`` instead of ``@param``.
```javascript
  /**
   * Sets bar to the given string
   *
   * @type {string}
   */
  set bar(v) {
    this._bar = v;
  }
```
<img width="322" alt="2015-08-30 20 13 40" src="https://cloud.githubusercontent.com/assets/985170/9566906/aa33dbb2-4f53-11e5-99c0-9654664e4b85.png">

**Comment by Rukenshia** [comment]
Alright.
