### ISSUE TITLE
Documenting getters and setters

### ISSUE THREAD

**Issue by IjzerenHein** [esdoc/esdoc#64]
Hi! First of all, great library, love the output it generates :)

Hey, I've got classes with getters and setters, like this:

```javascript
export default class Label2 extends Surface {
  constructor(options) {
    super(options);
    this.text = (options && options.text) ? options.text : '';
  }

  /**
   * Text that is displayed in the label.
   *
   * @type {String}
   */
  get text() {
    return this._text;
  }

  set text(text) {
    text = text || '';
    if (this._text !== text) {
      this._text = text;
      // do stuff here
    }
  }
}
```

It generates this output:
![image](https://cloud.githubusercontent.com/assets/6184593/9567541/4f4f4ba6-4f2f-11e5-83d6-2f0d39966c70.png)

It fails to document the getter/setter property, because `this.text = (options && options.text) ? options.text : '';` exists in the constructor. When clicking on 'source' it points to the constructor code:

![image](https://cloud.githubusercontent.com/assets/6184593/9567532/1b3a9c3a-4f2f-11e5-8511-db8343b7e179.png)

Am I doing it right? How can I fix this?

Cheers

**Comment by h13i32maru** [comment]
@IjzerenHein Hi! Thanks for this issue!
This is ESDoc bug :sweat: I will try to fix it. Please wait a little.

**Comment by IjzerenHein** [comment]
No worries, let me know if I need to help with testing anything.
Cheers dude, and thanks for this awesome doc generator :)

**Comment by h13i32maru** [comment]
I fixed it. Please try to use HEAD.
https://github.com/esdoc/esdoc/blob/master/CONTRIBUTING.md#install-from-head

**Comment by IjzerenHein** [comment]
Awesome, will try =)

**Comment by IjzerenHein** [comment]
Awesome, works like a charm now :)))
Thanks!!
