### ISSUE TITLE
Documentation for module (Feature Request)

### ISSUE THREAD

**Issue by PinkaminaDianePie** [esdoc/esdoc#66]
It will be great to add support of documentation for module. Ill explain the case: i have module with logicaly grouped helpers. I can use it with 2 ways. With first i need to create class with static helpers, and export it as default. Then i need to use it in this way:
```javascript
import helpers from 'helpers';
helpers.method(); 
helpers.const;
```
With second way ill define all helpers as simple functions and export them all from my module. 
```javascript
let helper = function(){};
export {helper};
```
Then ill use it:
```javascript
import * as helpers from 'helpers';
helpers.method(); 
helpers.const;
```
But with this way i can import only helpers i need, by their names:
```javascript
import {method, const} from 'helpers';
method(); 
const;
```
and using them will be much easier. With static class approach i need to always use it as namespace for my methods. So if i need to export some helpers from my module i will always choose second way of exporting. But the problem of this is i can not documentate module. The only solution i found it is  defining static class and then export methods from them as one namespace. May be it will be better to provide functionality to documentate module?

**Comment by h13i32maru** [comment]
ESDoc supports the following code.

```javascript
/** this is foo1 */
export function foo1(){}

/** this is foo2 */
let foo2 = function(){};

export {foo2}
```

<img width="522" alt="2015-09-06 14 59 53" src="https://cloud.githubusercontent.com/assets/985170/9702813/f55df3a8-54a7-11e5-8891-f718a02903f4.png">


Does this code help you?

**Comment by PinkaminaDianePie** [comment]
@h13i32maru nope. All my functions from separate modules will be shown in general namespace, while if i'll add them to static class - they will be shown in their own namespace. Its a really problem for a big library: if i have a lots of helpers i need to show them together. Or i need to create static class for them, but ill face with problem i already described above.

**Comment by madx** [comment]
I do have the same use-case here

What we are trying to achieve is something like the `/** @module foo */` directive that you can use in JSDoc. You just put it at the top of a file and all the functions exported in this module will be grouped in a `foo` module section in the documentation.

I think that for ESDoc you'll want to add a *Modules* sections (like *Class* or *Function*) in the sidebar

**Comment by h13i32maru** [comment]
@PinkaminaDianePie @madx I understood it!
Currently sidebar of ESDoc displays the grouping identifiers with ``Class/Function/Variable/Typedef``.
But I have new idea that is file/directory base navigation.

<img width="228" alt="2015-09-12 12 58 03" src="https://cloud.githubusercontent.com/assets/985170/9829754/f098d45a-594d-11e5-8339-84dba29ab8c1.png">

- ``Foo.js, BarX.js, BarUtilY.js`` is file
- ``BarDirectory`` is directory
- ``Foo1, Foo2, BarX`` is class
- ``barY1, barY2, barY3`` is function
- ``▼`` is toggle button

I think good this, but this is big change. So I carefully consider.

**Comment by PinkaminaDianePie** [comment]
@h13i32maru i dont really know which way is better, as i see in auto-generated docs from another projects - people really like to keep all docs in single level hierarchy. I think its because of simpler search of intrested class/module. In multi-level hierarchy folder structure may be very deep, so it will be much hard to find what you need. But we still need feature of grouping functionality. Maybe it will be really better to provide tag like ```/** @module foo */``` for manual grouping instead of automatic?

**Comment by h13i32maru** [comment]
@PinkaminaDianePie I do not want to add ``@module`` because more tags increase more complex about ESDoc. And ES6 module is file base module system, so ``@module`` is confusion.

If the multi-level hierarchy will support that switching collapse all and expand all buttons, the problem can be solved by the buttons. And ``Identifier`` page shows all class/function/variable at flat.

Thanks for understand.

**Comment by PinkaminaDianePie** [comment]
@h13i32maru but how do you will provide description for module, without any tags?

**Comment by madx** [comment]
@h13i32maru I understand your concerns about adding an `@module` directive, and the confusion it can generate. It is also IMO a sign of bad design if you need to specify which module a function relates to.

However, the multi-level hierarchy can be quite difficult to use as well.

I have a new proposal for you to consider: Why not simply grouping the functions in the *Function* category by module name?

The rationale here is that a file can contain either a class definition (or multiple classes) or a bunch of functions, in which case it is a module. We would get something like:

![](http://drop.madx.me/2wgrfy8mr8mii23i0a5lhz1q5hzd8z9.png)

I don't think you need to change anything in the parsing code for this, only in the doc generation (correct me if I'm wrong). I also think this is a good compromise.

What do you think?

**Comment by h13i32maru** [comment]
@PinkaminaDianePie @madx Thanks for your proposal.

But I have the following policy.

- ES6 code style is Class Base OOP
- ESDoc mainly support class
- function support is secondly
- ES6 module is **file** base system

```javascript
function foo1(){}
function foo2(){}
// this does not have module name by syntax.
// but this has module name by file name.
export {foo2, foo2}
```

- directory base navigation provides full module name
  - module name confusion is reduced by it
- **ESDoc must use the ones that already exist**
  - code syntax and file/directory structure

So, I do not support ``@module``.
Sorry.

**Comment by madx** [comment]
At least we will have a way to browse the functions per module, which is good :)

I'm not advocating for `@module` either, but as we said, being able to see the module names and not the whole function list would be a big plus.

Let's wait for the implementation of the new navigation then ;)

**Comment by h13i32maru** [comment]
@PinkaminaDianePie @madx I published v0.3.0 with [new side bar style](https://github.com/esdoc/esdoc/issues/84) :rocket:

**Comment by PinkaminaDianePie** [comment]
@h13i32maru interesting, i hope it will solve our problems.

**Comment by Galiaf47** [comment]
Replaced jsdoc by esdoc recently. So my code has module tags and most of functions don't wrapped by classes. 
My index.js file exports some functions as library functions (lib.function) and some functions as modules functions (lib.module.function). So how can I tell esdoc to document my modules for these cases? Is it possible with esdoc or should I return to jsdoc?

**Comment by englercj** [comment]
> My index.js file exports some functions as library functions (lib.function) and some functions as modules functions (lib.module.function). So how can I tell esdoc to document my modules for these cases? Is it possible with esdoc or should I return to jsdoc?

This. I'm having parse issues with jsdoc so tried out esdoc but without modules my docs are very useful. For example I have a class that is exported under a namespace.

Consider a file structure:

```
+-- index.js
+-- folder/
 `-- index.js
 `-- Class.js
```

The root `index.js` looks like:

```js
export * as someModule from './folder';
```

Similarly the `folder/index.js` file looks like:

```js
export { default as Class } from './Class';
```

The root index gets exported to the global namespace, and you use it like:

```js
const thing = new MyLib.someModule.Class();
```

Obviously I want the docs to reflect the fact that in reality you must access `Class` via the `someModule` namespace. As such we need a way to express that here. `@namespace` or something is needed or I unfortunately can't use this module.

**Comment by ProLoser** [comment]
@h13i32maru feel like you should re-open this issue because while many people use classes in their javascript these days, there's absolutely NO reason to make ALL of their code classes, and completely disregarding or hobbling the other _half_ of javascript is just extremely limiting.

I use both classes AND hashes of utility functions. I do NOT want to have to create a bunch of classes with static functions just to document them in a more organized/sane manner.

Please allow grouping of functions rather than treating them like they exist on the global namespace (which they do NOT). Even named exports are flattened into a global namespace, and this breaks the whole point of splitting up your code into separate files.

**Comment by ProLoser** [comment]
Nevermind, I'm just gonna go back to jsdoc.

Documentation coverage and unit test integration features are awesome but they're not worth half of my codebase not being documented properly or being flattened into massive collections of functions and constants because of a design decision.

**Comment by PinkaminaDianePie** [comment]
@ProLoser check http://documentation.js.org/ also. It work nicely with any es-next features, even staged ones and can parse types from Flow annotations. Moved to it from esdoc without any regrets, because first order function support is must-have feature to js since it's not object oriented, but multi-paradigm

**Comment by Telokis** [comment]
@PinkaminaDianePie Thanks for this alternative! It's really good!

**Comment by loopmode** [comment]
@h13i32maru I think that `ES6 code style is Class Base OOP` is simply an incorrect premise. ES6+ is about much more than about classes, especially given its powerful module system. 
A developer who tries to force everything into classes in javascript - for whatever reason - wouldn't last long in my company. And I personally feel ridiculous trying to squeeze everything into classes just for the sake of being able to document with one specific tool. In 90% of the cases, I know that it's the wrong way and another way is much better - but will end up with chaotic docs where everything is in a global scope.

Even if the sidebar groups it somewhat nicely, the document page itself still just lists everything in alphabetical order.
In my case of monorepo workspaces, I end up having `restart` from `client/app/index.js` next to `retrieveAttachments` from `server/controllers/AttachmentController`, just because they both start with an r and I don't use classes. Works when picking things from the index specifically, but makes it horrible to just get an overview of a project's implementation.

**Comment by callingmybluff** [comment]
> @ProLoser check http://documentation.js.org/ also. It work nicely with any es-next features, even staged ones and can parse types from Flow annotations. Moved to it from esdoc without any regrets, because first order function support is must-have feature to js since it's not object oriented, but multi-paradigm

I came to ESDoc because of direct lining between code and comments, along side the coverage page. However, gonna remove it soon and go back to documentation as it supports modules. This is a big deal for many users, whether the dev here liked to confirm to that or not.

**Comment by Aaron3** [comment]
I would point out that `@module` has existed for a while: http://usejsdoc.org/tags-module.html
