### ISSUE TITLE
Is there a way to disable the inclusion of the source code?

### ISSUE THREAD

**Issue by arielschiavoni** [esdoc/esdoc#67]
Hi there,

I have a use case in which I can't expose the source code to the clients.

I was wondering if there is some way to not include the source files in the documentation. (basically remove the `file` folder that is part of the output)

If no, could it be achieved with a plugin?

Thanks!

**Comment by h13i32maru** [comment]
@arielschiavoni Hi! Thanks for this issue!
I consider way to disable inclusion of the source code.

**Comment by h13i32maru** [comment]
I published ESDoc v0.2.5. This version support ``config.includeSource``.
You can config: 
```
{
  ...,
  "includeSource": false
}
```
see https://esdoc.org/config.html for more information.

**Comment by arielschiavoni** [comment]
Wow that was fast :-) !

Thanks!
