### ISSUE TITLE
Config flag for not including source code into output html

### ISSUE THREAD

**Issue by Weitklick** [esdoc/esdoc#68]
I'd love to use esdoc to generate public documentation for a project at Work. But unfortunately, since we are not open-sourcing the code, I cannot use esdoc, as long as it includes the source code.

The idea would be to have a config flag `includeSource` that would default to true. If its set to false, the output html should not contain any source code.

I'd be happy to submit a pull request, If you can give me some pointers as to the best way of implementing this :)

**Comment by h13i32maru** [comment]
@Weitklick Hi! Thanks for this issue!
I consider way to disabled including source code. Please wait a little.

**Comment by h13i32maru** [comment]
I published ESDoc v0.2.5. This version support ``config.includeSource``.
You can config: 
```
{
  ...,
  "includeSource": false
}
```
see https://esdoc.org/config.html for more information.

**Comment by Weitklick** [comment]
Wow, you are fast! Much appreciated, thanks a bunch! :+1:

**Comment by h13i32maru** [comment]
duplicate https://github.com/esdoc/esdoc/issues/67
