### ISSUE TITLE
class member typed as class not reconized

### ISSUE THREAD

**Issue by mookraiser** [esdoc/esdoc#69]
```
export class actor_PartyInput
{
        constructor()
        {
                super();

                /** @type {Long} */
                this.actorId=0;
                /** @type {actor_ActorAccessIdentifier} */
                this.actorAccessIdentifier=new actor_ActorAccessIdentifier();
        }
}

export class actor_ActorAccessIdentifier
{
        constructor()
        {
                super();
        }
}
```
actorAccessIdentifier will be displayed with type '*'

**Comment by h13i32maru** [comment]
@mookraiser Hi! Thanks for this issue!
I try to generate documentation of the code. And the documentation is valid.
<img width="462" alt="2015-09-05 20 34 46" src="https://cloud.githubusercontent.com/assets/985170/9699058/e35bd7aa-540d-11e5-93b8-0b46d81ab00e.png">

I use ESDoc v0.2.4.

**Comment by mookraiser** [comment]
wow, that's weird because I'm using ESDoc v0.2.4 also...

**Comment by h13i32maru** [comment]
@mookraiser Please tell me your repository, if it is possible.
I want to look it.
