### ISSUE TITLE
member detection can fail

### ISSUE THREAD

**Issue by mookraiser** [esdoc/esdoc#70]
Doing this produce 2 members instead of 2 methods.
This way to bind methods in ES6 is recommanded in React for instance
https://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html#autobinding
```
constructor(props) {
         super(props);

         this.onConnect = this.onConnect.bind(this);
         this.onKeyDown = this.onKeyDown.bind(this);
}
```

**Comment by h13i32maru** [comment]
@mookraiser Hi! Thanks for this issue!
This is ESDoc bug. I will try to fix it. Please wait.

**Comment by h13i32maru** [comment]
I fixed it. Please try to use HEAD.
https://github.com/esdoc/esdoc/blob/master/CONTRIBUTING.md#install-from-head
