### ISSUE TITLE
Change side bar navigation style

### ISSUE THREAD

**Issue by h13i32maru** [esdoc/esdoc#84]
Currently side bar is
- sorted by identifier name
- split by kind(class, function, etc)

New side bar is
- sorted by file full path
- not split
- show directory path
- show kind icon

<img width="346" alt="2015-09-20 23 25 31" src="https://cloud.githubusercontent.com/assets/985170/9981135/f1a4bd44-5fee-11e5-8909-745b6a8d8908.png">

**Comment by madx** [comment]
Looks great, better than what I expected :)

**Comment by h13i32maru** [comment]
@madx Thanks! I am glad :smile:
