### ISSUE TITLE
Wrong parsing on subclass starts with "_"

### ISSUE THREAD

**Issue by buzzzzer** [esdoc/esdoc#87]
Expample:
```javascript
'use strict'
class mainClass {
}
class _subClass extends mainClass {
}
```

Regards.

**Comment by h13i32maru** [comment]
The identifier beginning with _ is handled as private. So ``_subClass`` is not documentation.

See [config page](https://esdoc.org/config.html).
- ``config.autoPrivate``
- ``config.access``
