### ISSUE TITLE
@extends tag. Strange behavior

### ISSUE THREAD

**Issue by buzzzzer** [esdoc/esdoc#88]
with @extends tag on subclass looks like:
![sample1](https://cloud.githubusercontent.com/assets/1981785/10068539/cd468f9c-62ad-11e5-855e-aca5340478d5.PNG)
without link to mainclass
but without @extends tag looks ok:
![sampleok](https://cloud.githubusercontent.com/assets/1981785/10068553/f2731344-62ad-11e5-9d9e-5587e550a0f0.PNG)
Sample:
```javascript
'use strict'

/**
 * Some greate class
 */
class mainClass {
}

/**
 * Some subclass, if has extends tag below, looks strange
 * @extends mainClass
 */
class subClass extends mainClass {
}
```

Regards.

**Comment by h13i32maru** [comment]
The ``@extends`` syntax is ``@extends {mainClass}``. Your syntax(``@extends mainClass``) is invalid.

See [@extends tag](https://esdoc.org/tags.html#-extends)
