### ISSUE TITLE
Not an issue - just some proposals

### ISSUE THREAD

**Issue by ralf-o** [esdoc/esdoc#90]
Dear ESDoc team,

you did and do really a great job with ESDoc - thank you very much.
Three  suggestions for enhancements:

1. Wouldn't it be better in case that source code is not included in the API documentation (=> includeSource: false) to get rid of all those "Source" links that only tell: "Sorry, this documentation does not provide source code"?

2. A very minor one: Would it be possible to add a configuration flag to get rid of that import statement on top of the documentation pages (for example "import MyClass from 'my-project/src/module/MyClass.js'")?
It always shows the full project path to the source files, which normally will not be the way the user will import the corresponding class later, so it may be confusing for some projects.

3. A not-so-minor one: One key feature of JavaScript is that it allows meta programming of the kind that classes can be built dynamically, for example:

    ```
    const MySuperFancyClass = SuperFancy.createClass({...someConfigParams});
    export default MySuperFancyClass;
    ```

    You cannot document such classes in ESDoc currently. 
    My suggestion would be to add the following tags: @class, @constructor and @method. 
    All of them trigger a special behavior in ESDoc: ESDoc will ignore completely what source code
    will follow the corresonding apidoc comment. All information to generate the ESDoc is given in
    the comment itself.
    This would be great enhancement I think .. at least for fans of JavaScript meta programming ;-)

Thank you very much in advance.

Best regards
Ralf

**Comment by h13i32maru** [comment]
@ralf-o Hi! Thanks for this proposal :smile: 

1. I will consider to rid the source links.

2. Sorry I do not plan to support the flag. However, you can use [ESDoc Import Path Plugin](https://github.com/esdoc/esdoc-importpath-plugin) in order to help this proposal.

3. Sorry, for now, I do not plan to support the tags for meta programming. Because:
  - I do not almost use meta programming.
  - The tags make more complex ESDoc.

Thanks.

**Comment by pedroteixeira** [comment]
hi @ralf-o , did you manage to find a way to document "dynamic classes"? such as in React.createClass.
I was thinking about a plugin to integrate with react-gendoc in this case.
