### ISSUE TITLE
Import/Export 

### ISSUE THREAD

**Issue by Verikon** [esdoc/esdoc#92]
Great Project.

At this time NodeJS does not support es6 module syntax. I could use a transpiler such as BabelJS to provide this however this will ( by default ) loose native functionality such as generators.

What's the possibility of allowing for CommonJS syntax until they/v8 does?

eg module.exports = class myClass extends myBaseClass {}

**Comment by Verikon** [comment]
On second thoughts I should probably use babelJS and whitelist only module support here as this project is doing what it says - providing a documentation system for es6.

It's a pity node or v8 don't support import/export syntax yet.

Feel free to close this.

**Comment by h13i32maru** [comment]
@Verikon Hi! Thanks for this issue.

> This project is doing what it says - providing a documentation system for es6.

Yes, ESDoc supports ES6. So does not plan to support ``module.exports``.
Thanks.
