### ISSUE TITLE
Repository url is git+https

### ISSUE THREAD

**Issue by silkentrance** [esdoc/esdoc#94]
The generated URL for the repository uses a scheme of git+https, which fails when trying to navigate to that link.

Would it be possible to just make it https instead?

**Comment by h13i32maru** [comment]
@silkentrance Hi! Thanks for this issue.
``repository`` in package.json supports formant in [here](https://docs.npmjs.com/files/package.json#repository)

So, I do not plan to support ``git+https``

Sorry.

**Comment by silkentrance** [comment]
@h13i32maru ups, sorry, I had my package.json wrong. Thanks for the input.
