### ISSUE TITLE
Test Suites

### ISSUE THREAD

**Issue by jaylaw81** [esdoc/esdoc#95]
When will new test suites be added? (Jasmin, Jest, etc...)

**Comment by h13i32maru** [comment]
@jaylaw81 Hi! Thanks for this issue.
Jasmine and Jest are same style with Mocha(``describe`` and ``it``).
So, actually ``config.type: "mocha"`` can work with the test suites.
But I do not know much about the test suites :sweat: 

Please tell me what is different between the test suites syntax and Mocha syntax.

**Comment by indiesquidge** [comment]
@h13i32maru, any chance of some support for [Tape](https://github.com/substack/tape)? It uses the TAP protocol as a test harness.

> _TAP is the [Test Anything Protocol](https://en.wikipedia.org/wiki/Test_Anything_Protocol#History) that has been around since 1987. Almost every important automated testing tool supports TAP output. There are TAP processors that produce colored console reports, processors that make pretty, styled HTML, processors that can branch on results and trigger various hooks, and on and on…_

> _You could think of Tape as a pure CLI tool that takes unit tests as input and produces TAP as output. Using standard Unix tools available on every Node platform, you can integrate tape with literally any tooling that can read from stdin and understand TAP output._

[(_source_)](https://medium.com/javascript-scene/why-i-use-tape-instead-of-mocha-so-should-you-6aa105d8eaf4#.q036bzvx6)

---

I would be more than happy to implement it myself, but I'm having trouble figuring out to do so.
