### ISSUE TITLE
Generic Array consisting of multiple different component types

### ISSUE THREAD

**Issue by silkentrance** [esdoc/esdoc#96]
Say, I'd want to document something like

```
@param {Array<string|function>} param the param
...
```

As of now, the generated documentation will not provide any links for either string or function.

Is there any way to do this?

**Comment by silkentrance** [comment]
Found a workaround, however, this is exactly what I want to express

```
@param {Array<string,function>} param the param
```

**Comment by h13i32maru** [comment]
@silkentrance You can use ``@typedef``

```javascript
/**
 * @typedef {(string|function)} MyUnionType
 */

/**
 *
 * @param {MyUnionType[]} p
 */
function foo(p){}
```

I will try to support it in future version. But now I have no time. Please wait a moment.
Sorry.

**Comment by silkentrance** [comment]
@h13i32maru thanks for the typedef hint, will use it as work around for now instead of string,Object,...

**Comment by h13i32maru** [comment]
The head revision of ESDoc supports union in generics. Please check it.

[Installation from head revision](https://esdoc.org/manual/usage/usage.html#installation)
