### ISSUE TITLE
Introduce Scalar as a placeholder for (number|string|boolean|number)

### ISSUE THREAD

**Issue by silkentrance** [esdoc/esdoc#97]
You currently refer to scalar types as for being 'Simple' types. Would it be possible to replace that by just 'Scalar'? The rationale here would be that we are operating on the programming language level and not on the (xml) schema level.

And, instead of repeatedly writing down

```
@param {(number|string|boolean|number)} param the param
```

I'd like to instead

```
@param {Scalar} param the param
```

With Scalar also supporting generic notation, e.g.

```
@param {Scalar<number,string>} param the param
```

to limit the number of available options in the interface.

**Comment by silkentrance** [comment]
Since mozilla does not provide a general documentation page for the existing scalar types, I reckon that upon

```
@param {Scalar} param the param
```

the following documentation should be generated

```
param : Scalar<number, string, boolean, ...>
```

with the appropriate links pointing towards the official mozilla documentation.

**Comment by raveclassic** [comment]
@silkentrance 
You can use `@typedef` or `@type` to define your custom type and reuse it later.

As long as JS does not support generics, you cannot use them easily. The only way I see is adopting [Google Closure Compiler's `@template` tag](https://developers.google.com/closure/compiler/docs/js-for-compiler#generics) to ES6 classes (it will look very similar to typescript generics. It is also [supported by jsdoc3](https://github.com/jsdoc3/jsdoc/issues/

**Comment by h13i32maru** [comment]
@silkentrance You can use [@typedef](https://esdoc.org/tags.html#-typedef). I do not plan to support ``Scalar``. Because it is far from JavaScript.

@raveclassic Thanks for comment!
