### ISSUE TITLE
Number should support generic notation

### ISSUE THREAD

**Issue by silkentrance** [esdoc/esdoc#98]
Number is very generic, ranging from mere integers to float and double.

It would be nice to be able to limit the numeric range, by say

```
@param {number<int>} param the param
@param {number<float>} param the param
@param {number<double>} param the param
```

While int, of course, could be also made generic in that it comprises of byte, short, long and so on...

**Comment by h13i32maru** [comment]
@silkentrance you can use ``@typedef`` and ``@external`` for int, float, double and etc.
